-- Rollback lotto 8: le cultivar delle madri coinvolte tornano al nome scientifico; le madri col nome cambiato
-- ritrovano il vecchio nome e tolgono il vecchio nome dai nomi_alternativi.
update specie c set nome = c.nome_scientifico from specie p
where p.id = c.specie_padre_id and c.nome <> c.nome_scientifico and p.slug in (
    'acanthus-spinosus',
    'achillea-tomentosa',
    'allium-amethystinum',
    'allium-angulosum',
    'allium-flavum',
    'allium-giganteum',
    'allium-moly',
    'allium-porrum',
    'anthemis-cupaniana',
    'anthericum-ramosum',
    'aquilegia-alpina',
    'arabis-alpina',
    'arnica-montana',
    'asphodeline-lutea',
    'campanula-fragilis',
    'campanula-garganica',
    'campanula-glomerata',
    'campanula-pyramidalis',
    'campanula-raineri',
    'campanula-sibirica',
    'cardamine-heptaphylla',
    'carex-firma',
    'carex-pendula',
    'centaurea-cineraria',
    'centaurea-ragusina',
    'cerastium-tomentosum',
    'clerodendrum-trichotomum',
    'colchicum-bivonae',
    'colchicum-cilicicum',
    'corydalis-solida',
    'crocus-corsicus',
    'crocus-minimus',
    'cymbalaria-pallida',
    'daphne-sericea',
    'dianthus-pavonius',
    'digitalis-ferruginea',
    'doronicum-pardalianches',
    'draba-aizoides',
    'epimedium-alpinum',
    'euonymus-japonicus',
    'euphorbia-ceratocarpa',
    'euphorbia-pithyusa',
    'euphorbia-rigida',
    'fagus-orientalis',
    'festuca-valesiaca',
    'fragaria-moschata',
    'fritillaria-affinis',
    'galatella-linosyris',
    'geranium-nodosum',
    'geranium-pyrenaicum',
    'geranium-reflexum',
    'geranium-versicolor',
    'geum-montanum',
    'gypsophila-repens',
    'hosta-plantaginea',
    'lagunaria-patersonia',
    'leptospermum-scoparium',
    'leucanthemum-maximum',
    'linum-grandiflorum',
    'lunaria-rediviva',
    'lycianthes-rantonnetii',
    'malva-moschata',
    'musa-basjoo',
    'nepeta-nuda',
    'oreomecon-alpina',
    'oxalis-pes-caprae',
    'panicum-virgatum',
    'pelargonium-cucullatum',
    'petrorhagia-saxifraga',
    'phyllostachys-aureosulcata',
    'phyllostachys-sulphurea',
    'phyllostachys-vivax',
    'pinus-virginiana',
    'primula-allionii',
    'primula-florindae',
    'primula-hirsuta',
    'primula-marginata',
    'pseudodictamnus-mediterraneus',
    'quercus-shumardii',
    'ranunculus-gramineus',
    'ranunculus-montanus',
    'rosa-pendulina',
    'rosa-spinosissima',
    'rudbeckia-laciniata',
    'salix-hastata',
    'salix-retusa',
    'salvia-hispanica',
    'saxifraga-exarata',
    'sedum-hispanicum',
    'sempervivum-arachnoideum',
    'silene-acaulis',
    'silene-flos-jovis',
    'streptocarpus-ionanthus',
    'symphyotrichum-novae-angliae',
    'symphyotrichum-pilosum',
    'thalictrum-minus',
    'thymus-herba-barona',
    'thymus-praecox',
    'trifolium-rubens',
    'tulipa-saxatilis',
    'verbascum-chaixii',
    'verbascum-phoeniceum',
    'vinca-difformis',
    'viola-riviniana',
    'viscaria-alpina'
  );

with v(slug, vecchio, nuovo, alt_vecchi, alt_nuovi) as (values
  ('daphne-sericea', 'Dafne sericea', 'Dafne olivella', 'Dafne olivella', 'Dafne sericea'),
  ('euonymus-japonicus', 'Evonimo del Giappone', 'Evonimo giapponese', 'Evonimo giapponese', 'Evonimo del Giappone'),
  ('fragaria-moschata', 'Fragola moscata', 'Fragolina muschiata', 'Fragolina muschiata', 'Fragola moscata'),
  ('linum-grandiflorum', 'Lino scarlatto', 'Lino a fiori grandi', 'Lino a fiori grandi', 'Lino scarlatto'),
  ('panicum-virgatum', 'Panico vergato', 'Panico verga', 'Panico verga', 'Panico vergato')
)
update specie s set nome = v.vecchio, nomi_alternativi = nullif(v.alt_vecchi, '')
from v where s.slug = v.slug and s.nome = v.nuovo;
