-- Rollback righe genere: ripristina il nome scientifico e toglie le righe-specie create (solo se senza piante né cultivar).
update specie s set nome_scientifico = v.vecchio
from (values
  ('abelia', 'Abelia', 'Abelia'),
  ('abies', 'Abies', 'Abies'),
  ('abutilon', 'Abutilon x hybridum', 'Abutilon'),
  ('acacia', 'Acacia dealbata', 'Acacia'),
  ('acaena', 'Acaena', 'Acaena'),
  ('acalypha', 'Acalypha', 'Acalypha'),
  ('acanthus', 'Acanthus', 'Acanthus'),
  ('acer', 'Acer', 'Acer'),
  ('achillea', 'Achillea', 'Achillea'),
  ('achimenes', 'Achimenes', 'Achimenes'),
  ('aconitum', 'Aconitum', 'Aconitum'),
  ('actaea', 'Actaea', 'Actaea'),
  ('adenophora', 'Adenophora', 'Adenophora'),
  ('adonis', 'Adonis', 'Adonis'),
  ('aechmea', 'Aechmea', 'Aechmea'),
  ('aeonium', 'Aeonium arboreum', 'Aeonium'),
  ('aeschynanthus', 'Aeschynanthus', 'Aeschynanthus'),
  ('aesculus', 'Aesculus', 'Aesculus'),
  ('aethionema', 'Aethionema', 'Aethionema'),
  ('agapanto', 'Agapanthus', 'Agapanthus'),
  ('agapetes', 'Agapetes', 'Agapetes'),
  ('agastache', 'Agastache', 'Agastache'),
  ('ageratum', 'Ageratum', 'Ageratum'),
  ('aglaonema', 'Aglaonema', 'Aglaonema'),
  ('ajuga', 'Ajuga', 'Ajuga'),
  ('alchemilla', 'Alchemilla', 'Alchemilla'),
  ('allium', 'Allium', 'Allium'),
  ('alocasia', 'Alocasia', 'Alocasia'),
  ('aloe', 'Aloe', 'Aloe'),
  ('alstroemeria', 'Alstroemeria', 'Alstroemeria'),
  ('alyssum', 'Alyssum', 'Alyssum'),
  ('amaranthus', 'Amaranthus', 'Amaranthus'),
  ('amelanchier', 'Amelanchier', 'Amelanchier'),
  ('amsonia', 'Amsonia', 'Amsonia'),
  ('anemone', 'Anemone', 'Anemone'),
  ('angelonia', 'Angelonia', 'Angelonia'),
  ('anigozanthos', 'Anigozanthos', 'Anigozanthos'),
  ('anisodontea', 'Anisodontea', 'Anisodontea'),
  ('anthurium', 'Anthurium andraeanum', 'Anthurium'),
  ('antirrhinum', 'Antirrhinum', 'Antirrhinum'),
  ('aphelandra', 'Aphelandra', 'Aphelandra'),
  ('aquilegia', 'Aquilegia vulgaris', 'Aquilegia'),
  ('arbutus', 'Arbutus unedo', 'Arbutus'),
  ('ardisia', 'Ardisia', 'Ardisia'),
  ('argyranthemum', 'Argyranthemum', 'Argyranthemum'),
  ('armeria', 'Armeria', 'Armeria'),
  ('arum', 'Arum', 'Arum'),
  ('aruncus', 'Aruncus', 'Aruncus'),
  ('asplenium', 'Asplenium', 'Asplenium'),
  ('astelia', 'Astelia', 'Astelia'),
  ('aster', 'Aster', 'Aster'),
  ('astilbe', 'Astilbe', 'Astilbe'),
  ('astrantia', 'Astrantia', 'Astrantia'),
  ('athyrium', 'Athyrium', 'Athyrium'),
  ('aubrieta', 'Aubrieta', 'Aubrieta'),
  ('aylostera', 'Aylostera', 'Aylostera'),
  ('baptisia', 'Baptisia', 'Baptisia'),
  ('begonia', 'Begonia', 'Begonia'),
  ('berberis', 'Berberis', 'Berberis'),
  ('bergenia', 'Bergenia', 'Bergenia'),
  ('betonica', 'Betonica', 'Betonica'),
  ('betula', 'Betula', 'Betula'),
  ('bidens', 'Bidens', 'Bidens'),
  ('billbergia', 'Billbergia', 'Billbergia'),
  ('bistorta', 'Bistorta', 'Bistorta'),
  ('boehmeria', 'Boehmeria', 'Boehmeria'),
  ('bougainvillea', 'Bougainvillea', 'Bougainvillea'),
  ('brachyglottis', 'Brachyglottis', 'Brachyglottis'),
  ('brachyscome', 'Brachyscome', 'Brachyscome'),
  ('brassica', 'Brassica', 'Brassica'),
  ('brodiaea', 'Brodiaea', 'Brodiaea'),
  ('browallia', 'Browallia', 'Browallia'),
  ('brugmansia', 'Brugmansia suaveolens', 'Brugmansia'),
  ('buddleja', 'Buddleja', 'Buddleja'),
  ('buxus', 'Buxus', 'Buxus'),
  ('caladium', 'Caladium', 'Caladium'),
  ('calathea', 'Calathea', 'Calathea'),
  ('calendula', 'Calendula officinalis', 'Calendula'),
  ('callicarpa', 'Callicarpa', 'Callicarpa'),
  ('callistemon', 'Callistemon', 'Callistemon'),
  ('calycanthus', 'Calycanthus', 'Calycanthus'),
  ('camassia', 'Camassia', 'Camassia'),
  ('camellia', 'Camellia', 'Camellia'),
  ('campanula', 'Campanula isophylla', 'Campanula'),
  ('campsis', 'Campsis', 'Campsis'),
  ('canna', 'Canna', 'Canna'),
  ('capsicum', 'Capsicum', 'Capsicum'),
  ('carex', 'Carex oshimensis', 'Carex'),
  ('caryopteris', 'Caryopteris', 'Caryopteris'),
  ('cassinia', 'Cassinia', 'Cassinia'),
  ('cassiope', 'Cassiope', 'Cassiope'),
  ('castanea', 'Castanea', 'Castanea'),
  ('ceanothus', 'Ceanothus', 'Ceanothus'),
  ('celmisia', 'Celmisia', 'Celmisia'),
  ('celosia', 'Celosia argentea', 'Celosia'),
  ('centaurea', 'Centaurea', 'Centaurea'),
  ('ceratostigma', 'Ceratostigma', 'Ceratostigma'),
  ('cereus', 'Cereus', 'Cereus'),
  ('ceropegia', 'Ceropegia woodii', 'Ceropegia'),
  ('cestrum', 'Cestrum', 'Cestrum'),
  ('chaenomeles', 'Chaenomeles', 'Chaenomeles'),
  ('choisya', 'Choisya', 'Choisya'),
  ('chrysanthemum', 'Chrysanthemum', 'Chrysanthemum'),
  ('cirsium', 'Cirsium', 'Cirsium'),
  ('cistus', 'Cistus', 'Cistus'),
  ('clematis', 'Clematis', 'Clematis'),
  ('cleome', 'Cleome', 'Cleome'),
  ('clerodendrum', 'Clerodendrum', 'Clerodendrum'),
  ('clivia', 'Clivia miniata', 'Clivia'),
  ('colchicum', 'Colchicum', 'Colchicum'),
  ('coleonema', 'Coleonema', 'Coleonema'),
  ('columnea', 'Columnea', 'Columnea'),
  ('coprosma', 'Coprosma', 'Coprosma'),
  ('cordyline', 'Cordyline', 'Cordyline'),
  ('coreopsis', 'Coreopsis grandiflora', 'Coreopsis'),
  ('coriandrum', 'Coriandrum', 'Coriandrum'),
  ('cornus', 'Cornus', 'Cornus'),
  ('correa', 'Correa', 'Correa'),
  ('corydalis', 'Corydalis', 'Corydalis'),
  ('corylus', 'Corylus', 'Corylus'),
  ('cosmos', 'Cosmos', 'Cosmos'),
  ('cotinus', 'Cotinus', 'Cotinus'),
  ('cotoneaster', 'Cotoneaster', 'Cotoneaster'),
  ('cotyledon', 'Cotyledon', 'Cotyledon'),
  ('crassula', 'Crassula', 'Crassula'),
  ('crinum', 'Crinum', 'Crinum'),
  ('crocosmia', 'Crocosmia', 'Crocosmia'),
  ('crocus', 'Crocus', 'Crocus'),
  ('ctenanthe', 'Ctenanthe', 'Ctenanthe'),
  ('cucurbita', 'Cucurbita', 'Cucurbita'),
  ('cuphea', 'Cuphea hyssopifolia', 'Cuphea'),
  ('curcuma', 'Curcuma', 'Curcuma'),
  ('cyclamen', 'Cyclamen persicum', 'Cyclamen'),
  ('cymbidium', 'Cymbidium', 'Cymbidium'),
  ('cypripedium', 'Cypripedium', 'Cypripedium'),
  ('cytisus', 'Cytisus', 'Cytisus'),
  ('dahlia', 'Dahlia', 'Dahlia'),
  ('daphne', 'Daphne', 'Daphne'),
  ('delosperma', 'Delosperma cooperi', 'Delosperma'),
  ('delphinium', 'Delphinium', 'Delphinium'),
  ('dendrobium', 'Dendrobium', 'Dendrobium'),
  ('deutzia', 'Deutzia', 'Deutzia'),
  ('dianella', 'Dianella', 'Dianella'),
  ('dianthus', 'Dianthus', 'Dianthus'),
  ('diascia', 'Diascia', 'Diascia'),
  ('dicentra', 'Dicentra', 'Dicentra'),
  ('dieffenbachia', 'Dieffenbachia', 'Dieffenbachia'),
  ('dierama', 'Dierama', 'Dierama'),
  ('digitalis', 'Digitalis', 'Digitalis'),
  ('dimorphotheca', 'Dimorphotheca', 'Dimorphotheca'),
  ('dionysia', 'Dionysia', 'Dionysia'),
  ('doronicum', 'Doronicum', 'Doronicum'),
  ('draba', 'Draba', 'Draba'),
  ('dracaena', 'Dracaena', 'Dracaena'),
  ('dyckia', 'Dyckia', 'Dyckia'),
  ('echinacea', 'Echinacea purpurea', 'Echinacea'),
  ('echinocereus', 'Echinocereus', 'Echinocereus'),
  ('echinops', 'Echinops', 'Echinops'),
  ('echinopsis', 'Echinopsis', 'Echinopsis'),
  ('echium', 'Echium', 'Echium'),
  ('elaeagnus', 'Elaeagnus', 'Elaeagnus'),
  ('epimedium', 'Epimedium', 'Epimedium'),
  ('epiphyllum', 'Epiphyllum', 'Epiphyllum'),
  ('eremurus', 'Eremurus', 'Eremurus'),
  ('erica', 'Erica carnea', 'Erica'),
  ('erigeron', 'Erigeron', 'Erigeron'),
  ('erodium', 'Erodium', 'Erodium'),
  ('eryngium', 'Eryngium', 'Eryngium'),
  ('erysimum', 'Erysimum', 'Erysimum'),
  ('erythronium', 'Erythronium', 'Erythronium'),
  ('escallonia', 'Escallonia', 'Escallonia'),
  ('eucalyptus', 'Eucalyptus', 'Eucalyptus'),
  ('eucomis', 'Eucomis', 'Eucomis'),
  ('euonymus', 'Euonymus', 'Euonymus'),
  ('eupatorium', 'Eupatorium', 'Eupatorium'),
  ('eustoma', 'Eustoma grandiflorum', 'Eustoma'),
  ('exacum', 'Exacum affine', 'Exacum'),
  ('fagus', 'Fagus', 'Fagus'),
  ('fargesia', 'Fargesia', 'Fargesia'),
  ('felicia', 'Felicia', 'Felicia'),
  ('festuca', 'Festuca', 'Festuca'),
  ('ficus', 'Ficus', 'Ficus'),
  ('filipendula', 'Filipendula', 'Filipendula'),
  ('forsythia', 'Forsythia', 'Forsythia'),
  ('fragaria', 'Fragaria', 'Fragaria'),
  ('freesia', 'Freesia', 'Freesia'),
  ('fremontodendron', 'Fremontodendron', 'Fremontodendron'),
  ('fritillaria', 'Fritillaria', 'Fritillaria'),
  ('fuchsia', 'Fuchsia', 'Fuchsia'),
  ('gaillardia', 'Gaillardia', 'Gaillardia'),
  ('galanthus', 'Galanthus', 'Galanthus'),
  ('gardenia', 'Gardenia jasminoides', 'Gardenia'),
  ('gaultheria', 'Gaultheria', 'Gaultheria'),
  ('gazania', 'Gazania rigens', 'Gazania'),
  ('genista', 'Genista', 'Genista'),
  ('gentiana', 'Gentiana', 'Gentiana'),
  ('geranium', 'Geranium', 'Geranium'),
  ('gerbera', 'Gerbera jamesonii', 'Gerbera'),
  ('geum', 'Geum', 'Geum'),
  ('gibasis', 'Gibasis', 'Gibasis'),
  ('gladiolus', 'Gladiolus', 'Gladiolus'),
  ('glandora', 'Glandora', 'Glandora'),
  ('gloriosa', 'Gloriosa superba', 'Gloriosa'),
  ('gomphrena', 'Gomphrena globosa', 'Gomphrena'),
  ('grevillea', 'Grevillea', 'Grevillea'),
  ('guzmania', 'Guzmania', 'Guzmania'),
  ('gymnocalycium', 'Gymnocalycium', 'Gymnocalycium'),
  ('gypsophila', 'Gypsophila', 'Gypsophila'),
  ('hamamelis', 'Hamamelis', 'Hamamelis'),
  ('haworthia', 'Haworthia', 'Haworthia'),
  ('haworthiopsis', 'Haworthiopsis', 'Haworthiopsis'),
  ('hedychium', 'Hedychium', 'Hedychium'),
  ('helenium', 'Helenium', 'Helenium'),
  ('helianthemum', 'Helianthemum', 'Helianthemum'),
  ('helianthus', 'Helianthus', 'Helianthus'),
  ('helichrysum', 'Helichrysum', 'Helichrysum'),
  ('heliotropium', 'Heliotropium', 'Heliotropium'),
  ('hemerocallis', 'Hemerocallis', 'Hemerocallis'),
  ('hibiscus', 'Hibiscus rosa-sinensis', 'Hibiscus'),
  ('hippeastrum', 'Hippeastrum', 'Hippeastrum'),
  ('hoheria', 'Hoheria', 'Hoheria'),
  ('hoya', 'Hoya carnosa', 'Hoya'),
  ('hyacinthus', 'Hyacinthus orientalis', 'Hyacinthus'),
  ('hydrangea', 'Hydrangea macrophylla', 'Hydrangea'),
  ('hylotelephium', 'Hylotelephium', 'Hylotelephium'),
  ('hypericum', 'Hypericum', 'Hypericum'),
  ('iberis', 'Iberis', 'Iberis'),
  ('ilex', 'Ilex', 'Ilex'),
  ('impatiens', 'Impatiens walleriana', 'Impatiens'),
  ('indigofera', 'Indigofera', 'Indigofera'),
  ('ipheion', 'Ipheion', 'Ipheion'),
  ('ipomoea', 'Ipomoea', 'Ipomoea'),
  ('iresine', 'Iresine', 'Iresine'),
  ('iris', 'Iris', 'Iris'),
  ('ismene', 'Ismene', 'Ismene'),
  ('isotoma', 'Isotoma', 'Isotoma'),
  ('ixia', 'Ixia', 'Ixia'),
  ('jatropha', 'Jatropha podagrica', 'Jatropha'),
  ('juniperus', 'Juniperus', 'Juniperus'),
  ('justicia', 'Justicia carnea', 'Justicia'),
  ('kalanchoe', 'Kalanchoe blossfeldiana', 'Kalanchoe'),
  ('kalimeris', 'Kalimeris', 'Kalimeris'),
  ('kohleria', 'Kohleria', 'Kohleria'),
  ('laburnum', 'Laburnum', 'Laburnum'),
  ('lachenalia', 'Lachenalia', 'Lachenalia'),
  ('lagerstroemia', 'Lagerstroemia', 'Lagerstroemia'),
  ('lampranthus', 'Lampranthus', 'Lampranthus'),
  ('lantana', 'Lantana', 'Lantana'),
  ('lathyrus', 'Lathyrus', 'Lathyrus'),
  ('lavandula', 'Lavandula', 'Lavandula'),
  ('leptospermum', 'Leptospermum', 'Leptospermum'),
  ('leucadendron', 'Leucadendron', 'Leucadendron'),
  ('leucanthemum', 'Leucanthemum', 'Leucanthemum'),
  ('leucocoryne', 'Leucocoryne', 'Leucocoryne'),
  ('leucothoe', 'Leucothoe', 'Leucothoe'),
  ('lewisia', 'Lewisia cotyledon', 'Lewisia'),
  ('ligularia', 'Ligularia', 'Ligularia'),
  ('ligustrum', 'Ligustrum', 'Ligustrum'),
  ('lilium', 'Lilium', 'Lilium'),
  ('linaria', 'Linaria', 'Linaria'),
  ('liriope', 'Liriope', 'Liriope'),
  ('lobelia', 'Lobelia', 'Lobelia'),
  ('lonicera', 'Lonicera', 'Lonicera'),
  ('lotus', 'Lotus', 'Lotus'),
  ('lupinus', 'Lupinus', 'Lupinus'),
  ('lysimachia', 'Lysimachia', 'Lysimachia'),
  ('magnolia', 'Magnolia', 'Magnolia'),
  ('mahonia', 'Mahonia', 'Mahonia'),
  ('malus', 'Malus', 'Malus'),
  ('malva', 'Malva', 'Malva'),
  ('mandevilla', 'Mandevilla splendens', 'Mandevilla'),
  ('massonia', 'Massonia', 'Massonia'),
  ('matthiola', 'Matthiola', 'Matthiola'),
  ('meconopsis', 'Meconopsis', 'Meconopsis'),
  ('medinilla', 'Medinilla magnifica', 'Medinilla'),
  ('mentha', 'Mentha', 'Mentha'),
  ('mimulus', 'Mimulus', 'Mimulus'),
  ('miscanthus', 'Miscanthus', 'Miscanthus'),
  ('monarda', 'Monarda', 'Monarda'),
  ('monstera', 'Monstera', 'Monstera'),
  ('morus', 'Morus', 'Morus'),
  ('muscari', 'Muscari', 'Muscari'),
  ('myosotis', 'Myosotis', 'Myosotis'),
  ('narcissus', 'Narcissus', 'Narcissus'),
  ('nemesia', 'Nemesia', 'Nemesia'),
  ('neoregelia', 'Neoregelia carolinae', 'Neoregelia'),
  ('nepenthes', 'Nepenthes', 'Nepenthes'),
  ('nepeta', 'Nepeta', 'Nepeta'),
  ('nephrolepis', 'Nephrolepis', 'Nephrolepis'),
  ('nerine', 'Nerine', 'Nerine'),
  ('nicotiana', 'Nicotiana', 'Nicotiana'),
  ('nidularium', 'Nidularium', 'Nidularium'),
  ('nymphaea', 'Nymphaea', 'Nymphaea'),
  ('ocimum', 'Ocimum', 'Ocimum'),
  ('oenothera', 'Oenothera', 'Oenothera'),
  ('olearia', 'Olearia', 'Olearia'),
  ('oncidium', 'Oncidium', 'Oncidium'),
  ('ophiopogon', 'Ophiopogon', 'Ophiopogon'),
  ('opuntia', 'Opuntia', 'Opuntia'),
  ('orchidea', 'Phalaenopsis', 'Phalaenopsis'),
  ('origanum', 'Origanum', 'Origanum'),
  ('osteospermum', 'Osteospermum ecklonis', 'Osteospermum'),
  ('ourisia', 'Ourisia', 'Ourisia'),
  ('oxalis', 'Oxalis', 'Oxalis'),
  ('ozothamnus', 'Ozothamnus', 'Ozothamnus'),
  ('paeonia', 'Paeonia', 'Paeonia'),
  ('panicum', 'Panicum', 'Panicum'),
  ('papaver', 'Papaver', 'Papaver'),
  ('paphiopedilum', 'Paphiopedilum', 'Paphiopedilum'),
  ('parthenocissus', 'Parthenocissus', 'Parthenocissus'),
  ('passiflora', 'Passiflora caerulea', 'Passiflora'),
  ('paulownia', 'Paulownia', 'Paulownia'),
  ('pelargonium', 'Pelargonium', 'Pelargonium'),
  ('penstemon', 'Penstemon', 'Penstemon'),
  ('peperomia', 'Peperomia', 'Peperomia'),
  ('persicaria', 'Persicaria', 'Persicaria'),
  ('petunia', 'Petunia', 'Petunia'),
  ('philadelphus', 'Philadelphus', 'Philadelphus'),
  ('philodendron', 'Philodendron', 'Philodendron'),
  ('phlomis', 'Phlomis', 'Phlomis'),
  ('phlox', 'Phlox', 'Phlox'),
  ('phormium', 'Phormium', 'Phormium'),
  ('photinia', 'Photinia', 'Photinia'),
  ('phragmipedium', 'Phragmipedium', 'Phragmipedium'),
  ('phygelius', 'Phygelius', 'Phygelius'),
  ('pieris', 'Pieris', 'Pieris'),
  ('pilea', 'Pilea', 'Pilea'),
  ('pinguicula', 'Pinguicula', 'Pinguicula'),
  ('pinus', 'Pinus', 'Pinus'),
  ('pittosporum', 'Pittosporum', 'Pittosporum'),
  ('platanus', 'Platanus', 'Platanus'),
  ('plectranthus', 'Plectranthus', 'Plectranthus'),
  ('pleroma', 'Pleroma', 'Pleroma'),
  ('plumbago', 'Plumbago auriculata', 'Plumbago'),
  ('podocarpus', 'Podocarpus', 'Podocarpus'),
  ('podophyllum', 'Podophyllum', 'Podophyllum'),
  ('polemonium', 'Polemonium', 'Polemonium'),
  ('polygala', 'Polygala', 'Polygala'),
  ('polypodium', 'Polypodium', 'Polypodium'),
  ('polystichum', 'Polystichum', 'Polystichum'),
  ('potentilla', 'Potentilla', 'Potentilla'),
  ('primula', 'Primula vulgaris', 'Primula'),
  ('prostanthera', 'Prostanthera', 'Prostanthera'),
  ('protea', 'Protea', 'Protea'),
  ('prunella', 'Prunella', 'Prunella'),
  ('prunus', 'Prunus', 'Prunus'),
  ('pseudopanax', 'Pseudopanax', 'Pseudopanax'),
  ('pulmonaria', 'Pulmonaria', 'Pulmonaria'),
  ('pyracantha', 'Pyracantha', 'Pyracantha'),
  ('quercus', 'Quercus', 'Quercus'),
  ('ranunculus', 'Ranunculus', 'Ranunculus'),
  ('rebutia', 'Rebutia', 'Rebutia'),
  ('rheum', 'Rheum', 'Rheum'),
  ('rhodanthemum', 'Rhodanthemum', 'Rhodanthemum'),
  ('rhododendron', 'Rhododendron simsii', 'Rhododendron'),
  ('ribes', 'Ribes', 'Ribes'),
  ('rodgersia', 'Rodgersia', 'Rodgersia'),
  ('rosa', 'Rosa', 'Rosa'),
  ('rubus', 'Rubus', 'Rubus'),
  ('rudbeckia', 'Rudbeckia', 'Rudbeckia'),
  ('ruta', 'Ruta graveolens', 'Ruta'),
  ('salix', 'Salix', 'Salix'),
  ('salvia', 'Salvia officinalis', 'Salvia'),
  ('sambucus', 'Sambucus', 'Sambucus'),
  ('sanguisorba', 'Sanguisorba', 'Sanguisorba'),
  ('sansevieria', 'Sansevieria trifasciata', 'Sansevieria'),
  ('santolina', 'Santolina', 'Santolina'),
  ('saponaria', 'Saponaria ocymoides', 'Saponaria'),
  ('sarcococca', 'Sarcococca', 'Sarcococca'),
  ('sarracenia', 'Sarracenia', 'Sarracenia'),
  ('saxifraga', 'Saxifraga', 'Saxifraga'),
  ('scabiosa', 'Scabiosa', 'Scabiosa'),
  ('schefflera', 'Schefflera', 'Schefflera'),
  ('scilla', 'Scilla', 'Scilla'),
  ('sedum', 'Sedum', 'Sedum'),
  ('semiaquilegia', 'Semiaquilegia', 'Semiaquilegia'),
  ('sempervivum', 'Sempervivum', 'Sempervivum'),
  ('senecio', 'Senecio', 'Senecio'),
  ('sesleria', 'Sesleria', 'Sesleria'),
  ('sidalcea', 'Sidalcea', 'Sidalcea'),
  ('silene', 'Silene', 'Silene'),
  ('sinningia', 'Sinningia speciosa', 'Sinningia'),
  ('solanum', 'Solanum', 'Solanum'),
  ('soldanella', 'Soldanella', 'Soldanella'),
  ('solidago', 'Solidago', 'Solidago'),
  ('sophora', 'Sophora', 'Sophora'),
  ('sorbus', 'Sorbus', 'Sorbus'),
  ('spathiphyllum', 'Spathiphyllum wallisii', 'Spathiphyllum'),
  ('sphaeralcea', 'Sphaeralcea', 'Sphaeralcea'),
  ('spigelia', 'Spigelia', 'Spigelia'),
  ('spiraea', 'Spiraea', 'Spiraea'),
  ('stachyurus', 'Stachyurus', 'Stachyurus'),
  ('stephanotis', 'Stephanotis floribunda', 'Stephanotis'),
  ('symphoricarpos', 'Symphoricarpos', 'Symphoricarpos'),
  ('symphyotrichum', 'Symphyotrichum', 'Symphyotrichum'),
  ('symphytum', 'Symphytum', 'Symphytum'),
  ('syngonium', 'Syngonium', 'Syngonium'),
  ('syringa', 'Syringa', 'Syringa'),
  ('tagetes', 'Tagetes', 'Tagetes'),
  ('tamarix', 'Tamarix', 'Tamarix'),
  ('taxodium', 'Taxodium', 'Taxodium'),
  ('telopea', 'Telopea', 'Telopea'),
  ('teucrium', 'Teucrium', 'Teucrium'),
  ('thalictrum', 'Thalictrum', 'Thalictrum'),
  ('thunbergia', 'Thunbergia alata', 'Thunbergia'),
  ('thymus', 'Thymus', 'Thymus'),
  ('tiarella', 'Tiarella', 'Tiarella'),
  ('tibouchina', 'Tibouchina', 'Tibouchina'),
  ('tilia', 'Tilia', 'Tilia'),
  ('tillandsia', 'Tillandsia', 'Tillandsia'),
  ('tithonia', 'Tithonia', 'Tithonia'),
  ('torenia', 'Torenia', 'Torenia'),
  ('trachelospermum', 'Trachelospermum', 'Trachelospermum'),
  ('tradescantia', 'Tradescantia zebrina', 'Tradescantia'),
  ('tricyrtis', 'Tricyrtis', 'Tricyrtis'),
  ('trifolium', 'Trifolium', 'Trifolium'),
  ('trillium', 'Trillium', 'Trillium'),
  ('triteleia', 'Triteleia', 'Triteleia'),
  ('trollius', 'Trollius', 'Trollius'),
  ('tulbaghia', 'Tulbaghia', 'Tulbaghia'),
  ('tulipa', 'Tulipa', 'Tulipa'),
  ('ulmus', 'Ulmus', 'Ulmus'),
  ('vaccinium', 'Vaccinium', 'Vaccinium'),
  ('vanda', 'Vanda', 'Vanda'),
  ('verbascum', 'Verbascum', 'Verbascum'),
  ('verbena', 'Verbena hybrida', 'Verbena'),
  ('veronica', 'Veronica', 'Veronica'),
  ('veronicastrum', 'Veronicastrum', 'Veronicastrum'),
  ('viburnum', 'Viburnum', 'Viburnum'),
  ('vicia', 'Vicia', 'Vicia'),
  ('viola', 'Viola', 'Viola'),
  ('viscaria', 'Viscaria', 'Viscaria'),
  ('vitis', 'Vitis', 'Vitis'),
  ('weigela', 'Weigela', 'Weigela'),
  ('westringia', 'Westringia', 'Westringia'),
  ('wisteria', 'Wisteria', 'Wisteria'),
  ('yucca', 'Yucca', 'Yucca'),
  ('zantedeschia', 'Zantedeschia aethiopica', 'Zantedeschia'),
  ('zinnia', 'Zinnia elegans', 'Zinnia'),
  ('zygopetalum', 'Zygopetalum', 'Zygopetalum')
) as v(slug, vecchio, genere)
where s.slug = v.slug and s.nome_scientifico = v.genere || ' spp.' and s.specie_padre_id is null;

delete from specie s using (values
  ('anthurium-andraeanum'),
  ('carex-oshimensis'),
  ('ceropegia-woodii'),
  ('coreopsis-grandiflora'),
  ('cuphea-hyssopifolia'),
  ('delosperma-cooperi'),
  ('erica-carnea'),
  ('gerbera-jamesonii'),
  ('plumbago-auriculata'),
  ('tradescantia-zebrina'),
  ('zinnia-elegans')
) as v(slug) where s.slug = v.slug
  and not exists (select 1 from piante p where p.specie = s.slug)
  and not exists (select 1 from specie c where c.specie_padre_id = s.id);
