-- La colonna slug mancava nell'import di #128: piante.json referenzia le
-- specie per slug (chiave dell'oggetto in specie.json, es. "pomodoro"), non
-- per nome visualizzato ("Pomodoro") — store.specie[pianta.specie] in tutta
-- l'app si aspetta quella chiave. Senza questa colonna, il collegamento
-- pianta -> specie si sarebbe rotto silenziosamente passando a Supabase.

alter table specie add column slug text;

update specie set slug = $t$aeonium$t$ where nome = $t$Aeonium$t$;
update specie set slug = $t$agapanto$t$ where nome = $t$Agapanto$t$;
update specie set slug = $t$agave$t$ where nome = $t$Agave$t$;
update specie set slug = $t$alisso$t$ where nome = $t$Alisso$t$;
update specie set slug = $t$allium-sphaerocephalon$t$ where nome = $t$Allium sphaerocephalon$t$;
update specie set slug = $t$alloro$t$ where nome = $t$Alloro$t$;
update specie set slug = $t$anthurium$t$ where nome = $t$Anthurium$t$;
update specie set slug = $t$aquilegia$t$ where nome = $t$Aquilegia$t$;
update specie set slug = $t$arancio-navel$t$ where nome = $t$Arancio Navel$t$;
update specie set slug = $t$avocado$t$ where nome = $t$Avocado$t$;
update specie set slug = $t$basilico$t$ where nome = $t$Basilico$t$;
update specie set slug = $t$bellis-perennis$t$ where nome = $t$Bellis perennis$t$;
update specie set slug = $t$cactus-ago-di-eva-monstroso$t$ where nome = $t$Cactus Ago di Eva (mostruoso)$t$;
update specie set slug = $t$calancola$t$ where nome = $t$Calancola$t$;
update specie set slug = $t$calathea$t$ where nome = $t$Calathea$t$;
update specie set slug = $t$calendula$t$ where nome = $t$Calendula$t$;
update specie set slug = $t$calibrachoa$t$ where nome = $t$Calibrachoa$t$;
update specie set slug = $t$camelia$t$ where nome = $t$Camelia$t$;
update specie set slug = $t$carex$t$ where nome = $t$Carex$t$;
update specie set slug = $t$centaurea-ragusina$t$ where nome = $t$Centaurea ragusina$t$;
update specie set slug = $t$ceropegia$t$ where nome = $t$Ceropegia$t$;
update specie set slug = $t$cetriolo$t$ where nome = $t$Cetriolo$t$;
update specie set slug = $t$clematis-montana$t$ where nome = $t$Clematis montana$t$;
update specie set slug = $t$coreopsis$t$ where nome = $t$Coreopsis$t$;
update specie set slug = $t$cosmos-atrosanguineus$t$ where nome = $t$Cosmo cioccolato$t$;
update specie set slug = $t$cuphea$t$ where nome = $t$Cuphea$t$;
update specie set slug = $t$delosperma$t$ where nome = $t$Delosperma$t$;
update specie set slug = $t$echeveria$t$ where nome = $t$Echeveria$t$;
update specie set slug = $t$echinacea$t$ where nome = $t$Echinacea$t$;
update specie set slug = $t$erba-cipollina$t$ where nome = $t$Erba cipollina$t$;
update specie set slug = $t$erica$t$ where nome = $t$Erica$t$;
update specie set slug = $t$erica-del-messico$t$ where nome = $t$Erica del Messico$t$;
update specie set slug = $t$falso-gelsomino$t$ where nome = $t$Falso gelsomino$t$;
update specie set slug = $t$ferocactus$t$ where nome = $t$Ferocactus$t$;
update specie set slug = $t$fico-di-mare$t$ where nome = $t$Fico di mare$t$;
update specie set slug = $t$ficus-ginseng$t$ where nome = $t$Ficus ginseng$t$;
update specie set slug = $t$fittonia$t$ where nome = $t$Fittonia$t$;
update specie set slug = $t$fragola-rifiorente$t$ where nome = $t$Fragola rifiorente$t$;
update specie set slug = $t$garofano$t$ where nome = $t$Garofano$t$;
update specie set slug = $t$gasteria$t$ where nome = $t$Gasteria$t$;
update specie set slug = $t$gaura$t$ where nome = $t$Gaura$t$;
update specie set slug = $t$gazania$t$ where nome = $t$Gazania$t$;
update specie set slug = $t$geranio-parigino$t$ where nome = $t$Geranio parigino$t$;
update specie set slug = $t$geranio-zonale$t$ where nome = $t$Geranio zonale$t$;
update specie set slug = $t$gerbera$t$ where nome = $t$Gerbera$t$;
update specie set slug = $t$glechoma-hederacea$t$ where nome = $t$Glechoma hederacea$t$;
update specie set slug = $t$heuchera$t$ where nome = $t$Heuchera$t$;
update specie set slug = $t$iberis-sempervirens$t$ where nome = $t$Iberis sempervirens$t$;
update specie set slug = $t$ipoeste$t$ where nome = $t$Ipoeste$t$;
update specie set slug = $t$iris-spontaneo$t$ where nome = $t$Sisyrinchium$t$;
update specie set slug = $t$lavanda$t$ where nome = $t$Lavanda$t$;
update specie set slug = $t$lewisia$t$ where nome = $t$Lewisia$t$;
update specie set slug = $t$lucky-bamboo$t$ where nome = $t$Lucky Bamboo$t$;
update specie set slug = $t$mammillaria$t$ where nome = $t$Mammillaria$t$;
update specie set slug = $t$mammillaria-allungata$t$ where nome = $t$Mammillaria allungata$t$;
update specie set slug = $t$mammillaria-piumosa$t$ where nome = $t$Mammillaria piumosa$t$;
update specie set slug = $t$mandarino-cinese$t$ where nome = $t$Mandarino cinese (Kumquat)$t$;
update specie set slug = $t$margherita-delle-canarie$t$ where nome = $t$Margherita delle Canarie$t$;
update specie set slug = $t$marsilea-quadrifolia$t$ where nome = $t$Marsilea quadrifolia$t$;
update specie set slug = $t$melanzana$t$ where nome = $t$Melanzana$t$;
update specie set slug = $t$mesembriantemo$t$ where nome = $t$Mesembriantemo$t$;
update specie set slug = $t$narciso$t$ where nome = $t$Narciso$t$;
update specie set slug = $t$orchidea$t$ where nome = $t$Orchidea$t$;
update specie set slug = $t$origano$t$ where nome = $t$Origano$t$;
update specie set slug = $t$osteospermum$t$ where nome = $t$Osteospermum$t$;
update specie set slug = $t$passiflora-caerulea$t$ where nome = $t$Passiflora caerulea$t$;
update specie set slug = $t$pennisetum-cinese$t$ where nome = $t$Pennisetum cinese$t$;
update specie set slug = $t$peperoncino$t$ where nome = $t$Peperoncino$t$;
update specie set slug = $t$pianta-della-fortuna$t$ where nome = $t$Pianta della Fortuna$t$;
update specie set slug = $t$pianta-delle-monete$t$ where nome = $t$Pianta delle Monete$t$;
update specie set slug = $t$pianta-panda$t$ where nome = $t$Pianta panda$t$;
update specie set slug = $t$plumbago$t$ where nome = $t$Plumbago$t$;
update specie set slug = $t$pomodoro$t$ where nome = $t$Pomodoro$t$;
update specie set slug = $t$pothos$t$ where nome = $t$Pothos$t$;
update specie set slug = $t$pothos-talea$t$ where nome = $t$pothos-talea$t$;
update specie set slug = $t$prezzemolo$t$ where nome = $t$Prezzemolo$t$;
update specie set slug = $t$primula$t$ where nome = $t$Primula$t$;
update specie set slug = $t$prunus-taoflora$t$ where nome = $t$Prunus taoflora$t$;
update specie set slug = $t$rosmarino$t$ where nome = $t$Rosmarino$t$;
update specie set slug = $t$salcerella$t$ where nome = $t$Salcerella$t$;
update specie set slug = $t$salvia$t$ where nome = $t$Salvia$t$;
update specie set slug = $t$sansevieria$t$ where nome = $t$Sansevieria$t$;
update specie set slug = $t$saponaria$t$ where nome = $t$Saponaria$t$;
update specie set slug = $t$sassifraga$t$ where nome = $t$Sassifraga$t$;
update specie set slug = $t$saxifraga$t$ where nome = $t$saxifraga$t$;
update specie set slug = $t$scalogno$t$ where nome = $t$Scalogno$t$;
update specie set slug = $t$scilla-marittima$t$ where nome = $t$Scilla marittima$t$;
update specie set slug = $t$sedum-acre$t$ where nome = $t$Sedum acre$t$;
update specie set slug = $t$sedum-makinoi$t$ where nome = $t$Sedum makinoi$t$;
update specie set slug = $t$sedum-morganianum$t$ where nome = $t$Sedum morganianum$t$;
update specie set slug = $t$sedum-spurium$t$ where nome = $t$Sedum spurium$t$;
update specie set slug = $t$senecio$t$ where nome = $t$Senecio$t$;
update specie set slug = $t$spiraea-arguta$t$ where nome = $t$Spiraea arguta$t$;
update specie set slug = $t$stipa-tenuissima$t$ where nome = $t$Stipa tenuissima$t$;
update specie set slug = $t$timo-serpillo$t$ where nome = $t$Timo serpillo$t$;
update specie set slug = $t$tradescantia$t$ where nome = $t$Tradescantia$t$;
update specie set slug = $t$ulivo$t$ where nome = $t$Ulivo$t$;
update specie set slug = $t$uva-di-gatto$t$ where nome = $t$Uva di gatto$t$;
update specie set slug = $t$verbena$t$ where nome = $t$Verbena$t$;
update specie set slug = $t$violaciocca$t$ where nome = $t$Violaciocca$t$;
update specie set slug = $t$zinnia$t$ where nome = $t$Zinnia$t$;
update specie set slug = $t$zinnia-angustifolia$t$ where nome = $t$Zinnia a foglia stretta$t$;
update specie set slug = $t$zucca$t$ where nome = $t$Zucca$t$;
update specie set slug = $t$zucchina$t$ where nome = $t$Zucchina$t$;
update specie set slug = $t$zz-plant$t$ where nome = $t$ZZ Plant$t$;
alter table specie alter column slug set not null;
alter table specie add constraint specie_slug_key unique (slug);
