-- Fase 3, enciclopedia-piante-da-arbusti, batch residuo: generi Escallonia,
-- Euonymus, Forsythia (fonti/ridimensionate/19.md), le sole pagine del libro
-- rimaste fuori dal batch01 (comparivano solo nella tabella riepilogativa
-- 18.md senza sezione narrativa propria). Stesso criterio del batch01: righe
-- PFAF esistenti arricchite in append, nuove specie inserite in bozza con
-- on conflict do nothing, fonte tracciata per riga.

update specie set descrizione = descrizione || $t$ Soffre i forti geli, raggiunge rapidamente 4 m; foglie ovato-oblunghe verde-lucente con nervature chiare e margini dentati, lunghe 2,5-5 cm; fiori rosa o porpora scuro, lunghi 2,5-10 cm, in racemi terminali (giugno-luglio).$t$, fonti = array_append(fonti, $t$Il giardino di arbusti (Edicart, 1995) — Escallonia rubra$t$) where slug = $t$escallonia-rubra$t$ and not ($t$Il giardino di arbusti (Edicart, 1995) — Escallonia rubra$t$ = any(fonti));
update specie set descrizione = descrizione || $t$ Portamento sferico ramificato, crescita lenta, fino a 2 m; rami marrone alati, foglie ovali finemente seghettate verdi-lucenti (1,5-7 cm), rosso vermiglio in autunno; fiori giallo-verdognoli, frutti rosso-brunastri con semi arancioni.$t$, fonti = array_append(fonti, $t$Il giardino di arbusti (Edicart, 1995) — Euonymus alatus$t$) where slug = $t$euonymus-alatus$t$ and not ($t$Il giardino di arbusti (Edicart, 1995) — Euonymus alatus$t$ = any(fonti));
update specie set descrizione = descrizione || $t$ Berretta da prete o fusaggine, fino a 7 m, ramificazioni verdi con ali sugherose, foglie ovato-lanceolate seghettate (3-8 cm) rosso-rosate in autunno, fiori bianco-verdognoli, frutti rosati a forma quadrata con semi arancioni; 'Red Cascade' ha frutti rosa intenso.$t$, fonti = array_append(fonti, $t$Il giardino di arbusti (Edicart, 1995) — Euonymus europaeus$t$) where slug = $t$euonymus-europaeus$t$ and not ($t$Il giardino di arbusti (Edicart, 1995) — Euonymus europaeus$t$ = any(fonti));
update specie set descrizione = descrizione || $t$ Raggiunge 2 m, ramificazioni vigorose arcuate, foglie ovali trilobate, fiori giallo chiaro; 'Lynwood' rami più rigidi e fiori più grandi, 'Spectabilis' fino a 4 m con fioritura abbondante giallo-oro; adatta a siepi, tollera potatura radicale.$t$, fonti = array_append(fonti, $t$Il giardino di arbusti (Edicart, 1995) — Forsythia x intermedia$t$) where slug = $t$forsythia-x-intermedia$t$ and not ($t$Il giardino di arbusti (Edicart, 1995) — Forsythia x intermedia$t$ = any(fonti));
update specie set descrizione = descrizione || $t$ Raggiunge 2-3 m (utilizzabile come rampicante), ramificazioni arcuate che possono radicare, foglie ovali spesso trifogliate verde scuro, fiori penduli giallo-oro (2-3 cm) in mazzetti di 2-4; 'Nymans' crescita vigorosa con rami bruno-rossicci o nero-brunastri, fiori giallo chiaro.$t$, fonti = array_append(fonti, $t$Il giardino di arbusti (Edicart, 1995) — Forsythia suspensa$t$) where slug = $t$forsythia-suspensa$t$ and not ($t$Il giardino di arbusti (Edicart, 1995) — Forsythia suspensa$t$ = any(fonti));

insert into specie (nome, nome_scientifico, slug, ciclo_vitale, descrizione, esigenze, fonti, stato_verifica) values ($t$Escallonia virgata$t$, $t$Escallonia virgata$t$, $t$escallonia-virgata$t$, $t$perenne$t$, $t$Abbastanza resistente al gelo, 1,8-3 m, fiorisce maggio-luglio; adatta a crescere in ombra, in terra ben drenata e non calcarea; ramificazioni ricurvate, foglie caduche piccole, fiori piccoli bianchi.$t$, $t${"luce": "Ombra"}$t$::jsonb, ARRAY[$t$Il giardino di arbusti (Edicart, 1995) — Escallonia virgata$t$]::text[], $t$bozza$t$) on conflict (slug) do nothing;
insert into specie (nome, nome_scientifico, slug, ciclo_vitale, descrizione, esigenze, fonti, stato_verifica) values ($t$Euonymus phellomanus$t$, $t$Euonymus phellomanus$t$, $t$euonymus-phellomanus$t$, $t$perenne$t$, $t$Alto 5-6 m, ramificazioni alate, foglie che si tingono di rosso (6-10 cm), frutti rosa con semi di un rosso vivo.$t$, $t${"luce": "Pieno sole / Mezz'ombra / Ombra"}$t$::jsonb, ARRAY[$t$Il giardino di arbusti (Edicart, 1995) — Euonymus phellomanus$t$]::text[], $t$bozza$t$) on conflict (slug) do nothing;
insert into specie (nome, nome_scientifico, slug, ciclo_vitale, descrizione, esigenze, fonti, stato_verifica) values ($t$Euonymus planipes$t$, $t$Euonymus planipes$t$, $t$euonymus-planipes$t$, $t$perenne$t$, $t$Alto anche 4 m, foglie lunghe 7-13 cm, fiori verdi in racemi penduli, frutti angolosi rosso scuro con semi rossi; in inverno produce sottili germogli terminali rossi.$t$, $t${"luce": "Pieno sole / Mezz'ombra / Ombra"}$t$::jsonb, ARRAY[$t$Il giardino di arbusti (Edicart, 1995) — Euonymus planipes$t$]::text[], $t$bozza$t$) on conflict (slug) do nothing;
