-- Fase 3 (#120), primo blocco (20/90 specie usate da piante reali): bozza di
-- ciclo_colturale e vaso da conoscenza botanica generale, non ancora verificata
-- su fonti reali (task di verifica separato). stato_verifica resta 'bozza'
-- di default, non lo cambio qui.
--
-- 8 specie (zinnia, basilico, prezzemolo, pomodoro, zucca, zucchina,
-- melanzana, scalogno) avevano già ciclo_colturale dalla fonte originale:
-- qui aggiungo solo vaso. Le altre 12 sono compilate da zero.

update specie set vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$zinnia$t$;
update specie set vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$basilico$t$;
update specie set vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$prezzemolo$t$;
update specie set vaso = $j${"adatta": true, "dimensione_minima_litri": 20, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.6}$j$::jsonb where slug = $t$pomodoro$t$;
update specie set vaso = $j${"adatta": true, "dimensione_minima_litri": 40, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.6}$j$::jsonb where slug = $t$zucca$t$;
update specie set vaso = $j${"adatta": true, "dimensione_minima_litri": 30, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.6}$j$::jsonb where slug = $t$zucchina$t$;
update specie set vaso = $j${"adatta": true, "dimensione_minima_litri": 20, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.6}$j$::jsonb where slug = $t$melanzana$t$;
update specie set vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$scalogno$t$;
update specie set ciclo_vitale = $t$annuale$t$, ciclo_colturale = $j${"famiglia_botanica": "Cucurbitaceae", "giorni_germinazione": "6-10", "giorni_trapianto": "20-30", "giorni_raccolta": "50-70", "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera", "estate"], "resistenza_gelo": "nessuna", "spaziatura_cm": 40, "consociazioni_favorevoli": ["fagiolo", "mais", "girasole"], "consociazioni_sfavorevoli": ["patata"]}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 15, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$cetriolo$t$;
update specie set ciclo_vitale = $t$annuale$t$, ciclo_colturale = $j${"famiglia_botanica": "Solanaceae", "giorni_germinazione": "10-20", "giorni_trapianto": "45-60", "giorni_raccolta": "70-90", "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 40, "consociazioni_favorevoli": ["basilico", "carota"], "consociazioni_sfavorevoli": ["fagiolo", "finocchio"]}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 10, "rinvaso_ogni_mesi": 12, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$peperoncino$t$;
update specie set ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Lamiaceae", "giorni_germinazione": "14-21", "giorni_trapianto": "30-40", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 25, "consociazioni_favorevoli": ["cavolo", "pomodoro"], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.6}$j$::jsonb where slug = $t$timo-serpillo$t$;
update specie set ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Amaryllidaceae", "giorni_germinazione": "14-20", "giorni_trapianto": "40-50", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 20, "consociazioni_favorevoli": ["carota", "pomodoro"], "consociazioni_sfavorevoli": ["fagiolo", "pisello"]}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 12, "irrigazione_fattore": 0.9}$j$::jsonb where slug = $t$erba-cipollina$t$;
update specie set ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Lamiaceae", "giorni_germinazione": "14-21", "giorni_trapianto": "40-60", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "media", "spaziatura_cm": 40, "consociazioni_favorevoli": ["rosmarino", "cavolo"], "consociazioni_sfavorevoli": ["cetriolo"]}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.6}$j$::jsonb where slug = $t$salvia$t$;
update specie set ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Lauraceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "media", "spaziatura_cm": 100, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 20, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$alloro$t$;
update specie set ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Rosaceae", "giorni_germinazione": "14-21", "giorni_trapianto": "30-40", "giorni_raccolta": "60-90", "finestra_semina": ["inverno", "primavera"], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "media", "spaziatura_cm": 30, "consociazioni_favorevoli": ["aglio", "lattuga", "spinacio"], "consociazioni_sfavorevoli": ["cavolo"]}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 12, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$fragola-rifiorente$t$;
update specie set ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Ranunculaceae", "giorni_germinazione": "20-30", "giorni_trapianto": "60-90", "giorni_raccolta": null, "finestra_semina": ["primavera", "estate"], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.9}$j$::jsonb where slug = $t$aquilegia$t$;
update specie set ciclo_vitale = $t$annuale$t$, ciclo_colturale = $j${"famiglia_botanica": "Brassicaceae", "giorni_germinazione": "7-14", "giorni_trapianto": "20-30", "giorni_raccolta": null, "finestra_semina": ["primavera", "autunno"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "media", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$alisso$t$;
update specie set ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Geraniaceae", "giorni_germinazione": "7-14", "giorni_trapianto": "40-50", "giorni_raccolta": null, "finestra_semina": ["inverno", "primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 12, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$geranio-zonale$t$;
update specie set ciclo_vitale = $t$annuale$t$, ciclo_colturale = $j${"famiglia_botanica": "Asteraceae", "giorni_germinazione": "7-14", "giorni_trapianto": "20-30", "giorni_raccolta": null, "finestra_semina": ["primavera", "autunno"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "media", "spaziatura_cm": 25, "consociazioni_favorevoli": ["pomodoro", "cavolo"], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$calendula$t$;
update specie set ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Caryophyllaceae", "giorni_germinazione": "14-21", "giorni_trapianto": "45-60", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "media", "spaziatura_cm": 25, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$garofano$t$;
