-- Naturalizzazione della descrizione delle 74 specie effettivamente possedute
-- dall'utente che ricadono nel blocco RHS marcato (punto 4 del piano, issue #153).
-- Riscrittura in prosa narrativa italiana: traduzione del blocco RHS in inglese +
-- naturalizzazione dello stile, seguendo la skill naturalizza-descrizioni
-- (famiglia citata in modo naturale, rusticita' RHS convertita in temperature,
-- niente elenchi di cultivar ne' nomi comuni, nessuna invenzione).
--
-- Verifica fattuale indipendente (subagent Haiku) + revisione manuale + revisione
-- utente. fonti e stato_verifica restano invariati (intervento di stile).
-- descrizione_originale (migration 20260901010000) conserva gia' il testo pre-strip
-- di tutte e 74 le righe: l'operazione e' reversibile per riga.
--
-- Guardia "descrizione ilike '%testo originale in inglese%'": la migration e'
-- idempotente (una riga gia' riscritta non fa piu' match).

begin;

update public.specie set descrizione = $rewr$Succulenta della famiglia delle Crassulaceae dal portamento arbustivo, con fusti legnosi radi che portano all'apice rosette di foglie carnose e spatolate, lucide; in Aeonium arboreum la pianta arriva a circa 1,5 m e produce ampie pannocchie coniche di piccoli fiori gialli stellati. Il ciclo è invertito rispetto a molte altre succulente: vegeta in autunno, inverno e primavera e va in semi-riposo durante la calura estiva, quando la perdita di qualche foglia basale è normale. Teme il gelo intenso e prolungato e va tenuta al riparo sotto i 5 °C circa; vuole pieno sole, poca acqua e un substrato molto drenante. Si moltiplica con facilità per talea di fusto o di rosetta.$rewr$
 where slug = 'aeonium' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Perenne cespitosa della famiglia delle Amaryllidaceae, con radici carnose e foglie nastriformi, sempreverdi in alcune specie, da cui in estate si alzano scapi rigidi che portano ombrelle di fiori imbutiformi blu o bianchi. Vuole pieno sole e un terreno fertile ma ben drenato, e fiorisce meglio quando le radici sono un po' costrette nel vaso. La rusticità varia molto con la specie: si va da forme poco resistenti, da proteggere sotto i -5 °C, ad altre che tollerano inverni rigidi fino a circa -20 °C; nelle zone con inverni più freddi conviene pacciamare la base. Sopporta bene la siccità estiva una volta radicata.$rewr$
 where slug = 'agapanto' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Lobularia maritima è una pianta bassa e compatta della famiglia delle Brassicaceae, annuale o perenne di breve durata, che forma cuscini tappezzanti coperti per tutta l'estate da minuti fiori bianchi profumati di miele, riuniti in corimbi arrotondati e molto visitati dagli insetti impollinatori. Cresce al sole in terreno drenato anche non ricco, e teme soprattutto i ristagni idrici. È poco resistente al freddo, con danni già intorno a -5 °C. Una leggera cimatura dopo la prima ondata di fioritura ne stimola una seconda.$rewr$
 where slug = 'alisso' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Bulbosa ornamentale della famiglia delle Amaryllidaceae, con un ciuffo di foglie basali strette lunghe fino a 30 cm e scapi lungamente peduncolati che in piena estate portano capolini densi e ovoidali, dapprima verdastri poi virati al rosa-porpora carico, da cui il nome comune legato alla forma "a testa di tamburo". Chiede terreno drenante e posizione soleggiata, e va tenuta all'asciutto durante il riposo estivo del bulbo. È molto rustica, oltre i -15 °C, e si naturalizza con facilità, riseminandosi e moltiplicandosi per bulbilli fino a formare colonie durature.$rewr$
 where slug = 'allium-sphaerocephalon' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Laurus nobilis è un grande arbusto eretto, spesso allevato ad alberello, della famiglia delle Lauraceae. Ha foglie sempreverdi coriacee e lucide, strettamente ovate, lunghe fino a 10 cm e larghe 2-4 cm, aromatiche: fresche o essiccate sono un condimento diffuso in cucina. I fiori sono minuti (circa 5 mm), giallo-verde pallido, riuniti in mazzetti densi; i frutti sono bacche ovali di circa 1,5 cm, nere e lucide a maturità. È rustico fino a circa -10 °C, resiste bene a vento e sole pieno ed è molto tollerante alla siccità; nelle estati più calde può essere attaccato dalla cocciniglia. La crescita è vigorosa e conviene controllare polloni ed espansione.$rewr$
 where slug = 'alloro' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Anthurium andraeanum è una perenne sempreverde tropicale della famiglia delle Araceae, alta fino a circa 60 cm, con foglie verde scuro a base sagittata lunghe fino a 30 cm e vistose spate cuoriformi rosso vivo attraversate da uno spadice giallo chiaro, prodotte in ogni periodo dell'anno. In natura il genere è per lo più epifita, a volte rampicante. Si coltiva solo in appartamento o in serra calda, con minime sopra i 15 °C: vuole luce diffusa mai diretta, alta umidità ambientale, acqua non calcarea e nessun ristagno, che favorirebbe i marciumi radicali.$rewr$
 where slug = 'anthurium' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Aquilegia vulgaris è una perenne erbacea cespitosa della famiglia delle Ranunculaceae, con foglie basali lungamente picciolate e divise in segmenti, e steli eretti e ramificati che in primavera portano fiori penduli e campanulati, dai sepali e petali colorati prolungati in speroni. La forma selvatica è di norma blu, ma la lunga storia in coltivazione ha prodotto varianti viola, malva, rosa e bianche. Vuole mezz'ombra fresca e terreno fertile e drenato, si risemina con facilità ed è molto rustica, ampiamente sotto lo zero.$rewr$
 where slug = 'aquilegia' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Citrus sinensis è un agrume sempreverde della famiglia delle Rutaceae, spesso spinoso, con foglie coriacee e aromatiche dal picciolo alato e fiori bianchi profumati seguiti da grandi frutti succosi; nelle selezioni del gruppo Navel il frutto è senza semi e reca all'apice un piccolo frutto secondario. Vuole pieno sole, terreno ricco e drenato e irrigazione regolare senza ristagni. È sensibile al freddo e va protetto quando la temperatura scende sotto lo zero; nelle estati calde va tenuta d'occhio la cocciniglia.$rewr$
 where slug = 'arancio-navel' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Ocimum basilicum è un'aromatica tenera della famiglia delle Lamiaceae, coltivata come annuale, alta 30-60 cm, con foglie ellittiche verde brillante lunghe circa 5 cm e piccoli fiori tubulari bianchi o sfumati di rosa riuniti in spighe terminali a fine estate. Le cultivar disponibili sono moltissime, diverse per taglia e colore del fogliame. Vuole sole, terreno fertile e ben drenato e annaffiature regolari senza ristagni nel sottovaso; soffre freddo e vento, e con poca luce fila. Cimare le infiorescenze appena compaiono mantiene la produzione di foglie.$rewr$
 where slug = 'basilico' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Perenne sempreverde della famiglia delle Asteraceae, forma rosette compatte di foglie spatolate verde scuro da cui, tra tarda primavera ed estate, spuntano piccoli capolini solitari a margherita: petali bianchi sfumati di rosa attorno a un centro giallo. Adatta a bordure e tappeti fioriti, vuole terreno fresco, sole o mezz'ombra e buona luce per fiorire in abbondanza. È molto rustica, ben sotto lo zero, e tende ad autoriseminarsi; rimuovere i fiori appassiti prolunga di molto la fioritura.$rewr$
 where slug = 'bellis-perennis' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Euphorbia trigona, qui nella forma mostruosa, è un arbusto succulento architettonico della famiglia delle Euphorbiaceae, a crescita lenta, con fusti eretti a tre o quattro coste alti fino a circa 1,8 m. Lungo le costolature porta spine bruno-rossastre persistenti e piccole foglie ovali effimere, mentre i lati mostrano bande grigio-verdi a forma di V. I fiori, verdolini e insignificanti, compaiono in primavera-estate all'apice dei fusti ma difficilmente in coltivazione domestica. Il lattice è irritante e va maneggiato con cautela. Vuole molta luce, substrato sabbioso e niente ristagni; non tollera il gelo e va portato al riparo quando la temperatura scende sotto i 5 °C.$rewr$
 where slug = 'cactus-ago-di-eva-monstroso' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Pianta della famiglia delle Marantaceae (le specie oggi ricadono in gran parte nel genere Goeppertia), perenne sempreverde rizomatosa che forma cespi di foglie ellittiche, spesso vistosamente marezzate e disegnate: è per il fogliame che si coltiva, dato che le spighe di fiori compaiono di rado in appartamento. Richiede ambiente caldo, sopra i 15 °C, umidità elevata, luce filtrata mai diretta e acqua non calcarea, che altrimenti macchia le foglie; teme correnti e sbalzi termici.$rewr$
 where slug = 'calathea' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Pianta della famiglia delle Solanaceae, in origine perenne a base legnosa ma tenera, coltivata come annuale, dal portamento per lo più ricadente, con foglie semplici e piccoli fiori imbutiformi simili a quelli della petunia, prodotti senza sosta da primavera ad autunno. È ideale per fioriere e vasi sospesi, dove però il substrato si asciuga più in fretta. Vuole sole pieno per fiorire bene e teme i ristagni; è sensibile al gelo, con danni sotto i -5 °C circa.$rewr$
 where slug = 'calibrachoa' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Camellia japonica è un arbusto sempreverde della famiglia delle Theaceae, da eretto a espanso e ramificato, che può raggiungere i 10 m. Le foglie sono verde scuro e lucide, da ovali a ovate, lunghe 7-10 cm; i fiori, solitari, bianchi o rosa, larghi 6-10 cm, sbocciano all'estremità dei rametti tra fine inverno e primavera. È acidofila e non tollera i terreni calcarei: va usato terriccio specifico ed evitati gli ammendanti che alzano il pH. Rustica fino a circa -10/-15 °C, soffre il sole diretto del primo pomeriggio estivo, mentre il sole del primo mattino dopo notti fredde può scottare i boccioli per disgelo troppo rapido. Non va potata sul legno vecchio poco prima della fioritura.$rewr$
 where slug = 'camelia' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Carex oshimensis è una perenne sempreverde della famiglia delle Cyperaceae, durevole e densamente cespitosa, alta 30-40 cm, con fogliame lucido a texture fine e brune spighe fiorali poco appariscenti, nascoste tra le foglie, a metà e tarda primavera. Il genere comprende specie decidue o sempreverdi, cespitose o rizomatose, con fusti a sezione triangolare. Vuole terreno fresco e drenato ed è molto rustica, ben sotto lo zero; la crescita è lenta ma ordinata, e la pianta si presta bene come elemento strutturale.$rewr$
 where slug = 'carex' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Perenne della famiglia delle Asteraceae originaria delle scogliere costiere della Dalmazia, molto ornamentale per il fogliame bianco-argento; i capolini, simili a quelli dei cardi, hanno fioretti esterni ingranditi. Vuole pieno sole e terreno sabbioso o ghiaioso, drenante anche se povero, e teme i ristagni prolungati, mentre resiste bene alla siccità e alla salsedine una volta radicata. Esiste anche la cultivar 'Balcentsirl' (Silver Swirl), a fogliame più compatto e ondulato ai margini e con rusticità superiore rispetto alla specie.$rewr$
 where slug = 'centaurea-ragusina' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Ceropegia woodii è una succulenta perenne della famiglia delle Apocynaceae, da eretta a ricadente, con fusti sottili e filiformi e foglioline opposte cuoriformi, marmorizzate d'argento sulla pagina superiore. In estate produce fiori dalla forma curiosa, a volte seguiti da frutti cilindrici con semi dal ciuffo serico. Coltivata in vaso sospeso per i lunghi tralci pendenti, vuole luce intensa ma indiretta per mantenere la variegatura e pochissima acqua: i ristagni, soprattutto in inverno, provocano marciume alla base.$rewr$
 where slug = 'ceropegia' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Cucumis sativus è la specie da cui derivano tutte le cultivar coltivate, una pianta annuale della famiglia delle Cucurbitaceae, rampicante o strisciante fino a circa 2 m, che si aggrappa con viticci sottili all'ascella delle foglie. Porta fiori gialli maschili e femminili separati sulla stessa pianta; dopo l'impollinazione i fiori femminili danno il frutto cilindrico verde scuro, lungo fino a 40 cm. Vuole pieno sole, terreno fertile e ricco di sostanza organica e acqua abbondante e regolare: in carenza idrica i frutti diventano amari o deformi. È molto sensibile al freddo, con sofferenze già sotto i 10 °C.$rewr$
 where slug = 'cetriolo' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Rampicante decidua vigorosa della famiglia delle Ranunculaceae, capace di raggiungere 7-12 m se non contenuta. In tarda primavera si copre di piccoli fiori singoli bianchi; le foglie, all'apertura, hanno spesso una sfumatura bronzo o porpora prima di virare al verde. Fiorisce sui rami dell'anno precedente. Ama avere il piede all'ombra e la chioma al sole, con terreno fertile e drenato; è rustica fino a circa -15/-10 °C. Può essere colpita dall'avvizzimento del clematide, una malattia specifica potenzialmente grave.$rewr$
 where slug = 'clematis-montana' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Coreopsis grandiflora è una perenne rustica della famiglia delle Asteraceae, cespugliosa, con foglie lanceolate allungate leggermente pelose e capolini a margherita giallo dorato dal centro più scuro, portati su steli lunghi e sottili per un lungo periodo estivo. La pianta coltivata qui è a fioritura doppia, del tipo 'Sunray' o 'Early Sunrise': i petali numerosi ed embricati formano una testa densa e arrotondata a palla anziché la classica margherita piatta. Resiste bene alla siccità una volta radicata, teme i ristagni ed è molto rustica; rimuovere i fiori appassiti prolunga la fioritura.$rewr$
 where slug = 'coreopsis' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Cuphea hyssopifolia è una pianta arbustiva compatta e sempreverde della famiglia delle Lythraceae, spesso rivestita di peli vischiosi, con foglie opposte semplici e piccoli fiori tubulari numerosissimi dal calice vistoso. Il genere comprende anche annuali e perenni. Vuole sole o mezz'ombra luminosa e terreno drenato, e teme i ristagni; è poco resistente al freddo e va riparata già sotto i 5 °C.$rewr$
 where slug = 'cuphea' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Delosperma cooperi è una succulenta tappezzante della famiglia delle Aizoaceae, originaria del Sudafrica, con fusti radicanti e foglie cilindriche verde chiaro lunghe fino a 5 cm; da metà a fine estate produce fiori a margherita rosa-porpora intenso larghi fino a 5 cm. È adatta a bordure, muretti e scarpate, e teme i ristagni idrici più del freddo: è infatti più resistente al gelo di molte succulente, tollerando qualche grado sotto lo zero, indicativamente fino a circa -10 °C. Vuole pieno sole e substrato sabbioso molto drenante.$rewr$
 where slug = 'delosperma' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Le Echeveria sono perenni succulente sempreverdi, o piccoli suffrutici, della famiglia delle Crassulaceae, che formano rosette di foglie carnose spesso vivacemente colorate, sopra le quali si alzano racemi o pannocchie di fiori urceolati. Servono molta luce per mantenere la rosetta compatta: quando la pianta si allunga verso l'alto è segno di illuminazione insufficiente. Il substrato deve essere molto drenante e le annaffiature scarse; foglie molli indicano eccesso d'acqua, foglie raggrinzite sete. Al di sotto di 1-5 °C vanno riparate dal freddo.$rewr$
 where slug = 'echeveria' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Echinacea purpurea è una perenne eretta e rizomatosa della famiglia delle Asteraceae, cespitosa, alta fino a circa 1,5 m, con foglie basali lanceolate e ispide lunghe fino a 15 cm. Da metà estate all'autunno porta capolini solitari larghi fino a 12 cm, con ligule rosa-porpora chiaro leggermente ricurve all'indietro attorno a un disco centrale conico bruno-dorato. È originaria delle praterie e dei boschi degli Stati Uniti orientali, molto rustica e attraente per le farfalle; vuole sole o mezz'ombra e terreno fertile e drenato, e teme i ristagni.$rewr$
 where slug = 'echinacea' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Allium schoenoprasum è una piccola perenne bulbosa aromatica della famiglia delle Amaryllidaceae, che forma un cespo di foglie erette, cilindriche e cave, lunghe fino a 30 cm, dall'odore di cipolla. Sopra il fogliame porta ombrelle arrotondate di fioretti campanulati viola chiaro; foglie e fiori sono entrambi commestibili, e i fiori sono ricchi di nettare per api e altri impollinatori. È molto rustica, ben oltre i -15 °C, si autosemina con facilità e può diventare infestante se non gestita. Raccogliere spesso le foglie stimola nuova crescita.$rewr$
 where slug = 'erba-cipollina' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Erica carnea è un arbusto sempreverde nano ed espanso della famiglia delle Ericaceae, con foglioline strette e aghiformi verde scuro. Tra fine inverno e inizio primavera produce spighe unilaterali lunghe circa 8 cm di piccoli fiori urceolati rosa, rosa-porpora, magenta o bianchi. A differenza della maggior parte delle eriche, questa specie tollera bene il calcare. È molto rustica, ampiamente sotto lo zero; richiede terreno drenante e teme i ristagni, che favoriscono i marciumi radicali, in particolare da Phytophthora. Non va potata sul legno vecchio, perché non ributta.$rewr$
 where slug = 'erica' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Trachelospermum jasminoides è una rampicante legnosa sempreverde della famiglia delle Apocynaceae, vigorosa, alta fino a circa 9 m, con fusti volubili e foglie ovali verde scuro lucide lunghe fino a 10 cm, che spesso virano al bronzo-rosso in inverno. Tra la tarda primavera e la fine dell'estate porta mazzetti di fiori bianchi stellati larghi circa 2,5 cm, molto profumati. Ha bisogno di un supporto su cui arrampicarsi; è rustica indicativamente fino a -10 °C, meglio se in posizione riparata, e teme le correnti fredde e i ristagni.$rewr$
 where slug = 'falso-gelsomino' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$I Ferocactus sono cactus della famiglia delle Cactaceae, da sferici a colonnari, con coste prominenti percorse da areole spinose; le spine, robuste e ben visibili, sono a volte uncinate. In estate produce fiori imbutiformi. La crescita è lenta. Vuole molta luce diretta, substrato sabbioso con ghiaia e nessun ristagno idrico; le spine vanno maneggiate con attenzione.$rewr$
 where slug = 'ferocactus' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Carpobrotus edulis è una succulenta sempreverde tappezzante della famiglia delle Aizoaceae, molto vigorosa, con fusti striscianti e radicanti capaci di estendersi per 3 m o più. Le foglie carnose e ricurve, lunghe fino a 15 cm, hanno sezione triangolare; i fiori, larghi fino a 15 cm, sono gialli e sfumano al rosa, e possono dare frutti carnosi gialli. È una specie ufficialmente riconosciuta come invasiva: nel Regno Unito è reato piantarla in natura, e anche sulle coste mediterranee, Italia compresa, compete con la vegetazione dunale nativa. Va quindi tenuta sotto controllo e mai lasciata sfuggire in aree naturali. Tollera brevi gelate leggere, fino a circa -5 °C.$rewr$
 where slug = 'fico-di-mare' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Ficus microcarpa è un albero della famiglia delle Moraceae che nei climi caldi diventa grande e sviluppa abbondanti radici aeree, mentre in vaso resta un arbusto sempreverde cespuglioso alto fino a circa 4 m, con foglie ovate verde scuro lucide. È diffuso come bonsai da appartamento per la base ingrossata. Va coltivato in casa, con minime sopra i 10-15 °C, luce intensa ma indiretta e nessun ristagno idrico; è sensibile agli sbalzi di temperatura e alle correnti.$rewr$
 where slug = 'ficus-ginseng' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Le Gasteria sono succulente perenni acauli della famiglia delle Asphodelaceae, che formano cespi di rosette di foglie carnose, spesso disposte su due file opposte e maculate di punti chiari su fondo scuro. I fiori, penduli e tubulari, sono portati in racemi. A differenza di molte altre succulente tollera bene la luce indiretta e va anzi riparata dal sole diretto nelle ore più calde, che scotta le foglie; la colorazione bronzo-porpora sotto luce forte o freddo è normale. Vuole substrato molto drenante e non è rustica: va protetta dalle gelate, con minime intorno a 1-5 °C.$rewr$
 where slug = 'gasteria' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Pelargonium peltatum è una perenne sempreverde della famiglia delle Geraniaceae, cespugliosa e dal portamento ricadente, con foglie carnose verde chiaro a lobi appuntiti, simili a quelle dell'edera, e fiori singoli rosa. È tra le piante più usate in fioriere e balconiere per la lunghissima fioritura. Vuole sole, terreno fertile e drenato e nessun ristagno; è sensibile al gelo e va protetta con minime intorno a 1-5 °C.$rewr$
 where slug = 'geranio-parigino' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Pelargonium zonale, della famiglia delle Geraniaceae, è il capostipite della maggior parte dei pelargoni zonali: una pianta eretta e cespugliosa, con fusti carnosi che lignificano con l'età e foglie tondeggianti verde medio segnate da una fascia più scura. Cresce di norma fino a circa 1 m, ma può arrivare a 3 m addossata a un muro in serra. I mazzetti di fiori a petali stretti, rosa, bianchi o porpora, compaiono quasi tutto l'anno in clima caldo e luminoso, altrimenti in estate e inizio autunno. È sensibile al gelo, da proteggere sotto i 5 °C; vuole sole e terreno drenato.$rewr$
 where slug = 'geranio-zonale' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Gerbera jamesonii è una perenne sempreverde cespitosa della famiglia delle Asteraceae, a rosetta basale senza fusto legnoso: le foglie, profondamente lobate, verde scuro e con pagina inferiore lanosa, arrivano a 45 cm e nascono direttamente dalla base, come gli scapi fiorali. Ogni scapo eretto porta un solo capolino a margherita largo fino a 12 cm, nei toni del rosso, arancio, rosa o giallo con centro giallo, da tarda primavera a fine estate. È poco rustica e va protetta dal gelo, con minime indicativamente tra -5 e 1 °C; teme i ristagni al colletto. Uno scapo corto e ripiegato indica poca luce o una rosetta troppo fitta.$rewr$
 where slug = 'gerbera' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Perenne sempreverde tappezzante della famiglia delle Lamiaceae, vigorosa e aromatica, che si diffonde con stoloni prostrati e radicanti; i fusti fioriferi, sub-eretti, arrivano a circa 10 cm e portano fiori di norma blu-violetto, ma esistono anche forme rosa e bianche. Copre bene il suolo limitando le infestanti, ma la crescita è molto rapida e la pianta può diventare invasiva, espandendosi oltre l'area desiderata. Preferisce mezz'ombra o sole del mattino e terreno fresco e drenato; è molto rustica, oltre i -15 °C.$rewr$
 where slug = 'glechoma-hederacea' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Le Heuchera sono perenni più o meno sempreverdi della famiglia delle Saxifragaceae, cespitose, con foglie arrotondate e superficialmente lobate, spesso vivacemente colorate, e racemi o pannocchie di piccoli fiori tubulari dai calici a volte colorati. Il fogliame resta decorativo tutto l'anno. Preferiscono mezz'ombra luminosa e terreno ricco e drenato, temono il caldo eccessivo e i ristagni, e sono rustiche ben sotto lo zero.$rewr$
 where slug = 'heuchera' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Suffrutice sempreverde della famiglia delle Brassicaceae, dal portamento espanso a cuscino, alto fino a circa 30 cm, con foglie strette verde scuro. Da tarda primavera si copre di fiori bianco puro riuniti in capolini densi larghi fino a 4 cm, dapprima appiattiti e poi arrotondati. Adatto a muretti, bordure e aiuole rocciose, cresce lentamente ma in modo molto compatto; teme i ristagni più del caldo e può diventare invadente se non contenuto. È molto rustico, ben oltre i -15 °C.$rewr$
 where slug = 'iberis-sempervirens' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Hypoestes phyllostachya appartiene alla famiglia delle Acanthaceae ed è una perenne sempreverde tenera, a volte suffrutice, con foglie semplici vistosamente maculate e colorate; a volte produce fioretti tubulari bilabiati, ma si coltiva soprattutto per il fogliame. Va tenuta in casa, con minime sopra i 10-15 °C, e ha bisogno di luce intensa ma indiretta per mantenere la variegatura: se si allunga troppo è segno di luce insufficiente. Vuole terreno ricco e nessun ristagno.$rewr$
 where slug = 'ipoeste' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Dracaena sanderiana è un arbusto snello ed eretto della famiglia delle Asparagaceae, con fusti simili a canne e foglie verde lucido striate longitudinalmente di bianco; nonostante il nome comune non è un vero bambù e non produce germogli commestibili. È una pianta da interno molto facile, che si alleva sia in terra sia in acqua: in acqua è più semplice da far crescere, in terra è meno scenografica ma più rigogliosa e fogliosa. Va tenuta al chiuso, con minime sopra i 10-15 °C, molta luce non diretta e acqua da rinnovare ogni una o due settimane; il cloro dell'acqua di rubinetto può danneggiarla.$rewr$
 where slug = 'lucky-bamboo' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Le Mammillaria sono cactus spinosi della famiglia delle Cactaceae, con fusti sferici o colonnari spesso riuniti in gruppi, coperti da numerosi tubercoli prominenti. I fiori, imbutiformi, si dispongono di norma in un anello attorno all'apice del fusto. Sono cactus resistenti e facili da coltivare, che chiedono molta luce, substrato drenante e nessun ristagno idrico; una base che diventa giallo-bruna con l'età è normale lignificazione.$rewr$
 where slug = 'mammillaria' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Mammillaria elongata è un cactus della famiglia delle Cactaceae dai fusti cilindrici riuniti in gruppi, alti fino a circa 15 cm, con spine da giallo-crema a brune e piccoli fiori (circa 1,5 cm) giallo pallido o sfumati di rosa. Vuole luce intensa per mantenere la forma compatta e un inverno non più freddo di 1-5 °C, perché non regge il gelo; i ristagni idrici sono da evitare in modo assoluto.$rewr$
 where slug = 'mammillaria-allungata' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Mammillaria plumosa è un cactus cespitoso della famiglia delle Cactaceae che forma un cuscino di fusti globosi larghi fino a circa 6 cm, interamente nascosti da fitte spine radiali bianche e piumose che gli danno un aspetto morbido; è delicata al tatto e va maneggiata con cura. A fine estate produce fioretti di circa 1,5 cm, bianco-crema o rosa smorto. È molto sensibile ai ristagni e la lanugine non va bagnata dall'alto, perché trattiene umidità; la crescita è lenta. Va svernata al riparo dal gelo, con minime intorno a 1-5 °C.$rewr$
 where slug = 'mammillaria-piumosa' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Citrus japonica è un grande arbusto sempreverde spinoso della famiglia delle Rutaceae, a portamento compatto, con foglie lanceolate lucide. In primavera ed estate porta mazzetti ascellari di fiori bianchi profumati larghi circa 1,2 cm, seguiti da piccoli frutti arancioni globosi di 3-4 cm, dalla buccia dolce che si mangia insieme alla polpa. È più rustico degli altri agrumi, ma va comunque protetto sotto i -5/-6 °C. Vuole pieno sole, terreno ricco e drenato e nessun ristagno.$rewr$
 where slug = 'mandarino-cinese' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Argyranthemum frutescens è un suffrutice arrotondato e variabile della famiglia delle Asteraceae, di origine mediterranea, con foglie verde brillante grossolanamente incise e abbondanti capolini a margherita bianchi, larghi circa 2 cm, dal disco giallo, prodotti per un lungo periodo. Vuole sole e terreno drenato di media fertilità, teme i ristagni ed è poco rustica, da proteggere dal gelo con minime intorno a 1-5 °C.$rewr$
 where slug = 'margherita-delle-canarie' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Marsilea quadrifolia è una felce acquatica della famiglia delle Marsileaceae: una perenne erbacea espansa, coltivata di norma in acqua bassa, con foglie verde scuro larghe 2-3 cm formate da quattro segmenti triangolari, che le danno l'aspetto di un quadrifoglio. Si diffonde rapidamente per rizomi e teme la siccità: le foglie si afflosciano quando il terreno si asciuga. È rustica, indicativamente fino a circa -15 °C, e in inverno può ridurre la parte aerea per poi ricacciare in primavera. È adatta a bordi di laghetto e terreni costantemente umidi.$rewr$
 where slug = 'marsilea-quadrifolia' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Solanum melongena è la specie selvatica da cui è stato selezionato l'ortaggio coltivato, della famiglia delle Solanaceae. In natura è perenne, ma alle nostre latitudini si coltiva come annuale perché non rustica; ha foglie verdi, fusto leggermente spinoso e fiori viola che si sviluppano in piccoli frutti viola ovoidali. Le varietà disponibili variano molto per taglia, forma e colore. Vuole pieno sole, terreno fertile e drenato e clima caldo: la crescita rallenta già sotto i 15 °C. Le varietà a frutto grosso hanno bisogno di un tutore.$rewr$
 where slug = 'melanzana' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Le Phalaenopsis sono orchidee epifite sempreverdi tropicali della famiglia delle Orchidaceae, tra le piante da appartamento più diffuse; sono originarie delle foreste del Sud-est asiatico, dove vivono sugli alberi lungo i grandi fiumi. Portano da sei a dieci foglie carnose, ovali o ellittiche, disposte alternativamente attorno a un fusto corto interamente rivestito dalle basi fogliari embricate. Gli steli fiorali, eretti, arcuati o semi-penduli, emergono sotto le foglie più vecchie e reggono fiori di lunga durata, variabili per numero e dimensione secondo la cultivar. Il nome, dal greco "che sembra una falena", fu coniato nel 1825 dal botanico Carl Ludwig Blume dopo la scoperta della pianta nel Borneo. Va coltivata in casa, con minime sopra i 15 °C, in substrato di corteccia, con luce diffusa e senza far ristagnare acqua al centro della rosetta, per prevenire i marciumi batterici.$rewr$
 where slug = 'orchidea' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Pianta mediterranea della famiglia delle Asteraceae, oggi classificata da alcune fonti come Dimorphotheca ecklonis: può essere perenne, annuale o suffrutice, con foglie sempreverdi aromatiche, semplici o lobate, e vistosi capolini a margherita prodotti per un lungo periodo a partire da tarda primavera. I fiori si chiudono all'ombra e la pianta dà il meglio in pieno sole, su terreno molto drenato e leggero. È poco rustica e va protetta dal gelo, con minime indicativamente tra -5 e 1 °C.$rewr$
 where slug = 'osteospermum' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Rampicante sempreverde grande e vigorosa della famiglia delle Passifloraceae, alta fino a circa 10 m, con foglie verdi lunghe fino a 10 cm divise in 5-7 lobi digitati. Dall'estate all'autunno produce fiori a coppa larghi fino a 8 cm, bianchi con i filamenti della corona blu e porpora, seguiti da frutti ovoidali arancioni lunghi 4 cm: sono commestibili ma poco gustosi, a differenza di quelli della Passiflora edulis. Richiede un supporto robusto per la crescita rapida e può diventare invadente. È rustica fino a circa -5/-7 °C nella parte aerea, che poi spesso ricaccia dalla base.$rewr$
 where slug = 'passiflora-caerulea' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Pennisetum alopecuroides è una graminacea ornamentale della famiglia delle Poaceae, che forma un cespo denso di foglie strette lunghe fino a 60 cm, brune in inverno. A fine estate e inizio autunno steli alti portano infiorescenze oblunghe, morbidamente pelose, da verdi a porpora, molto decorative. Vuole pieno sole e terreno drenato di media fertilità; in ombra fitta produce poche spighe. È abbastanza rustica, indicativamente fino a -10/-15 °C, e va tagliata a fine inverno, prima della nuova crescita.$rewr$
 where slug = 'pennisetum-cinese' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Pilea peperomioides è una perenne sempreverde eretta della famiglia delle Urticaceae, alta fino a 30 cm o poco più, con foglie carnose, tonde e piatte, lungamente picciolate, verde medio, larghe fino a 10 cm, da cui il nome comune legato alla forma a moneta. I fioretti, minuti e verde pallido, sono a volte sfumati di rosa. È facilissima da propagare grazie ai numerosi polloni che emette alla base. Va coltivata in casa, con minime sopra i 5-10 °C, luce luminosa ma indiretta e buona umidità ambientale; il fusto tende a lignificare alla base con l'età.$rewr$
 where slug = 'pianta-delle-monete' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Plumbago auriculata è un arbusto sempreverde della famiglia delle Plumbaginaceae che, con un supporto, raggiunge i 4 m o più; ha fusti sottili e scandenti, foglie verde chiaro spatolate e racemi terminali di fiori azzurro cielo a tubo lungo, larghi circa 15 mm. Fiorisce senza sosta da giugno a ottobre. Teme il gelo, con minime intorno a 1-5 °C: sotto i -5 °C la parte aerea secca, ma la pianta ricaccia dalla base. Vuole pieno sole, terreno fertile e drenato e un contenimento regolare del portamento vigoroso.$rewr$
 where slug = 'plumbago' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Solanum lycopersicum è la pianta originaria da cui derivano tutte le varietà di pomodoro, della famiglia delle Solanaceae. Nel suo habitat tropicale è un suffrutice perenne, grande, ramificato e rampicante fino a 2 m, con fusti e foglie coperti di peli corti. I fiori gialli stellati, larghi 1-2 cm, danno bacche verdi che maturano in frutti di taglia, forma e colore variabili secondo la cultivar. Alle nostre latitudini si coltiva come annuale: teme il freddo e vuole pieno sole, terreno fertile e drenato e acqua regolare e abbondante, senza ristagni. Ha bisogno di sostegni, soprattutto nelle varietà a crescita indeterminata, e va sfemminellato per favorire la fruttificazione.$rewr$
 where slug = 'pomodoro' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Epipremnum aureum è una rampicante sempreverde autoaggrappante della famiglia delle Araceae, con fusti sottili che, se non potati, superano i 4 m. Sulle piante giovani le foglie sono ovali, cuoriformi alla base, verde brillante lucido, screziate di crema o giallo; sulle piante mature diventano profondamente lobate e possono arrivare a 90 cm. Le spate verdi compaiono solo di rado in coltivazione. È molto resistente e adattabile, tollera bene le annaffiature saltuarie, ma perde le variegature con poca luce. Va tenuta in casa, con minime sopra i 10-15 °C.$rewr$
 where slug = 'pothos' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Prunus persica è un albero deciduo della famiglia delle Rosaceae, dal portamento espanso, alto in genere 4-9 m, con foglie strette e lucide, da verde medio a scuro, lunghe fino a 15 cm. I fiori a coppa, rosa o rossi, larghi circa 4 cm, sbocciano in primavera prima della fogliazione e sono seguiti da frutti sferici, tomentosi e commestibili, gialli sfumati di rosso. Da questa specie sono state selezionate moltissime cultivar di pesco; viene spesso allevato a ventaglio o a spalliera contro un muro esposto a sud o a ovest, oppure usato come portinnesto. È rustico, indicativamente fino a -10/-5 °C. È considerato ospite ad alto rischio per Xylella fastidiosa: va sorvegliata la comparsa di disseccamenti anomali dei rami. Contro la bolla del pesco si interviene in via preventiva a fine inverno con prodotti rameici, e la potatura va fatta dopo la raccolta, mai in inverno, per non favorire cancro batterico e mal del piombo. La cultivar ornamentale 'Klara Mayer', alta fino a circa 5 m, ha fiori doppi rosa acceso di 3,5 cm in aprile.$rewr$
 where slug = 'prunus-persica' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Lythrum salicaria è una perenne erbacea robusta della famiglia delle Lythraceae, tipica delle zone umide, con fusti eretti alti fino a 1,2 m rivestiti di foglie strette simili a quelle del salice. Per un lungo periodo estivo produce piccoli fiori rosa-porpora vivo, larghi circa 2 cm, riuniti in dense spighe terminali, molto attraenti per api e farfalle. Preferisce terreno umido o molto umido e pieno sole; la crescita è vigorosa e la pianta può espandersi rapidamente. È estremamente rustica, oltre i -20 °C.$rewr$
 where slug = 'salcerella' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Sansevieria trifasciata è una perenne sempreverde della famiglia delle Asparagaceae che forma un cespo di foglie rigide, erette e a forma di spada, verde scuro variegato con bande grigio-verde chiaro. In estate o autunno può produrre racemi di fioretti tubulari appiccicosi, da bianco-verdolino a crema, talvolta profumati. È una classica pianta da appartamento, notoriamente tollerante alla trascuratezza, ma va protetta dall'eccesso di umidità invernale. Va tenuta in casa, con minime sopra i 10-15 °C, in substrato molto drenante.$rewr$
 where slug = 'sansevieria' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Sedum acre è una perenne succulenta glabra della famiglia delle Crassulaceae, tappezzante, con foglioline ovoidi e carnose addossate ai fusti. Da maggio a luglio produce piccoli fiori gialli stellati a cinque petali, graditi agli impollinatori. È molto rustica, oltre i -20 °C, e cresce in fretta, tanto da poter competere con le infestanti ma anche da espandersi oltre il punto desiderato. È xerofila e va coltivata in pieno sole senza irrigazioni; la linfa può irritare la pelle, quindi conviene usare i guanti.$rewr$
 where slug = 'sedum-acre' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Sedum morganianum è una perenne succulenta sempreverde della famiglia delle Crassulaceae, dal portamento ricadente, con fusti penduli lunghi 30 cm o più rivestiti di foglie carnose lanceolate ed embricate, glauche, blu-verde. In primavera ed estate porta mazzetti di fioretti stellati da rosa pallido a porpora-rossastro. È ideale per vasi sospesi e davanzali, ma le foglie si staccano al minimo tocco. Vuole posizione molto luminosa, substrato molto drenante e va tenuta al riparo dal gelo, con minime intorno a 5-10 °C.$rewr$
 where slug = 'sedum-morganianum' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Sedum spurium è una perenne succulenta semi-sempreverde della famiglia delle Crassulaceae, vigorosa e tappezzante, alta fino a circa 10 cm, con foglie carnose e dentate portate su fusti prostrati e radicanti. A fine estate produce fiori stellati rosa o bianchi in corimbi arrotondati. I colori del fogliame si fanno più intensi con luce forte e freddo. È molto rustica, ben oltre i -15 °C, ottima come tappezzante e per i bordi; teme i ristagni idrici.$rewr$
 where slug = 'sedum-spurium' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Succulenta ricadente da appartamento, un tempo classificata come Senecio rowleyanus e oggi ricondotta al genere Curio, nella famiglia delle Asteraceae. Ha foglie sferiche simili a perline disposte lungo fusti sottili e penduli, ed è molto decorativa in vasi sospesi. I fusti sono fragili e vanno maneggiati con cura; se il vaso non drena bene si ha marciume alla base. Vuole posizione luminosa con sole diretto solo filtrato e substrato sabbioso molto drenante.$rewr$
 where slug = 'senecio' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Sisyrinchium californicum è una perenne semi-sempreverde della famiglia delle Iridaceae, con foglie a spada grigio-verdi lunghe fino a 15 cm. In estate, steli largamente alati alti fino a 60 cm portano una successione di fiori stellati giallo vivo venati di bruno. È una pianta di breve durata che si autosemina abbondantemente, al punto da poter diventare invadente, ed è adatta a bordi di stagno e giardini umidi. È rustica, indicativamente fino a -10/-5 °C.$rewr$
 where slug = 'sisyrinchium-californicum' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Nassella tenuissima, ancora nota come Stipa tenuissima, è una graminacea decidua della famiglia delle Poaceae, alta fino a 60 cm, che forma un ciuffo eretto e compatto di foglie sottili come fili. In estate produce pannocchie fiorali strette, arcuate e piumose, color bruno chiaro, che le danno un aspetto leggero e ondeggiante al vento. Vuole pieno sole e terreno drenato di media fertilità, e teme i ristagni più del freddo: è rustica fino a circa -10/-5 °C. Non va tagliata a raso, e la pulizia del fogliame secco è meglio rimandarla a inizio primavera.$rewr$
 where slug = 'stipa-tenuissima' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Thymus serpyllum è un'aromatica tappezzante della famiglia delle Lamiaceae, a base legnosa e sempreverde, con foglie piccole e aromatiche e verticilli terminali di fioretti tubulari bilabiati, purpurei, rosa o bianchi, a fine primavera ed estate, molto visitati dagli insetti utili. È xerofilo e va coltivato in pieno sole, senza irrigazioni, dove la crescita rapida e strisciante gli permette di competere con le infestanti su muretti e scarpate. È rustico, indicativamente fino a -10/-15 °C.$rewr$
 where slug = 'timo-serpillo' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Tradescantia zebrina è una perenne sempreverde ricadente della famiglia delle Commelinaceae, alta fino a 15 cm, con foglie lanceolate verde-bronzo scuro attraversate da due bande argentate longitudinali sulla pagina superiore e porpora sul rovescio; i fioretti rosa-porpora, in piccoli mazzetti terminali, compaiono qua e là durante l'anno. Coltivata all'aperto ha crescita rapida e spontanea e si comporta da infestante, radicando da ogni frammento di fusto a contatto col terreno. È poco rustica: sotto 0 °C la parte aerea secca, ma ricaccia in primavera se le radici sono protette.$rewr$
 where slug = 'tradescantia' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Olea europaea è un albero sempreverde latifoglie della famiglia delle Oleaceae, dal portamento robusto e molto ramificato, a crescita lenta e grande longevità: in condizioni favorevoli può diventare millenario e raggiungere i 15-20 m, anche se in coltivazione resta più spesso tra 4,5 e 9 m. Le foglie, coriacee, strette e da obovate a ovali, lunghe fino a 7,5 cm, sono argentate sulla pagina inferiore; i piccoli fiori bianchi sono riuniti in racemi ascellari lunghi fino a 5 cm. Da questa specie derivano numerose cultivar, alcune fruttifere anche in climi non tipicamente olivicoli. È rustico fino a circa -10/-5 °C, ma le piante giovani soffrono sotto i -5 °C. È molto sensibile ai marciumi radicali da ristagno ed è classificato come ospite ad alto rischio per Xylella fastidiosa, il patogeno responsabile del disseccamento rapido dell'olivo in Puglia: vanno sorvegliati disseccamenti anomali dei rami e segnalati i sospetti alle autorità fitosanitarie.$rewr$
 where slug = 'ulivo' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Muscari armeniacum è una bulbosa perenne primaverile della famiglia delle Asparagaceae, vigorosa, alta fino a 20 cm, con foglie verdi strette e arcuate. In primavera gli steli eretti portano dense spighe di fioretti ovoidali, lunghi circa 5 mm, blu-violetto intenso e orlati di bianco, che ricordano piccoli acini. È molto rustica, oltre i -15 °C, e si naturalizza con facilità, infittendosi nel tempo al punto da poter diventare invadente. Vuole terreno drenato e va tenuta all'asciutto in estate, durante il riposo del bulbo; le foglie non vanno tagliate finché restano verdi.$rewr$
 where slug = 'uva-di-gatto' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Pianta della famiglia delle Verbenaceae (le forme ibride da giardino sono oggi spesso ricondotte al genere Glandularia), che può essere annuale, perenne o suffrutice, con foglie dentate o pennato-lobate e piccoli fiori a cinque petali a forma di piattino, riuniti in spighe o pannocchie tra estate e autunno. La fioritura è continua e la crescita rapida. Vuole sole e terreno fertile e drenato, teme i ristagni ed è sensibile all'oidio; è abbastanza rustica, indicativamente fino a -10/-5 °C.$rewr$
 where slug = 'verbena' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Matthiola incana è una perenne a base legnosa della famiglia delle Brassicaceae, a volte di breve durata, con fogliame stretto grigio-verde. Tra fine primavera e inizio estate produce spighe erette di fiori profumati, larghi fino a 2,5 cm, rosa, malva, porpora, violetti o bianchi. Molte cultivar si coltivano come piante da aiuola annuali o biennali, oppure per il fiore reciso. Vuole sole e terreno fertile, drenato, neutro o leggermente alcalino; teme il caldo eccessivo e i ristagni. È rustica, fino a circa -10/-5 °C.$rewr$
 where slug = 'violaciocca' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Zinnia elegans è un'annuale cespugliosa semirustica della famiglia delle Asteraceae, capostipite di molte cultivar da giardino. In estate produce capolini a margherita, singoli, semidoppi o doppi, in una gamma che va dal bianco al rosa, rosso, arancio e giallo, portati su lunghi steli sopra un fogliame lanceolato verde medio; i fiori sono attraenti per api e farfalle e si prestano bene al taglio. Vuole sole e terreno fertile e drenato, teme il gelo, con danni già intorno a 1 °C e sotto, ed è sensibile all'oidio, soprattutto con umidità elevata.$rewr$
 where slug = 'zinnia' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Zinnia angustifolia è una specie della famiglia delle Asteraceae distinta dalla più comune Zinnia elegans: ha fiore singolo più aperto, con petali stretti e distanziati, non sovrapposti, e centro ispido e arruffato. È molto più resistente alla siccità e all'oidio, con portamento compatto e ramificato e fioritura abbondante e continua, il che la rende ottima da bordura. Il genere raccoglie annuali, perenni o suffrutici, con fusti ramificati, foglie opposte e capolini solitari terminali in estate. Vuole sole e terreno drenato anche povero, e teme comunque i ristagni idrici.$rewr$
 where slug = 'zinnia-angustifolia' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Cucurbita moschata è una zucca invernale della famiglia delle Cucurbitaceae, da cui derivano diverse cultivar commerciali. È una pianta annuale strisciante, con fusti lunghi anche oltre 4 m, che produce frutti cilindrici con un'estremità bulbosa opposta al picciolo. La buccia, dura e liscia, è di un arancio pallido variabile; la polpa è arancio vivo e dolce, e i frutti, che si conservano bene una volta maturi, possono superare i 3 kg. La cultivar Butternut è tra le più note per la polpa dolce. Teme il gelo e va messa a dimora solo dopo le ultime gelate, in pieno sole, su terreno fertile e ricco di sostanza organica; richiede molto spazio.$rewr$
 where slug = 'zucca' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Cucurbita pepo è la specie capostipite della famiglia delle Cucurbitaceae da cui derivano le cultivar di zucchine, zucche estive e invernali, e zucche ornamentali. È un'annuale tenera, strisciante o cespugliosa, con fiori gialli maschili e femminili portati sulla stessa pianta: il fiore femminile ha un piccolo frutto immaturo alla base. Il frutto può essere verde come le zucchine, oppure crema, giallo o arancio. Teme il gelo e vuole pieno sole, terreno fertile e drenato e acqua abbondante. È molto sensibile all'oidio a fine estate, e conviene raccogliere i frutti giovani per stimolare nuova produzione.$rewr$
 where slug = 'zucchina' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

update public.specie set descrizione = $rewr$Zamioculcas zamiifolia è una perenne sempreverde rizomatosa della famiglia delle Araceae: i rizomi carnosi sotterranei immagazzinano acqua e riserve, mentre le foglie pinnate, lucide e verde scuro, lunghe 40-60 cm, nascono direttamente dal terreno e portano da sei a otto paia di foglioline. In estate, tra le basi fogliari, possono comparire uno o due fiori bianco-verdi simili a quelli degli aro, seguiti da bacche bianche. È estremamente tollerante della scarsa luce e della trascuratezza, ma teme i ristagni idrici, che provocano il marciume dei rizomi, la causa di morte più comune. Tutte le parti sono tossiche se ingerite, quindi va tenuta lontano da bambini e animali domestici. Si coltiva in casa, con minime sopra i 10-15 °C.$rewr$
 where slug = 'zz-plant' and descrizione ilike '%testo originale in inglese%' and descrizione_originale is not null;

commit;
