-- Fase 3 (#120), sesto e ultimo blocco (14/14): specie non ancora usate da
-- nessuna pianta reale, priorità più bassa nel piano ma completano la
-- copertura dell'intero catalogo (105 specie).
--
-- pothos-talea non è un duplicato vuoto come stracchino/saxifraga: ha alert
-- reali e specifici sulla radicazione in acqua (già nella fonte), solo
-- descrizione ed esigenze erano vuote — completate qui. vaso.adatta = false
-- perché questa scheda descrive una fase transitoria in acqua, non una
-- coltivazione in vaso con terriccio.

update specie set famiglia_botanica = $t$Crassulaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Crassulaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 18, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$calancola$t$;
update specie set famiglia_botanica = $t$Ericaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Ericaceae", "giorni_germinazione": "20-30", "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["autunno"], "resistenza_gelo": "media", "spaziatura_cm": 40, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$erica-del-messico$t$;
update specie set famiglia_botanica = $t$Asteraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asteraceae", "giorni_germinazione": "10-15", "giorni_trapianto": "30", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "bassa", "spaziatura_cm": 25, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.4}$j$::jsonb where slug = $t$gazania$t$;
update specie set famiglia_botanica = $t$Acanthaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Acanthaceae", "giorni_germinazione": "14-21", "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 12, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$ipoeste$t$;
update specie set famiglia_botanica = $t$Lamiaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Lamiaceae", "giorni_germinazione": "14-21", "giorni_trapianto": "40-60", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 40, "consociazioni_favorevoli": ["rosmarino", "cavolo"], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$lavanda$t$;
update specie set famiglia_botanica = $t$Montiaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Montiaceae", "giorni_germinazione": "20-30", "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "alta", "spaziatura_cm": 15, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.4}$j$::jsonb where slug = $t$lewisia$t$;
update specie set famiglia_botanica = $t$Lamiaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Lamiaceae", "giorni_germinazione": "10-15", "giorni_trapianto": "30-40", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "alta", "spaziatura_cm": 25, "consociazioni_favorevoli": ["pomodoro", "peperone"], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 18, "irrigazione_fattore": 0.6}$j$::jsonb where slug = $t$origano$t$;
update specie set famiglia_botanica = $t$Crassulaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Crassulaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$pianta-della-fortuna$t$;
update specie set famiglia_botanica = $t$Crassulaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Crassulaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 18, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$pianta-panda$t$;
update specie set famiglia_botanica = $t$Araceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Araceae", "giorni_germinazione": null, "giorni_trapianto": "20-30", "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera", "estate"], "resistenza_gelo": "nessuna", "spaziatura_cm": null, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": false, "dimensione_minima_litri": null, "rinvaso_ogni_mesi": null, "irrigazione_fattore": null}$j$::jsonb, descrizione = $t$Fase di radicazione di talee di pothos in acqua, prima del trapianto in vaso con terriccio.$t$, esigenze = $j${"luce": "Luce diffusa, mai sole diretto (rischio di alghe nell’acqua)", "acqua": "Talea con il nodo radicale sempre immerso, acqua cambiata regolarmente", "terreno": "Nessuno in questa fase (radicazione in acqua); terriccio drenante dopo il trapianto"}$j$::jsonb where slug = $t$pothos-talea$t$;
update specie set famiglia_botanica = $t$Lamiaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Lamiaceae", "giorni_germinazione": "15-25", "giorni_trapianto": "40-60", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 50, "consociazioni_favorevoli": ["salvia", "cavolo"], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.4}$j$::jsonb where slug = $t$rosmarino$t$;
update specie set famiglia_botanica = $t$Caryophyllaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Caryophyllaceae", "giorni_germinazione": "14-21", "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$saponaria$t$;
update specie set famiglia_botanica = $t$Saxifragaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Saxifragaceae", "giorni_germinazione": "14-21", "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$sassifraga$t$;
update specie set famiglia_botanica = $t$Crassulaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Crassulaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 15, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 1, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$sedum-makinoi$t$;
