-- Lotto 2: 1033 nomi italiani da PlantNet (specie con un solo nome comune italiano).
-- Abbinati per nome scientifico; 201 abbinamenti scartati dopo revisione manuale
-- (altro taxon, cultivar, lingua straniera, refusi, troppo generici).
-- Controllato prima dell'apply: nessuna collisione con specie_nome_key.
-- Nomi italiani (lotto2).
-- Solo righe ancora senza nome italiano (nome = nome_scientifico) e non cultivar.
update specie s set nome = v.nome
from (values
  ('abies-bracteata', 'Abete di Santa Lucia'),
  ('abies-chensiensis', 'Abete del Chensi'),
  ('abies-delavayi', 'Abete di Delavay'),
  ('abies-forrestii', 'Abete di Forrest'),
  ('abies-fraseri', 'Abete di Fraser'),
  ('abies-guatemalensis', 'Abete del Guatemala'),
  ('abies-kawakamii', 'Abete di Kawakami'),
  ('abies-mariesii', 'Abete di Maries'),
  ('abies-pindrow', 'Abete pindrow'),
  ('abies-religiosa', 'Abete messicano'),
  ('abies-sachalinensis', 'Abete di Sachalin'),
  ('abies-sibirica', 'Abete siberiano'),
  ('abies-spectabilis', 'Abete dell''Imalaia'),
  ('abies-squamata', 'Abete squamato'),
  ('acacia-verticillata', 'Mimosa verticillata'),
  ('acalypha-hispida', 'Acalifa'),
  ('acanthus-spinosus', 'Acanto spinoso'),
  ('acer-carpinifolium', 'Acero a foglie di carpino'),
  ('acer-circinatum', 'Acero a foglie ronde'),
  ('acer-cissifolium', 'Acero a foglie di vite'),
  ('acer-crataegifolium', 'Acero a foglie di biancospino'),
  ('acer-davidii', 'Acero di Padre David'),
  ('acer-diabolicum', 'Acero cornuto'),
  ('acer-distylum', 'Acero a foglie di tiglio'),
  ('acer-glabrum', 'Acero a foglie glabre'),
  ('acer-griseum', 'Acero grigio'),
  ('acer-macrophyllum', 'Acero dell''Oregon'),
  ('acer-mandshuricum', 'Acero di Manciuria'),
  ('acer-maximowiczianum', 'Acero di Maximowicz'),
  ('acer-miyabei', 'Acero di Miyabe'),
  ('acer-pensylvanicum', 'Acero screziato'),
  ('acer-pseudosieboldianum', 'Acero di Corea'),
  ('acer-sieboldianum', 'Acero di Siebold'),
  ('acer-triflorum', 'Acero rugoso'),
  ('acer-truncatum', 'Acero troncato'),
  ('achillea-clavennae', 'Millefoglio di Clavena'),
  ('achillea-maritima', 'Santolina delle spiagge'),
  ('achillea-tomentosa', 'Millefoglio giallo'),
  ('acmella-oleracea', 'Crescione del Brasile'),
  ('aconitum-burnatii', 'Aconito di Burnat'),
  ('acorus-gramineus', 'Calamo aromatico'),
  ('actaea-racemosa', 'Cimicifuga'),
  ('adenophora-liliifolia', 'Campanella odorosa'),
  ('adiantum-pedatum', 'Capelvenere canadese'),
  ('adoxa-moschatellina', 'Moscatella'),
  ('aesculus-chinensis', 'Ippocastano cinese'),
  ('aesculus-parviflora', 'Ippocastano a fiori piccoli'),
  ('aesculus-sylvatica', 'Ippocastano della Carolina'),
  ('aesculus-turbinata', 'Ippocastano giapponese'),
  ('agathis-australis', 'Pino kauri'),
  ('agave-angustifolia', 'Agave dei Caraibi'),
  ('agave-parviflora', 'Agave a fiore piccolo'),
  ('agave-tequilana', 'Agave blu'),
  ('ageratum-houstonianum', 'Agerato celestino'),
  ('alangium-chinense', 'Alangio cinese'),
  ('alangium-platanifolium', 'Alangio a foglie platano'),
  ('albizia-lebbeck', 'Albizia indiana'),
  ('alchemilla-vetteri', 'Ventaglina di Vetter'),
  ('allium-altaicum', 'Cipolla d''inverno'),
  ('allium-amethystinum', 'Aglio ametistino'),
  ('allium-angulosum', 'Aglio angoloso'),
  ('allium-flavum', 'Aglio giallo'),
  ('allium-giganteum', 'Aglio gigante'),
  ('allium-moly', 'Aglio dorato'),
  ('allium-pendulinum', 'Aglio pendulo'),
  ('allium-porrum', 'Porro'),
  ('allium-senescens', 'Aglio montano'),
  ('allium-siculum', 'Aglio della Sicilia'),
  ('allium-suaveolens', 'Aglio odoroso'),
  ('allium-subhirsutum', 'Aglio pelosetto'),
  ('alnus-japonica', 'Ontano giapponese'),
  ('alnus-nitida', 'Ontano dell''Imalaia'),
  ('alnus-rhombifolia', 'Ontano a foglie romboidali'),
  ('alnus-rubra', 'Ontano rosso'),
  ('alnus-serrulata', 'Ontano rugoso'),
  ('alnus-subcordata', 'Ontano del Caucaso'),
  ('alocasia-odora', 'Orecchie di elefante'),
  ('aloe-perryi', 'Aloe di Perry'),
  ('aloe-polyphylla', 'Aloe spiralata'),
  ('aloe-striata', 'Aloe corallo'),
  ('alsophila-tricolor', 'Felce argentea'),
  ('amaranthus-graecizans', 'Amaranto blito minore'),
  ('amaranthus-hybridus', 'Amaranto a spiga verde'),
  ('amaranthus-palmeri', 'Amaranto di Palmer'),
  ('amaranthus-viridis', 'Amaranto verde'),
  ('amelanchier-asiatica', 'Nespolino asiatico'),
  ('amelanchier-laevis', 'Nespolino americano'),
  ('amorpha-canescens', 'Indaco bastardo bianco'),
  ('ampelopsis-japonica', 'Vite vergine giapponese'),
  ('andrographis-paniculata', 'Andrografis'),
  ('andromeda-polifolia', 'Andromeda'),
  ('androsace-pubescens', 'Androsace pubescente'),
  ('androsace-septentrionalis', 'Androsace nordica'),
  ('anigozanthos-flavidus', 'Zampa di canguro'),
  ('anthemis-cupaniana', 'Camomilla delle Madonie'),
  ('anthericum-ramosum', 'Lilioasfodelo minore'),
  ('apocynum-cannabinum', 'Apocino canapino'),
  ('apocynum-venetum', 'Apocino veneto'),
  ('aquilegia-alpina', 'Aquilegia maggiore'),
  ('arabis-allionii', 'Arabetta di Allioni'),
  ('arabis-alpina', 'Arabetta alpina'),
  ('arabis-caucasica', 'Arabetta del Caucaso'),
  ('arabis-hirsuta', 'Arabetta irsuta'),
  ('aralia-chinensis', 'Aralia cinese'),
  ('aralia-spinosa', 'Angelica spinosa'),
  ('araucaria-cunninghamii', 'Araucaria di Cunningham'),
  ('arbutus-menziesii', 'Madrona'),
  ('archontophoenix-cunninghamiana', 'Palma di Cunningham'),
  ('argania-spinosa', 'Legno ferro del Marocco'),
  ('aristaloe-aristata', 'Aloe aristata'),
  ('aristolochia-rotunda', 'Aristolochia rotonda'),
  ('armeria-maritima', 'Armeria'),
  ('armeria-pungens', 'Spillone delle spiagge'),
  ('arnica-montana', 'Arnica'),
  ('artemisia-biennis', 'Assenzio bienne'),
  ('asarum-canadense', 'Asaro'),
  ('asclepias-tuberosa', 'Asclepiade tuberosa'),
  ('aspalathus-linearis', 'Tè rosso del Sudafrica'),
  ('asparagus-albus', 'Asparago bianco'),
  ('asparagus-aphyllus', 'Asparago marino'),
  ('asparagus-falcatus', 'Asparago del Perù'),
  ('asparagus-horridus', 'Asparago spinoso'),
  ('asparagus-maritimus', 'Asparago amaro'),
  ('asparagus-tenuifolius', 'Asparago selvatico'),
  ('asphodeline-liburnica', 'Asfodelo della Liburnia'),
  ('asphodeline-lutea', 'Asfodelo giallo'),
  ('asphodelus-fistulosus', 'Asfodelo fistoloso'),
  ('asplenium-fontanum', 'Asplenio delle fonti'),
  ('asplenium-marinum', 'Asplenio marino'),
  ('asplenium-septentrionale', 'Asplenio settentrionale'),
  ('asplenium-viride', 'Asplenio verde'),
  ('astragalus-alpinus', 'Astragalo alpino'),
  ('astragalus-exscapus', 'Astragalo nano'),
  ('astrantia-minor', 'Astranzia minore'),
  ('astrocaryum-vulgare', 'Tucum'),
  ('astrophytum-asterias', 'Cactus riccio di mare'),
  ('astrophytum-myriostigma', 'Berretto del Vescovo'),
  ('attalea-maripa', 'Palma maripa'),
  ('austrocedrus-chilensis', 'Cedro del Cile'),
  ('avena-barbata', 'Avena a due barbe'),
  ('averrhoa-carambola', 'Carambola'),
  ('azadirachta-indica', 'Neem'),
  ('azara-microphylla', 'Azara a foglie piccole'),
  ('baccharis-halimifolia', 'Baccharis'),
  ('balanites-aegyptiaca', 'Dattero deserto'),
  ('bauhinia-purpurea', 'Albero delle orchidee'),
  ('begonia-grandis', 'Begonia a foglie larghe'),
  ('berberidopsis-corallina', 'Corallina'),
  ('berberis-aetnensis', 'Crespino dell''Etna'),
  ('berberis-gagnepainii', 'Crespino di Gagnepain'),
  ('berberis-wilsoniae', 'Crespino'),
  ('beta-trigyna', 'Bietola trigina'),
  ('betula-alleghaniensis', 'Betulla gialla canadese'),
  ('betula-maximowicziana', 'Betulla di Maximowicz'),
  ('betula-medwediewii', 'Betulla del Caucaso'),
  ('betula-nana', 'Betulla nana'),
  ('betula-occidentalis', 'Betulla occidentale'),
  ('billbergia-nutans', 'Lacrime della Regina'),
  ('blighia-sapida', 'Akee dell''Africa'),
  ('boerhavia-diffusa', 'Punarnava'),
  ('bolboschoenus-laticarpus', 'Lisca a frutti larghi'),
  ('bongardia-chrysogonum', 'Bongardia'),
  ('borago-pygmaea', 'Borragine di Sardegna'),
  ('borassus-aethiopum', 'Borasso'),
  ('botrychium-virginianum', 'Botrichio virginiano'),
  ('brahea-edulis', 'Palma di Guadalupe'),
  ('brasenia-schreberi', 'Brasenia'),
  ('brassica-elongata', 'Cavolo di Persia'),
  ('brassica-tournefortii', 'Cavolo di Tournefort'),
  ('brimeura-amethystina', 'Giacinto ametistino'),
  ('bromus-marginatus', 'Bromo montano'),
  ('brosimum-alicastrum', 'Capomo'),
  ('brugmansia-x-candida', 'Trombe degli angeli'),
  ('bupleurum-falcatum', 'Bupleuro falcato'),
  ('bupleurum-longifolium', 'Bupleuro con foglie lunghe'),
  ('cabomba-caroliniana', 'Cabomba della Carolina'),
  ('caesalpinia-echinata', 'Legno del Brasile'),
  ('calamus-manan', 'Palma rampicante'),
  ('callitriche-hermaphroditica', 'Callitrice'),
  ('calotropis-procera', 'Calotropo'),
  ('calycanthus-occidentalis', 'Calicanto americano'),
  ('campanula-cochleariifolia', 'Campanula dei ghiaioni'),
  ('campanula-fenestrellata', 'Campanula istriana'),
  ('campanula-fragilis', 'Campanula napoletana'),
  ('campanula-garganica', 'Campanula del Gargano'),
  ('campanula-glomerata', 'Campanula agglomerata'),
  ('campanula-pyramidalis', 'Campanula adriatica'),
  ('campanula-raineri', 'Campanula dell''arciduca'),
  ('campanula-sibirica', 'Campanula siberiana'),
  ('campanula-thyrsoides', 'Campanula gialla'),
  ('campanula-tommasiniana', 'Campanula di Tommasini'),
  ('campanula-versicolor', 'Campanula pugliese'),
  ('cananga-odorata', 'Ylang Ylang'),
  ('canarina-canariensis', 'Canarina campanula'),
  ('capsicum-pubescens', 'Rocoto'),
  ('carapichea-ipecacuanha', 'Ipecacuana'),
  ('cardamine-bulbifera', 'Dentaria minore'),
  ('cardamine-enneaphyllos', 'Dentaria a nove foglie'),
  ('cardamine-heptaphylla', 'Dentaria pennata'),
  ('cardamine-kitaibelii', 'Dentaria di Kitaibel'),
  ('cardamine-raphanifolia', 'Billeri di Calabria'),
  ('cardamine-trifolia', 'Billeri a tre foglie'),
  ('carex-acutiformis', 'Carice tagliente'),
  ('carex-arenaria', 'Carice comune'),
  ('carex-brizoides', 'Carice brizolina'),
  ('carex-buxbaumii', 'Carice di Buxbaum'),
  ('carex-disticha', 'Carice contratta'),
  ('carex-divulsa', 'Carice separata'),
  ('carex-firma', 'Carice rigida'),
  ('carex-panicea', 'Carice migliacea'),
  ('carex-pendula', 'Carice maggiore'),
  ('carex-remota', 'Carice ascellare'),
  ('carlina-acanthifolia', 'Carlina zolfina'),
  ('carludovica-palmata', 'Carludovica'),
  ('carpinus-japonica', 'Carpino del Giappone'),
  ('carpobrotus-glaucescens', 'Unghie di strega'),
  ('carya-aquatica', 'Caria palustre'),
  ('carya-cordiformis', 'Hickory delle paludi'),
  ('carya-glabra', 'Hickory glabra'),
  ('carya-laciniosa', 'Hickory maggiore'),
  ('carya-ovata', 'Hickory minore'),
  ('caryota-urens', 'Palma kithul'),
  ('casimiroa-edulis', 'Sapote bianco'),
  ('cassia-grandis', 'Cassia a grandi frutti'),
  ('castanea-mollissima', 'Castagno cinese'),
  ('castanea-pumila', 'Castagno nano'),
  ('casuarina-cunninghamiana', 'Casuarina'),
  ('catalpa-bungei', 'Catalpa di Bunge'),
  ('ceanothus-thyrsiflorus', 'Lillà californiano'),
  ('cecropia-peltata', 'Legno trombetta'),
  ('cedronella-canariensis', 'Mentastro'),
  ('celtis-caucasica', 'Bagolaro del Caucaso'),
  ('celtis-sinensis', 'Bagolaro della Cina'),
  ('celtis-tournefortii', 'Bagolaro dell''Etna'),
  ('centaurea-acaulis', 'Fiordaliso acaule'),
  ('centaurea-cineraria', 'Fiordaliso delle scogliere'),
  ('centaurea-depressa', 'Fiordaliso depresso'),
  ('centaurea-melitensis', 'Fiordaliso maltese'),
  ('centaurea-ragusina', 'Fiordaliso di Ragusa'),
  ('centranthus-lecoqii', 'Valeriana rosa'),
  ('cephalaria-alpina', 'Vedovina alpina'),
  ('cephalaria-gigantea', 'Vedovina gigante'),
  ('cephalotaxus-fortunei', 'Cefalotasso cinese'),
  ('cerastium-tomentosum', 'Peverina tomentosa'),
  ('cercis-chinensis', 'Albero di Giuda cinese'),
  ('ceroxylon-alpinum', 'Palma della cera'),
  ('chaenostoma-cordatum', 'Bacopa'),
  ('chamaedaphne-calyculata', 'Cassandra'),
  ('chamelaucium-uncinatum', 'Fiore di cera'),
  ('chasmanthe-aethiopica', 'Gladiatore africano'),
  ('chenopodium-berlandieri', 'Farinello di Berlandier'),
  ('chenopodium-suecicum', 'Farinello svedese'),
  ('chionanthus-virginicus', 'Albero della neve'),
  ('chondrilla-chondrilloides', 'Lattugaccio dei torrenti'),
  ('chorispora-tenella', 'Corispora delicata'),
  ('chrysalidocarpus-lutescens', 'Palma Areca'),
  ('chrysobalanus-icaco', 'Icaco'),
  ('chrysolepis-chrysophylla', 'Castagno dorato'),
  ('chrysophyllum-cainito', 'Cainito'),
  ('cichorium-spinosum', 'Cicoria spinosa'),
  ('cicuta-virosa', 'Cicuta acquatica'),
  ('cirsium-erisithales', 'Cardo zampa d''Orso'),
  ('cirsium-rivulare', 'Cardo dei rivi'),
  ('cirsium-tuberosum', 'Cardo tuberoso'),
  ('cistus-inflatus', 'Cisto irsuto'),
  ('cistus-populifolius', 'Cisto a foglie di pioppo'),
  ('citrofortunella-microcarpa', 'Calamondino'),
  ('citrus-australasica', 'Limone caviale'),
  ('citrus-x-junos', 'Yuzu'),
  ('clematis-campaniflora', 'Clematide campaniflora'),
  ('clematis-integrifolia', 'Clematide a foglie intere'),
  ('clematis-tangutica', 'Clematide di Tangut'),
  ('cleome-spinosa', 'Cleome comune'),
  ('clerodendrum-trichotomum', 'Clerodendro'),
  ('clinopodium-vulgare', 'Clinopodio dei boschi'),
  ('cochlearia-pyrenaica', 'Coclearia pirenaica'),
  ('coffea-canephora', 'Caffè robusta'),
  ('cola-acuminata', 'Albero della cola'),
  ('colchicum-bivonae', 'Colchico di Bivona'),
  ('colchicum-cilicicum', 'Colchico della Cilicia'),
  ('colletia-paradoxa', 'Albero degli aeroplanini'),
  ('collinsonia-canadensis', 'Balsamo del cavallo'),
  ('colophospermum-mopane', 'Albero farfalla'),
  ('commelina-virginica', 'Erba miseria americana'),
  ('comptonia-peregrina', 'Comptonia'),
  ('convolvulus-sabatius', 'Vilucchio della Riviera'),
  ('coprosma-repens', 'Coprosma rosso'),
  ('corchorus-capsularis', 'Juta'),
  ('corema-album', 'Corema bianca'),
  ('cornus-alternifolia', 'Corniolo a foglie alternate'),
  ('cornus-canadensis', 'Corniolo del Canadà'),
  ('cornus-controversa', 'Corniolo controverso'),
  ('cornus-suecica', 'Corniolo svedese'),
  ('corydalis-solida', 'Colombina solida'),
  ('corylus-americana', 'Nocciolo americano'),
  ('corylus-chinensis', 'Nocciolo di Cina'),
  ('corymbia-citriodora', 'Eucalipto a profumo di limone'),
  ('corymbia-ficifolia', 'Eucalipto a fiori rossi'),
  ('cotinus-obovatus', 'Scotano americano'),
  ('cotoneaster-adpressus', 'Cotognastro strisciante'),
  ('cotoneaster-bullatus', 'Cotognastro bolloso'),
  ('cotoneaster-dielsianus', 'Cotognastro di Diels'),
  ('cotoneaster-divaricatus', 'Cotognastro divaricato'),
  ('cotoneaster-franchetii', 'Cotognastro di Franchet'),
  ('cotyledon-orbiculata', 'Orecchia d''elefante'),
  ('cotyledon-tomentosa', 'Zampa d''orso'),
  ('crassula-arborescens', 'Crassula arbustiva'),
  ('crassula-helmsii', 'Erba grassa di Helms'),
  ('crassula-pyramidalis', 'Tempio di Buddha'),
  ('crataegus-douglasii', 'Cratego di Douglas'),
  ('crataegus-phaenopyrum', 'Cratego di Washington'),
  ('crepis-rubra', 'Radicchiella rosea'),
  ('crocus-corsicus', 'Zafferano di Corsica'),
  ('crocus-minimus', 'Zafferano minore'),
  ('cucumis-metuliferus', 'Kiwano'),
  ('cucurbita-foetidissima', 'Biccaciuccio'),
  ('cunila-origanoides', 'Cunila'),
  ('cupressus-cashmeriana', 'Cipresso di Cashmir'),
  ('cycas-circinalis', 'Palma del sago delle Indie orientali'),
  ('cyclamen-africanum', 'Ciclamino africano'),
  ('cyclamen-repandum', 'Ciclamino primaverile'),
  ('cyclospermum-leptophyllum', 'Sedano americano'),
  ('cylindropuntia-imbricata', 'Fico d''India arborescente'),
  ('cymbalaria-hepaticifolia', 'Ciombolino di Corsica'),
  ('cymbalaria-pallida', 'Ciombolino abruzzese'),
  ('cynanchum-acutum', 'Crisciola'),
  ('cyperus-involucratus', 'Papiro'),
  ('cystopteris-montana', 'Felcetta montana'),
  ('cytisus-ardoinoi', 'Citiso di Ardoino'),
  ('cytisus-decumbens', 'Citiso sdraiato'),
  ('daboecia-cantabrica', 'Daboecia'),
  ('dacrycarpus-dacrydioides', 'Podocarpo della Nuova Zelanda'),
  ('dacrydium-cupressinum', 'Rimu'),
  ('dahlia-imperialis', 'Dalia gigante'),
  ('dalbergia-latifolia', 'Palissandro delle Indie Orientali'),
  ('danae-racemosa', 'Lauro d''Alessandria'),
  ('daphne-blagayana', 'Dafne del Conte Blagay'),
  ('daphne-sericea', 'Dafne sericea'),
  ('dendrobium-bigibbum', 'Orchidea dalle Due Gobbe'),
  ('dendrocalamus-giganteus', 'Bambù gigante'),
  ('dendrocalamus-strictus', 'Bambù dall''India'),
  ('dianthus-alpinus', 'Garofano alpino'),
  ('dianthus-arenarius', 'Garofano delle sabbie'),
  ('dianthus-pavonius', 'Garofano pavonio'),
  ('dichondra-argentea', 'Dicondra'),
  ('dicksonia-antarctica', 'Felce arborea antartica'),
  ('digitalis-ferruginea', 'Digitale bruna'),
  ('digitalis-laevigata', 'Digitale della Rosandra'),
  ('digitalis-lanata', 'Digitale lanosa'),
  ('dimocarpus-longan', 'Longan'),
  ('dimorphotheca-fruticosa', 'Margherita Africana'),
  ('dioscorea-elephantipes', 'Pane degli ottentotti'),
  ('dioscorea-japonica', 'Igname del Giappone'),
  ('diospyros-celebica', 'Ebeno di Makassar'),
  ('diospyros-crassiflora', 'Ebeno africano'),
  ('diospyros-digyna', 'Sapote nero'),
  ('dipsacus-pilosus', 'Scardaccione peloso'),
  ('disocactus-flagelliformis', 'Cactus coda di topo'),
  ('doronicum-austriacum', 'Doronico austriaco'),
  ('doronicum-pardalianches', 'Doronico medicinale'),
  ('doronicum-x-excelsum', 'Doronico gigante'),
  ('draba-aizoides', 'Draba aizoide'),
  ('dracaena-cinnabari', 'Albero del drago di Socotra'),
  ('dracocephalum-moldavica', 'Dracocefalo della Moldavia'),
  ('drimys-winteri', 'Corteccia di Winter'),
  ('drosanthemum-hispidum', 'Barba di Giove'),
  ('drosera-capensis', 'Drosera'),
  ('dysphania-anthelmintica', 'Farinello suffruticoso'),
  ('echeveria-pulidonis', 'Rosa di pietra'),
  ('echinocereus-rigidissimus', 'Cactus arcobaleno'),
  ('elaeagnus-commutata', 'Eleagno argenteo'),
  ('elaeagnus-macrophylla', 'Olivagno'),
  ('elaeis-guineensis', 'Palma da olio'),
  ('eleusine-coracana', 'Panico indiano'),
  ('epimedium-alpinum', 'Epimedio alpino'),
  ('episcia-cupreata', 'Pianta tartaruga'),
  ('equisetum-pratense', 'Equiseto pratense'),
  ('equisetum-ramosissimum', 'Equiseto ramosissimo'),
  ('equisetum-variegatum', 'Equiseto variegato'),
  ('eragrostis-spectabilis', 'Erba dell''amore'),
  ('eremurus-himalaicus', 'Eremuro'),
  ('erica-australis', 'Erica della Spagna'),
  ('erica-ciliaris', 'Erica ciliata'),
  ('erica-manipuliflora', 'Erica pugliese'),
  ('erigeron-philadelphicus', 'Margherita selvaggia'),
  ('eriocephalus-africanus', 'Eriocefalo africano'),
  ('eriophorum-vaginatum', 'Pennacchi guainati'),
  ('eryngium-creticum', 'Calcatreppola di Creta'),
  ('eryngium-giganteum', 'Eringio gigante'),
  ('erysimum-repandum', 'Violaciocca infestante'),
  ('erythroxylum-coca', 'Coca'),
  ('eucalyptus-coccifera', 'Eucalipto coccifero'),
  ('eucalyptus-dalrympleana', 'Eucalipto a foglie largi'),
  ('eucalyptus-gunnii', 'Eucalipto del sidro'),
  ('eucalyptus-nitens', 'Eucalipto brillante'),
  ('eucalyptus-occidentalis', 'Eucalipto occidentale'),
  ('eucalyptus-regnans', 'Eucalipto australiano'),
  ('eucalyptus-robusta', 'Eucalipto robusto'),
  ('eucalyptus-viminalis', 'Eucalipto bianco'),
  ('eucryphia-glutinosa', 'Eucrifia del Cile'),
  ('euonymus-alatus', 'Evonimo alato'),
  ('euonymus-fortunei', 'Evonimo'),
  ('euonymus-japonicus', 'Evonimo del Giappone'),
  ('euphorbia-ceratocarpa', 'Euforbia cornuta'),
  ('euphorbia-epithymoides', 'Euforbia multicolore'),
  ('euphorbia-nicaeensis', 'Euforbia di Nizza'),
  ('euphorbia-obesa', 'Euforbia obesa'),
  ('euphorbia-pithyusa', 'Euforbia delle Baleari'),
  ('euphorbia-rigida', 'Euforbia rigida'),
  ('euphorbia-tirucalli', 'Pianta di corallo'),
  ('euryops-pectinatus', 'Margherita gialla'),
  ('euterpe-oleracea', 'Açaí'),
  ('fagus-crenata', 'Faggio crenato'),
  ('fagus-engleriana', 'Faggio cinese'),
  ('fagus-japonica', 'Faggio del Giappone'),
  ('fagus-orientalis', 'Faggio orientale'),
  ('felicia-amelloides', 'Agatea'),
  ('ferocactus-pilosus', 'Barile di fuoco messicano'),
  ('ferula-gummosa', 'Galbano'),
  ('festuca-valesiaca', 'Festuca del Vallese'),
  ('fibigia-clypeata', 'Fibigia comune'),
  ('ficus-benghalensis', 'Ficus indiano'),
  ('firmiana-simplex', 'Sterculia'),
  ('fitzroya-cupressoides', 'Alerce'),
  ('fragaria-moschata', 'Fragola moscata'),
  ('fraxinus-chinensis', 'Frassino cinese'),
  ('fraxinus-latifolia', 'Frassino dell''Oregon'),
  ('fraxinus-mandshurica', 'Frassino di Manciuria'),
  ('fraxinus-nigra', 'Frassino nero'),
  ('fraxinus-quadrangulata', 'Frassino blu'),
  ('fraxinus-velutina', 'Frassino dell''Arizona'),
  ('fritillaria-affinis', 'Campanella della Missione'),
  ('gaillardia-aristata', 'Palle di fuoco'),
  ('gaillardia-pulchella', 'Cappello messicano'),
  ('galatella-linosyris', 'Astro spillo d''oro'),
  ('galeopsis-bifida', 'Canapetta bifida'),
  ('garcinia-mangostana', 'Mangostano'),
  ('gaultheria-mucronata', 'Pernettya'),
  ('gelsemium-sempervirens', 'Gelsomino giallo'),
  ('genista-aetnensis', 'Ginestra dell''Etna'),
  ('gentiana-punctata', 'Genziana punteggiata'),
  ('geranium-asphodeloides', 'Geranio con radice d''asfodelo'),
  ('geranium-bohemicum', 'Geranio di Boemia'),
  ('geranium-lucidum', 'Geranio lucido'),
  ('geranium-maderense', 'Geranio di Madera'),
  ('geranium-nodosum', 'Geranio nodoso'),
  ('geranium-pyrenaicum', 'Geranio dei Pirenei'),
  ('geranium-reflexum', 'Geranio a petali riflessi'),
  ('geranium-sibiricum', 'Geranio di Siberia'),
  ('geranium-versicolor', 'Geranio striato'),
  ('geum-montanum', 'Cariofillata montana'),
  ('glaucidium-palmatum', 'Papavero del Giappone'),
  ('gleditsia-japonica', 'Gleditsia giapponese'),
  ('gleditsia-sinensis', 'Gleditsia cinese'),
  ('globularia-vulgaris', 'Vedovella dei prati'),
  ('glycyrrhiza-echinata', 'Liquirizia setolosa'),
  ('goeppertia-crocata', 'Calathea crocata'),
  ('goeppertia-ornata', 'Calathea ornata'),
  ('guaiacum-sanctum', 'Guaiaco'),
  ('guizotia-abyssinica', 'Guizotia'),
  ('guzmania-lingulata', 'Stella scarlatta'),
  ('gynostemma-pentaphyllum', 'Jiogulan'),
  ('gypsophila-repens', 'Gipsofila strisciante'),
  ('haemanthus-albiflos', 'Pennello'),
  ('halesia-carolina', 'Alesia'),
  ('hedysarum-hedysaroides', 'Sulla alpina'),
  ('helenium-autumnale', 'Elenio'),
  ('helianthemum-lunulatum', 'Eliantemo ligure'),
  ('helianthemum-oelandicum', 'Eliantemo rupino'),
  ('helianthus-debilis', 'Girasole nano'),
  ('helianthus-decapetalus', 'Girasole semplice'),
  ('helianthus-pauciflorus', 'Girasole selvatico'),
  ('helianthus-petiolaris', 'Girasole canadese'),
  ('heliopsis-helianthoides', 'Eliopside'),
  ('heliosperma-alpestre', 'Silene alpestre'),
  ('heliosperma-pusillum', 'Silene delle fonti'),
  ('helleborus-multifidus', 'Elleboro d''Istria'),
  ('hesperocallis-undulata', 'Giglio del deserto'),
  ('hieracium-sabaudum', 'Sparviere di Savoia'),
  ('himalayacalamus-falconeri', 'Bambù rosso'),
  ('hippuris-vulgaris', 'Coda di cavallo acquatica'),
  ('hosta-plantaginea', 'Giglio d''agosto'),
  ('hoya-australis', 'Pianta di cera'),
  ('hydrangea-serrata', 'Ortensia seghettata'),
  ('hydrastis-canadensis', 'Idraste'),
  ('hydrilla-verticillata', 'Peste d''acqua'),
  ('hydrocotyle-ranunculoides', 'Soldinella reniforme'),
  ('hydrocotyle-sibthorpioides', 'Soldinella sibtorpioide'),
  ('hyoscyamus-albus', 'Giusquiamo bianco'),
  ('hypericum-aegypticum', 'Iperico egiziano'),
  ('hypericum-elodes', 'Erba di San Giovanni delle torbiere'),
  ('hypericum-hirsutum', 'Erba di San Giovanni irsuta'),
  ('hypericum-pulchrum', 'Erba di San Giovanni occidentale'),
  ('hypericum-tetrapterum', 'Erba di San Giovanni alata'),
  ('iberis-amara', 'Iberide bianca'),
  ('idesia-polycarpa', 'Idesia'),
  ('ilex-crenata', 'Agrifoglio giapponese'),
  ('ilex-pernyi', 'Agrifolio di Perny'),
  ('illicium-anisatum', 'Anice stellato giapponese'),
  ('incarvillea-delavayi', 'Incarvillea'),
  ('indocalamus-tessellatus', 'Bambù a foglia larga'),
  ('ipomoea-nil', 'Campanella del mattino'),
  ('iris-sintenisii', 'Giaggiolo meridionale'),
  ('iris-tectorum', 'Giaggiolo dei tetti'),
  ('irvingia-gabonensis', 'Dica'),
  ('jacobaea-paludosa', 'Senecione palustre'),
  ('juglans-microcarpa', 'Noce a frutti piccoli'),
  ('juncus-compressus', 'Giunco compresso'),
  ('juncus-tenuis', 'Giunco americano'),
  ('juniperus-chinensis', 'Ginepro cinese'),
  ('juniperus-drupacea', 'Ginepro di Siria'),
  ('juniperus-excelsa', 'Ginepro di Grecia'),
  ('juniperus-formosana', 'Ginepro di Formosa'),
  ('juniperus-osteosperma', 'Ginepro'),
  ('juniperus-scopulorum', 'Ginepro delle Montagne Rocciose'),
  ('kadsura-japonica', 'Kadsura'),
  ('kalmia-angustifolia', 'Calmia a foglie strette'),
  ('keteleeria-davidiana', 'Keteleeria di David'),
  ('knautia-macedonica', 'Ambretta della Macedonia'),
  ('kummerowia-stipulacea', 'Lespedeza della Corea'),
  ('lactuca-perennis', 'Lattuga rupestre'),
  ('lactuca-quercina', 'Lattuga saettona'),
  ('lagarosiphon-major', 'Peste d''acqua arcuata'),
  ('lagunaria-patersonia', 'Lagunaria di Paterson'),
  ('larix-laricina', 'Larice americano'),
  ('larix-lyallii', 'Larice subalpino'),
  ('larix-occidentalis', 'Larice occidentale'),
  ('larix-potaninii', 'Larice del Tibet'),
  ('larix-sibirica', 'Larice siberiano'),
  ('laser-trilobum', 'Lasero trilobo'),
  ('lathyrus-niger', 'Cicerchia nera'),
  ('lavandula-viridis', 'Lavanda gialla'),
  ('lemna-gibba', 'Lenticchia d''acqua spugnosa'),
  ('lepidium-virginicum', 'Lepidio della Virginia'),
  ('leptospermum-scoparium', 'Manuka'),
  ('lespedeza-cuneata', 'Lespedeza perenne'),
  ('leucanthemum-heterophyllum', 'Margherita sudalpina'),
  ('leucanthemum-maximum', 'Margherita gigante'),
  ('leycesteria-formosa', 'Leycesteria'),
  ('liatris-spicata', 'Liatride a spighe'),
  ('lilium-regale', 'Giglio reale'),
  ('limonium-bellidifolium', 'Limonio del Caspio'),
  ('linaria-maroccana', 'Linaria marocchina'),
  ('linnaea-borealis', 'Linnea'),
  ('linum-arboreum', 'Lino arborescente'),
  ('linum-grandiflorum', 'Lino scarlatto'),
  ('linum-perenne', 'Lino campestre'),
  ('liriodendron-chinense', 'Liriodendro cinese'),
  ('lithops-karasmontana', 'Pietra vivente'),
  ('littorella-uniflora', 'Littorella'),
  ('lobelia-cardinalis', 'Lobelia rossa'),
  ('lophostemon-confertus', 'Tristania'),
  ('loropetalum-chinense', 'Loropetalo'),
  ('luffa-acutangula', 'Spugna vegetale'),
  ('luffa-cylindrica', 'Luffa da spugna'),
  ('luma-apiculata', 'Mirto luma'),
  ('lunaria-rediviva', 'Lunaria comune'),
  ('lupinus-perennis', 'Lupino perenne'),
  ('luronium-natans', 'Mestolaccia natante'),
  ('lycianthes-rantonnetii', 'Morella di Rantonnet'),
  ('lycopodium-alpinum', 'Licopodio alpino'),
  ('lycoris-radiata', 'Giglio ragno rosso'),
  ('lysimachia-thyrsiflora', 'Mazza d''oro tirsiflora'),
  ('lythrum-portula', 'Salcerella erba portula'),
  ('maackia-amurensis', 'Maackia dell''Amur'),
  ('macadamia-integrifolia', 'Noce australiana'),
  ('madia-sativa', 'Madia'),
  ('magnolia-acuminata', 'Magnolia a foglie acuminate'),
  ('magnolia-campbellii', 'Magnolia di Campbell'),
  ('magnolia-delavayi', 'Magnolia di Delavay'),
  ('magnolia-macrophylla', 'Magnolia a grandi foglie'),
  ('magnolia-salicifolia', 'Magnolia a foglie di salice'),
  ('magnolia-sargentiana', 'Magnolia di Sargent'),
  ('magnolia-sieboldii', 'Magnolia di Siebold'),
  ('malcolmia-maritima', 'Malcolmia marittima'),
  ('malpighia-glabra', 'Acerola'),
  ('malus-coronaria', 'Melo coronario'),
  ('malus-fusca', 'Melo dell''Oregon'),
  ('malus-halliana', 'Melo di Hall'),
  ('malus-ioensis', 'Melo dell''Iowa'),
  ('malus-prunifolia', 'Melo a foglie di pruno'),
  ('malus-x-floribunda', 'Melo giapponese'),
  ('malva-alcea', 'Malvone roseo'),
  ('malva-moschata', 'Malva moscata'),
  ('malva-nicaeensis', 'Malva scabra'),
  ('malva-verticillata', 'Malva crespa'),
  ('mangifera-indica', 'Mango'),
  ('manilkara-zapota', 'Sapota'),
  ('maranta-arundinacea', 'Maranta'),
  ('mazus-pumilus', 'Mazus nano'),
  ('melianthus-major', 'Melianto maggiore'),
  ('melilotus-elegans', 'Meliloto elegante'),
  ('mentha-cervina', 'Menta cervina'),
  ('mentha-x-villosa', 'Menta pelosa'),
  ('microbiota-decussata', 'Falso cipresso strisciante'),
  ('millettia-laurentii', 'Wengé'),
  ('mimusops-elengi', 'Bakula'),
  ('moneses-uniflora', 'Piroletta soldanina'),
  ('monotropa-uniflora', 'Fiore fantasma'),
  ('morinda-citrifolia', 'Noni'),
  ('moringa-oleifera', 'Moringa'),
  ('musa-basjoo', 'Banano giapponese'),
  ('musa-velutina', 'Banana rosa'),
  ('musanga-cecropioides', 'Parasolero'),
  ('myoporum-insulare', 'Mirioporum delle isole'),
  ('myriophyllum-spicatum', 'Millefoglio d''acqua comune'),
  ('myrtillocactus-geometrizans', 'Mirtillocactus'),
  ('nemophila-menziesii', 'Nemofila'),
  ('nepeta-nuda', 'Gattaia glabra'),
  ('nepeta-tuberosa', 'Gattaia tuberosa'),
  ('nepeta-x-faassenii', 'Gattaia ibrida'),
  ('nephelium-lappaceum', 'Rambutan'),
  ('nerine-undulata', 'Nerina'),
  ('nymphaea-candida', 'Ninfea candida'),
  ('nyssa-sylvatica', 'Nissa silvestre'),
  ('ocimum-gratissimum', 'Basilico cespuglioso'),
  ('ocimum-kilimandscharicum', 'Basilico del Kilimangiaro'),
  ('oenanthe-crocata', 'Finocchio acquatico con foglie di prezzemolo'),
  ('oenanthe-javanica', 'Finocchio acquatico di Giava'),
  ('oenanthe-pimpinelloides', 'Finocchio acquatico comune'),
  ('omphalodes-linifolia', 'Borrana con foglie di lino'),
  ('oncidium-altissimum', 'Orchidea ballerina allungata'),
  ('onopordum-illyricum', 'Onopordo maggiore'),
  ('ophiopogon-jaburan', 'Mughetto giapponese'),
  ('oreocereus-celsianus', 'Vecchio della montagna'),
  ('oreomecon-alpina', 'Papavero alpino'),
  ('origanum-dictamnus', 'Origano di Candia'),
  ('ornithogalum-dubium', 'Ornitogallo'),
  ('ornithogalum-thyrsoides', 'Ornitogalo'),
  ('orobanche-cernua', 'Succiamele ricurvo'),
  ('oscularia-deltoides', 'Fiore di ghiaccio rosa'),
  ('oxalis-pes-caprae', 'Acetosella gialla'),
  ('oxalis-triangularis', 'Acetosella triangolare'),
  ('oxyria-digyna', 'Acetosa soldanella'),
  ('pachyrhizus-erosus', 'Fagiolo patata'),
  ('paeonia-peregrina', 'Peonia pellegrina'),
  ('panax-quinquefolius', 'Ginseng americano'),
  ('pandanus-amaryllifolius', 'Pandano'),
  ('pandorea-jasminoides', 'Pandorea'),
  ('panicum-maximum', 'Erba di Guinea'),
  ('panicum-virgatum', 'Panico vergato'),
  ('papaver-atlanticum', 'Papavero atlantico'),
  ('parodia-magnifica', 'Cuscino di suocera'),
  ('paronychia-argentea', 'Paronichia argentea'),
  ('paronychia-capitata', 'Paronichia capitata'),
  ('parthenium-argentatum', 'Guaiule'),
  ('parthenium-hysterophorus', 'Cicutilla'),
  ('passiflora-incarnata', 'Granadiglia incarnata'),
  ('paullinia-cupana', 'Guaranà'),
  ('pedicularis-sylvatica', 'Pedicolare silvestre'),
  ('pelargonium-capitatum', 'Pelargonio capitato'),
  ('pelargonium-cucullatum', 'Pelargonio cucullato'),
  ('pelargonium-tomentosum', 'Geranio menta'),
  ('pelargonium-x-domesticum', 'Geranio imperiale'),
  ('peltaria-alliacea', 'Peltaria agliacea'),
  ('peltogyne-paniculata', 'Legno amarante'),
  ('pennisetum-setaceum', 'Penniseto allungato'),
  ('pentaglottis-sempervirens', 'Buglossa ovata'),
  ('pentas-lanceolata', 'Stella egiziana'),
  ('peperomia-rotundifolia', 'Peperomia a foglie rotonde'),
  ('pericopsis-elata', 'Afrormosia'),
  ('persicaria-orientalis', 'Poligono orientale'),
  ('petasites-albus', 'Farfaraccio bianco'),
  ('petasites-japonicus', 'Farfaraccio'),
  ('petasites-paradoxus', 'Farfaraccio niveo'),
  ('petiveria-alliacea', 'Anamù'),
  ('petrorhagia-saxifraga', 'Garofanina spaccasassi'),
  ('phalaris-minor', 'Scagliola minore'),
  ('phellodendron-amurense', 'Sughera cinese'),
  ('philodendron-squamiferum', 'Filodendro peloso'),
  ('phlomis-lychnitis', 'Salvione licnite'),
  ('phlomis-russeliana', 'Salvia turca'),
  ('phoenix-roebelenii', 'Palma da datteri nana'),
  ('phoenix-sylvestris', 'Palma da dattero indiana'),
  ('phyllanthus-emblica', 'Amla'),
  ('phyllodoce-caerulea', 'Fillodoce azzurro'),
  ('phyllospadix-scouleri', 'Zostera di Scouler'),
  ('phyllostachys-aureosulcata', 'Bambù aureosulcato'),
  ('phyllostachys-bissetii', 'Bambù di Bisset'),
  ('phyllostachys-flexuosa', 'Bambù flessuoso'),
  ('phyllostachys-sulphurea', 'Bambù sulfureo'),
  ('phyllostachys-vivax', 'Bambù vivace'),
  ('physalis-philadelphica', 'Tomatillo'),
  ('phyteuma-nigrum', 'Raponzolo nero'),
  ('phyteuma-scheuchzeri', 'Raponzolo di Scheuchzer'),
  ('phyteuma-spicatum', 'Raponzolo giallo'),
  ('picea-asperata', 'Abete della Cina'),
  ('picea-brachytyla', 'Abete di Sargent'),
  ('picea-likiangensis', 'Abete di Likiang'),
  ('picea-mariana', 'Abete nero'),
  ('picea-purpurea', 'Peccio purpureo'),
  ('picea-smithiana', 'Abete di Smith'),
  ('picea-wilsonii', 'Abete di Wilson'),
  ('pieris-japonica', 'Andromeda giapponese'),
  ('pinguicula-grandiflora', 'Erba unta con grandi fiori'),
  ('pinus-aristata', 'Pino aristato'),
  ('pinus-ayacahuite', 'Pino bianco del Messico'),
  ('pinus-balfouriana', 'Pino di Balfour'),
  ('pinus-banksiana', 'Pino di Banks'),
  ('pinus-bungeana', 'Pino di Bunge'),
  ('pinus-caribaea', 'Pino dei Caraibi'),
  ('pinus-contorta', 'Pino contorto'),
  ('pinus-coulteri', 'Pino di Coulter'),
  ('pinus-echinata', 'Pino piceiforme'),
  ('pinus-flexilis', 'Pino flessibile'),
  ('pinus-gerardiana', 'Pino di Gerard'),
  ('pinus-koraiensis', 'Pino coreano'),
  ('pinus-lambertiana', 'Pino di Lambert'),
  ('pinus-montezumae', 'Pino di Montezuma'),
  ('pinus-monticola', 'Pino bianco occidentale'),
  ('pinus-muricata', 'Pino muricato'),
  ('pinus-pumila', 'Pino nano siberiano'),
  ('pinus-rigida', 'Pino rigido'),
  ('pinus-roxburghii', 'Pino di Roxburgh'),
  ('pinus-sabiniana', 'Pino di Sabina'),
  ('pinus-tabuliformis', 'Pino della Cina'),
  ('pinus-taeda', 'Pino da incenso'),
  ('pinus-torreyana', 'Pino del Torrey'),
  ('pinus-virginiana', 'Pino della Virginia'),
  ('piper-betle', 'Betel'),
  ('pistacia-chinensis', 'Pistacchio della Cina'),
  ('pittosporum-tenuifolium', 'Pittosporo della Nuova Zelandia'),
  ('pittosporum-undulatum', 'Pitosporo'),
  ('plantago-amplexicaulis', 'Piantaggine calabrese'),
  ('plantago-crassifolia', 'Piantaggine a foglie grasse'),
  ('plantago-rugelii', 'Piantaggine rugeliosa'),
  ('platycerium-bifurcatum', 'Corna d''alce'),
  ('pleioblastus-variegatus', 'Pleioblasto'),
  ('pleiospilos-nelii', 'Sassi viventi'),
  ('plinia-cauliflora', 'Jabuticaba'),
  ('podocarpus-macrophyllus', 'Podocarpo a grandi foglie'),
  ('podocarpus-nubigenus', 'Manio'),
  ('podocarpus-totara', 'Totara'),
  ('podophyllum-peltatum', 'Podofillo comune'),
  ('polygala-amara', 'Poligala amara'),
  ('polygala-calcarea', 'Poligala del calcare'),
  ('polygonum-arenastrum', 'Poligono dei sabbioni'),
  ('polygonum-equisetiforme', 'Poligono equisetiforme'),
  ('polygonum-scoparium', 'Poligono scopario'),
  ('polyscias-fruticosa', 'Poliscia'),
  ('populus-angustifolia', 'Pioppo a foglie strette'),
  ('populus-balsamifera', 'Pioppo balsamico'),
  ('populus-lasiocarpa', 'Pioppo della Cina'),
  ('potentilla-calabra', 'Cinquefoglia di Calabria'),
  ('primula-allionii', 'Primula di Allioni'),
  ('primula-florindae', 'Primula tibetana'),
  ('primula-hirsuta', 'Primula irsuta'),
  ('primula-marginata', 'Primula impolverata'),
  ('primula-palinuri', 'Primula di Palinuro'),
  ('primula-x-polyantha', 'Primula comune'),
  ('proboscidea-louisianica', 'Artiglio del diavolo'),
  ('prumnopitys-andina', 'Podocarpo delle Ande'),
  ('prunus-davidiana', 'Pesco di David'),
  ('prunus-glandulosa', 'Mandorlo ornamentale'),
  ('prunus-ilicifolia', 'Ciliegio a foglie d''agrifoglio'),
  ('prunus-maackii', 'Ciliegio della Manciuria'),
  ('prunus-mandshurica', 'Albicocco della Manciuria'),
  ('prunus-mume', 'Albicocco del Giappone'),
  ('prunus-sargentii', 'Ciliegio di Sargent'),
  ('prunus-serrula', 'Ciliegio del Tibet'),
  ('prunus-sibirica', 'Albicocco siberiano'),
  ('prunus-tenella', 'Mandorlo nano'),
  ('prunus-tomentosa', 'Ciliegio di Nanchino'),
  ('prunus-virginiana', 'Ciliegio della Virginia'),
  ('prunus-x-subhirtella', 'Ciliegio da fiore'),
  ('pseudodictamnus-mediterraneus', 'Cimiciotta greca'),
  ('pteris-cretica', 'Pteride di Creta'),
  ('pterocarya-rhoifolia', 'Pterocaria del Giappone'),
  ('pterocarya-stenoptera', 'Pterocaria della Cina'),
  ('pueraria-montana', 'Kudzu'),
  ('pulicaria-odora', 'Incensaria odorosa'),
  ('pulmonaria-obscura', 'Polmonaria scura'),
  ('pyracantha-crenulata', 'Agazzino crenulato'),
  ('pyrola-chlorantha', 'Piroletta verdastra'),
  ('pyrola-elliptica', 'Pirola americana'),
  ('pyrola-minor', 'Piroletta minore'),
  ('quassia-amara', 'Quassio'),
  ('quercus-acuta', 'Quercia a foglie aguzze'),
  ('quercus-agrifolia', 'Quercia a foglie di agrifolio'),
  ('quercus-aliena', 'Quercia del Giappone a grandi foglie'),
  ('quercus-bicolor', 'Quercia bicolore'),
  ('quercus-dentata', 'Quercia dentata'),
  ('quercus-douglasii', 'Quercia di Douglas'),
  ('quercus-garryana', 'Quercia dell''Oregon'),
  ('quercus-imbricaria', 'Quercia imbricata'),
  ('quercus-infectoria', 'Quercia alle galle'),
  ('quercus-kelloggii', 'Quercia di Kellogg'),
  ('quercus-laurifolia', 'Quercia a foglie di lauro'),
  ('quercus-libani', 'Quercia del Libano'),
  ('quercus-lobata', 'Quercia bianca di California'),
  ('quercus-lyrata', 'Quercia bianca d''America'),
  ('quercus-macranthera', 'Quercia del Caucaso'),
  ('quercus-marilandica', 'Quercia nera americana'),
  ('quercus-mongolica', 'Quercia della Mongolia'),
  ('quercus-muehlenbergii', 'Quercia di Mühlenberg'),
  ('quercus-phellos', 'Quercia a foglie di salice'),
  ('quercus-pontica', 'Quercia pontica'),
  ('quercus-shumardii', 'Quercia di Shumard'),
  ('quercus-variabilis', 'Quercia da sughero della Cina'),
  ('quercus-x-turneri', 'Quercia di Turner'),
  ('ranunculus-gramineus', 'Ranuncolo gramineo'),
  ('ranunculus-montanus', 'Ranuncolo montano'),
  ('ranunculus-reptans', 'Ranuncolo reptante'),
  ('rhamnus-fallax', 'Ramno alpino'),
  ('rhamnus-lycioides', 'Olivello spinoso europeo'),
  ('rhamnus-utilis', 'Ramno utile'),
  ('rhapidophyllum-hystrix', 'Palmetto'),
  ('rheum-rhaponticum', 'Rabarbaro rapontico'),
  ('rhododendron-arborescens', 'Rododendro arborescente'),
  ('rhododendron-arboreum', 'Rododendro arboreo'),
  ('rhododendron-luteum', 'Azalea gialla'),
  ('rhododendron-molle', 'Azalea mollis'),
  ('rhododendron-viscosum', 'Rododendro viscoso'),
  ('rhus-potaninii', 'Sommacco cinese'),
  ('ribes-americanum', 'Ribes americano'),
  ('robinia-neomexicana', 'Robinia del Nuovo Messico'),
  ('romneya-coulteri', 'Papavero della California'),
  ('romulea-bulbocodium', 'Zafferanetto comune'),
  ('rosa-corymbifera', 'Rosa corimbifera'),
  ('rosa-moschata', 'Rosa moscata'),
  ('rosa-multiflora', 'Rosa moltiflora'),
  ('rosa-pendulina', 'Rosa alpina'),
  ('rosa-rugosa', 'Rosa con foglie rugose'),
  ('rosa-serafinii', 'Rosa di Serafini'),
  ('rosa-sherardii', 'Rosa di Sherard'),
  ('rosa-spinosissima', 'Rosa di macchia'),
  ('rotheca-myricoides', 'Clerodendro ugandese'),
  ('rubia-peregrina', 'Robbia selvatica'),
  ('rubus-argutus', 'Mora a dente di sega'),
  ('rubus-bifrons', 'Rovo bicolore'),
  ('rubus-laciniatus', 'Rovo con foglie pennatopartite'),
  ('rubus-odoratus', 'Rovo odorato'),
  ('rubus-sulcatus', 'Rovo solcato'),
  ('rudbeckia-laciniata', 'Rudbeckia comune'),
  ('rumex-dentatus', 'Romice dentato'),
  ('rumex-longifolius', 'Romice a foglie lunghe'),
  ('rumex-nepalensis', 'Romice del Nepal'),
  ('rumex-vesicarius', 'Romice vescicario'),
  ('rumohra-adiantiformis', 'Felce cuoio'),
  ('ruscus-hypophyllum', 'Ruscolo maggiore'),
  ('salix-alpina', 'Salice peloso'),
  ('salix-appendiculata', 'Salice stipolato'),
  ('salix-hastata', 'Salice astato'),
  ('salix-herbacea', 'Salice erbaceo'),
  ('salix-lanata', 'Salice lanoso'),
  ('salix-myrtilloides', 'Salice mirtilloide'),
  ('salix-nigra', 'Salice nero d''America'),
  ('salix-retusa', 'Salice retuso'),
  ('salvia-hispanica', 'Chia'),
  ('salvia-leucantha', 'Salvia a fiori bianchi'),
  ('salvia-patens', 'Salvia dai fiori viola'),
  ('salvia-viridis', 'Salvia annuale'),
  ('salvinia-auriculata', 'Erba pesce americana'),
  ('salvinia-molesta', 'Erba pesce gigante'),
  ('sanguisorba-dodecandra', 'Salvastrella Orobica'),
  ('santolina-etrusca', 'Crespolina etrusca'),
  ('santolina-pinnata', 'Crespolina apuana'),
  ('sarcococca-confusa', 'Bosso di Natale'),
  ('sarracenia-leucophylla', 'Pianta brocca'),
  ('sarracenia-purpurea', 'Sarracenia porporina'),
  ('sasa-veitchii', 'Bambù nano'),
  ('satureja-thymbra', 'Santoreggia sarda'),
  ('saururus-cernuus', 'Coda di lucertola'),
  ('saxifraga-bryoides', 'Sassifraga brioide'),
  ('saxifraga-callosa', 'Sassifraga meridionale'),
  ('saxifraga-cochlearis', 'Sassifraga spatolata'),
  ('saxifraga-exarata', 'Sassifraga solcata'),
  ('saxifraga-granulata', 'Sassifraga granulosa'),
  ('saxifraga-marginata', 'Sassifraga marginata'),
  ('saxifraga-oppositifolia', 'Sassifraga a foglie opposte'),
  ('saxifraga-retusa', 'Sassifraga retusa'),
  ('saxifraga-rosacea', 'Sassifraga rosacea'),
  ('saxifraga-stolonifera', 'Sassifraga stolonifera'),
  ('saxifraga-umbrosa', 'Sassifraga ombrosa'),
  ('sciadopitys-verticillata', 'Pino a ombrelli'),
  ('scilla-forbesii', 'Gloria delle nevi di Forbes'),
  ('scilla-litardierei', 'Scilla di Litardière'),
  ('scilla-peruviana', 'Scilla maggiore'),
  ('scilla-siberica', 'Scilla siberiana'),
  ('scirpus-sylvaticus', 'Lisca dei prati'),
  ('scolymus-grandiflorus', 'Cardogna maggiore'),
  ('scoparia-dulcis', 'Scopa dolce'),
  ('scorpiurus-vermiculatus', 'Erba lombrica uniflora'),
  ('scutellaria-altissima', 'Scutellaria maggiore'),
  ('secale-strictum', 'Segale selvatico'),
  ('sedum-brevifolium', 'Borracina di Corsica'),
  ('sedum-dendroideum', 'Foglie di giada'),
  ('sedum-forsterianum', 'Borracina di Forster'),
  ('sedum-hispanicum', 'Borracina glauca'),
  ('sedum-x-rubrotinctum', 'Pianta delle perle di giada'),
  ('sempervivum-arachnoideum', 'Semprevivo ragnateloso'),
  ('senecio-sylvaticus', 'Senecione delle selve'),
  ('senna-alata', 'Cassia alata'),
  ('senna-corymbosa', 'Senna corimbosa'),
  ('senna-tora', 'Cassia selvatica'),
  ('silaum-silaus', 'Silao'),
  ('silene-acaulis', 'Silene a cuscinetto'),
  ('silene-chalcedonica', 'Crotonella scarlatta'),
  ('silene-conoidea', 'Silene conoide'),
  ('silene-flos-jovis', 'Crotonella fior di Giove'),
  ('silene-gallica', 'Mazzettino'),
  ('silene-nutans', 'Silene ciondola'),
  ('smallanthus-sonchifolius', 'Yacon'),
  ('smilax-rotundifolia', 'Salsapariglia rotonda'),
  ('solanum-aethiopicum', 'Melanzana rossa di Rotonda'),
  ('solanum-bonariense', 'Morella di Buenos Aires'),
  ('solidago-nemoralis', 'Verga d''oro dei boschi'),
  ('sorbaria-tomentosa', 'Sorbaria'),
  ('sorbus-americana', 'Sorbo americano'),
  ('sorbus-cashmiriana', 'Sorbo del Kashmir'),
  ('sorbus-commixta', 'Sorbo giapponese'),
  ('sorbus-hupehensis', 'Sorbo dell''Hupeh'),
  ('spiraea-x-pseudosalicifolia', 'Spirea a foglie di salice'),
  ('sprekelia-formosissima', 'Sprekelia'),
  ('stachys-affinis', 'Tuberina'),
  ('staphylea-colchica', 'Stafilea della Colchide'),
  ('stellaria-alsine', 'Centocchio dei rivi'),
  ('stellaria-graminea', 'Centocchio gramignola'),
  ('stevia-rebaudiana', 'Stevia'),
  ('stewartia-sinensis', 'Stewartia cinese'),
  ('strelitzia-nicolai', 'Uccello del paradiso'),
  ('streptocarpus-ionanthus', 'Violetta africana'),
  ('streptocarpus-saxorum', 'Primula del Capo'),
  ('styrax-japonicus', 'Storace giapponese'),
  ('styrax-obassia', 'Storace a grandi foglie'),
  ('succisella-inflexa', 'Vedovina rizomatosa'),
  ('swietenia-macrophylla', 'Mogano americano'),
  ('symphyotrichum-ericoides', 'Settembrino bianco'),
  ('symphyotrichum-novae-angliae', 'Astro del New England'),
  ('symphyotrichum-pilosum', 'Astro peloso'),
  ('symphytum-orientale', 'Consolida orientale'),
  ('symphytum-x-uplandicum', 'Consolida tedesca'),
  ('syringa-josikaea', 'Lilla d''Ungheria'),
  ('syringa-reticulata', 'Lillà giapponese'),
  ('syringa-villosa', 'Lilla'),
  ('tagetes-minuta', 'Tagete puzzolente'),
  ('taiwania-cryptomerioides', 'Cedro di Taiwan'),
  ('tamarindus-indica', 'Tamarindo'),
  ('tamarix-aphylla', 'Tamarice'),
  ('tamarix-chinensis', 'Tamerice cinese'),
  ('tanacetum-cinerariifolium', 'Piretro della Dalmazia'),
  ('taraxacum-megalorrhizon', 'Tarassaco a radice grossa'),
  ('taraxacum-palustre', 'Tarassaco delle paludi'),
  ('taxus-canadensis', 'Tasso del Canadà'),
  ('terminalia-chebula', 'Mirobolano'),
  ('terminalia-superba', 'Limba'),
  ('tetradium-daniellii', 'Albero del miele'),
  ('tetragonia-tetragonioides', 'Spinacio di Nuova Zelanda'),
  ('thalictrum-alpinum', 'Pigamo alpino'),
  ('thalictrum-lucidum', 'Pigamo lucido'),
  ('thalictrum-minus', 'Pigamo minore'),
  ('thapsia-garganica', 'Firrastrina comune'),
  ('thuja-koraiensis', 'Tuia della Corea'),
  ('thujopsis-dolabrata', 'Hiba'),
  ('thunbergia-grandiflora', 'Trombetta blu'),
  ('thymus-herba-barona', 'Timo erba barona'),
  ('thymus-mastichina', 'Timo tomentoso'),
  ('thymus-polytrichus', 'Timo a peli variabili'),
  ('thymus-praecox', 'Timo precoce'),
  ('tigridia-pavonia', 'Fior di tigre messicano'),
  ('tilia-amurensis', 'Tiglio dell''Amur'),
  ('tilia-mongolica', 'Tiglio della Mongolia'),
  ('tillandsia-aeranthos', 'Pianta dell''aria'),
  ('tithonia-rotundifolia', 'Girasole messicano'),
  ('tordylium-apulum', 'Ombrellini pugliesi'),
  ('toxicodendron-vernicifluum', 'Lacca giapponese'),
  ('tricyrtis-hirta', 'Giglio del rospo'),
  ('trifolium-rubens', 'Trifoglio rosseggiante'),
  ('trillium-erectum', 'Trillio eretto'),
  ('tripolium-pannonicum', 'Astro marino'),
  ('tsuga-caroliniana', 'Tsuga della Carolina'),
  ('tsuga-chinensis', 'Tsuga della Cina'),
  ('tuberaria-guttata', 'Fior gallinaccio comune'),
  ('tuberaria-lignosa', 'Fior gallinaccio maggiore'),
  ('tulipa-cretica', 'Tulipano cretese'),
  ('tulipa-saxatilis', 'Tulipano dei sassi'),
  ('turritis-glabra', 'Arabetta glabrescente'),
  ('ulex-parviflorus', 'Ginestrone a fiori piccoli'),
  ('ulmus-americana', 'Olmo americano'),
  ('ulmus-rubra', 'Olmo rosso'),
  ('ulmus-thomasii', 'Olmo di Thomas'),
  ('vaccinium-arboreum', 'Mirtillo arboreo'),
  ('vaccinium-corymbosum', 'Mirtillo americano'),
  ('vachellia-seyal', 'Acacia seyal'),
  ('vachellia-tortilis', 'Acacia ad ombrello'),
  ('valeriana-celtica', 'Nardo celtico'),
  ('valeriana-dioica', 'Valeriana palustre'),
  ('valeriana-pyrenaica', 'Valeriana dei Pirenei'),
  ('vallisneria-americana', 'Vallisneria'),
  ('vanda-coerulea', 'Vanda cerulea'),
  ('veratrum-viride', 'Veratro verde'),
  ('verbascum-chaixii', 'Verbasco di Chaix'),
  ('verbascum-lychnitis', 'Verbasco licnite'),
  ('verbascum-phoeniceum', 'Verbasco porporino'),
  ('veronica-allionii', 'Veronica di Allioni'),
  ('veronica-austriaca', 'Veronica d''Austria'),
  ('veronica-fruticulosa', 'Veronica rosea'),
  ('veronica-prostrata', 'Veronica sdraiata'),
  ('veronica-repens', 'Veronica strisciante'),
  ('veronica-scutellata', 'Veronica delle paludi'),
  ('veronica-spicata', 'Veronica spigata'),
  ('vetiveria-zizanioides', 'Vetiver'),
  ('viburnum-lentago', 'Lentaggine'),
  ('viburnum-x-rhytidophylloides', 'Viburno dalle foglie rugose'),
  ('vicia-monantha', 'Veccia uniflora'),
  ('vicia-sylvatica', 'Veccia silvana'),
  ('vigna-angularis', 'Fagiolo adzuki'),
  ('vigna-mungo', 'Fagiolo urd'),
  ('vigna-radiata', 'Fagiolo mungo'),
  ('vinca-difformis', 'Pervinca ovata'),
  ('viola-canina', 'Viola selvatica'),
  ('viola-collina', 'Viola dei colli'),
  ('viola-cucullata', 'Viola degli orti'),
  ('viola-elatior', 'Viola maggiore'),
  ('viola-lutea', 'Viola gialla'),
  ('viola-mirabilis', 'Viola mirabile'),
  ('viola-pinnata', 'Viola pennata'),
  ('viola-reichenbachiana', 'Viola silvestre'),
  ('viola-riviniana', 'Viola di Rivinus'),
  ('viscaria-alpina', 'Crotonella alpina'),
  ('vitis-aestivalis', 'Uva volpina'),
  ('vitis-rotundifolia', 'Vite a foglie rotonde'),
  ('vitis-vulpina', 'Vite volpina'),
  ('waldsteinia-geoides', 'Waldsteinia con foglie di cariofillata'),
  ('waldsteinia-ternata', 'Waldsteinia trifogliata'),
  ('westringia-fruticosa', 'Falso rosmarino'),
  ('woodsia-alpina', 'Felcetta alpina'),
  ('youngia-japonica', 'Cicorietta'),
  ('zantedeschia-rehmannii', 'Calla'),
  ('zanthoxylum-bungeanum', 'Falso pepe di Sichuan'),
  ('zelkova-sicula', 'Zelkova siciliana'),
  ('zephyranthes-candida', 'Giglio bianco della pioggia'),
  ('zoysia-japonica', 'Zoisia del Giappone')
) as v(slug, nome)
where s.slug = v.slug
  and s.nome = s.nome_scientifico
  and s.specie_padre_id is null;
