-- Fase 3 (#120), quinto blocco (17/50, ultimo delle specie usate da piante
-- reali): fiori da bordura, perenni e bulbose rimaste.
--
-- Caso limite come marsilea-quadrifolia: salcerella (Lythrum salicaria) è
-- una pianta di zone umide, irrigazione_fattore 1.3 (più acqua, non meno).
--
-- gaura non aveva "alert" nella fonte: compilato insieme al resto (#132).

update specie set famiglia_botanica = $t$Asteraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asteraceae", "giorni_germinazione": "10-15", "giorni_trapianto": "30-40", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "bassa", "spaziatura_cm": 40, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$margherita-delle-canarie$t$;
update specie set famiglia_botanica = $t$Asteraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asteraceae", "giorni_germinazione": "10-15", "giorni_trapianto": "30", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "bassa", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$osteospermum$t$;
update specie set famiglia_botanica = $t$Verbenaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Verbenaceae", "giorni_germinazione": "14-21", "giorni_trapianto": "30-40", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "bassa", "spaziatura_cm": 25, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$verbena$t$;
update specie set famiglia_botanica = $t$Asteraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asteraceae", "giorni_germinazione": "14-21", "giorni_trapianto": "40-60", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 40, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.4}$j$::jsonb where slug = $t$centaurea-ragusina$t$;
update specie set famiglia_botanica = $t$Brassicaceae$t$, ciclo_vitale = $t$biennale$t$, ciclo_colturale = $j${"famiglia_botanica": "Brassicaceae", "giorni_germinazione": "10-15", "giorni_trapianto": "30-40", "giorni_raccolta": null, "finestra_semina": ["estate"], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 25, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$violaciocca$t$;
update specie set famiglia_botanica = $t$Lythraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Lythraceae", "giorni_germinazione": "14-21", "giorni_trapianto": "30-40", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "bassa", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$cuphea$t$;
update specie set famiglia_botanica = $t$Onagraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Onagraceae", "giorni_germinazione": "14-21", "giorni_trapianto": "40-60", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "media", "spaziatura_cm": 40, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.5}$j$::jsonb, alert = ARRAY[$t$Radice a fittone profonda: si adatta male a trapianti ripetuti da adulta$t$, $t$Molto tollerante alla siccità una volta ambientata$t$, $t$Portamento leggero, può piegarsi col vento: valutare un tutore$t$, $t$Fiorisce da primavera fino ad autunno inoltrato$t$] where slug = $t$gaura$t$;
update specie set famiglia_botanica = $t$Geraniaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Geraniaceae", "giorni_germinazione": "7-14", "giorni_trapianto": "40-50", "giorni_raccolta": null, "finestra_semina": ["inverno", "primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 12, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$geranio-parigino$t$;
update specie set famiglia_botanica = $t$Asteraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asteraceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "bassa", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.6}$j$::jsonb where slug = $t$cosmos-atrosanguineus$t$;
update specie set famiglia_botanica = $t$Solanaceae$t$, ciclo_vitale = $t$annuale$t$, ciclo_colturale = $j${"famiglia_botanica": "Solanaceae", "giorni_germinazione": "10-15", "giorni_trapianto": "30", "giorni_raccolta": null, "finestra_semina": ["inverno", "primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$calibrachoa$t$;
update specie set famiglia_botanica = $t$Asteraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asteraceae", "giorni_germinazione": "10-20", "giorni_trapianto": "30-40", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "alta", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.6}$j$::jsonb where slug = $t$coreopsis$t$;
update specie set famiglia_botanica = $t$Asteraceae$t$, ciclo_vitale = $t$annuale$t$, ciclo_colturale = $j${"famiglia_botanica": "Asteraceae", "giorni_germinazione": "5-10", "giorni_trapianto": "20-25", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$zinnia-angustifolia$t$;
update specie set famiglia_botanica = $t$Asteraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asteraceae", "giorni_germinazione": "10-20", "giorni_trapianto": "40-50", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "bassa", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 18, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$gerbera$t$;
update specie set famiglia_botanica = $t$Amaryllidaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Amaryllidaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 10, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.6}$j$::jsonb where slug = $t$allium-sphaerocephalon$t$;
update specie set famiglia_botanica = $t$Asparagaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asparagaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 8, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.6}$j$::jsonb where slug = $t$uva-di-gatto$t$;
update specie set famiglia_botanica = $t$Rosaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Rosaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 300, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 30, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$prunus-taoflora$t$;
update specie set famiglia_botanica = $t$Lythraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Lythraceae", "giorni_germinazione": "14-21", "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "alta", "spaziatura_cm": 40, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 8, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 1.3}$j$::jsonb where slug = $t$salcerella$t$;
