-- Rollback: update specie set nome = nome_scientifico where slug in (<gli slug di questa migration>);
-- (l'SQL esatto di rollback e' in scripts/nomi-italiani/out/rollback_lotto1.sql)
-- Omonimi saltati (13), per nome scientifico: Acacia dealbata, Aquilegia vulgaris, Brassica oleracea, Calendula officinalis, Camellia japonica, Helleborus niger, Hyacinthus orientalis, Lythrum salicaria, Passiflora caerulea, Primula vulgaris, Solanum tuberosum, Thymus serpyllum, Zea mays.
-- Slug esclusi dopo la revisione (nomi sbagliati o dubbi): 25.
-- Nomi italiani (lotto1): sostituisce nome con il nome comune italiano da Wikidata.
-- Solo righe ancora senza nome italiano (nome = nome_scientifico) e non cultivar.
update specie s set nome = v.nome
from (values
  ('abies-alba', 'Abete bianco'),
  ('abies-nordmanniana', 'Abete del Caucaso'),
  ('abutilon-theophrasti', 'Cencio molle'),
  ('acalypha-australis', 'Acalifa asiatica'),
  ('acanthus', 'Acanto'),
  ('acanthus-mollis', 'Acanto'),
  ('acer-negundo', 'Acero americano'),
  ('acer-platanoides', 'Acero riccio'),
  ('acer-saccharinum', 'Acero saccarino'),
  ('achillea-macrophylla', 'Millefoglio delle radure'),
  ('aconitum', 'Aconito'),
  ('adansonia-digitata', 'Baobab'),
  ('adonis-aestivalis', 'Adonide estiva'),
  ('adonis-vernalis', 'Adonide primaverile'),
  ('agave-sisalana', 'Sisal'),
  ('agrimonia-eupatoria', 'Agrimonio'),
  ('agrostemma-githago', 'Gittaione'),
  ('ailanthus-altissima', 'Ailanto'),
  ('alchemilla-vulgaris', 'Erba ventaglina'),
  ('allium-ursinum', 'Aglio orsino'),
  ('alnus', 'Ontano'),
  ('alnus-cordata', 'Ontano napoletano'),
  ('alnus-glutinosa', 'Ontano nero'),
  ('alnus-incana', 'Ontano bianco'),
  ('amaranthus', 'Amaranto'),
  ('amelanchier-ovalis', 'Pero corvino'),
  ('anacamptis-pyramidalis', 'Orchidea piramidale'),
  ('anagallis-arvensis', 'Mordigallina'),
  ('anemone-nemorosa', 'Anemone dei boschi'),
  ('anemone-ranunculoides', 'Anemone giallo'),
  ('annona-cherimola', 'Cirimoia'),
  ('anthyllis-vulneraria', 'Antillide vulneraria'),
  ('antirrhinum-majus', 'Bocca di leone comune'),
  ('aquilegia-atrata', 'Aquilegia scura'),
  ('arabidopsis-thaliana', 'Arabetta Comune'),
  ('araucaria-heterophylla', 'Abete di Norfolk'),
  ('armeria', 'Spillone'),
  ('artemisia-abrotanum', 'Abrotano'),
  ('artemisia-annua', 'Artemisia annuale'),
  ('artemisia-dracunculus', 'Dragoncello o estragone'),
  ('aspidosperma-quebracho-blanco', 'Quebracho bianco'),
  ('aster-alpinus', 'Astro alpino'),
  ('astrantia', 'Astranzia'),
  ('astrantia-major', 'Astranzia maggiore'),
  ('atriplex-hortensis', 'Atriplice degli orti'),
  ('atropa-bella-donna', 'Belladonna'),
  ('avena-sativa', 'Avena comune'),
  ('ballota-nigra', 'Marrubio selvatico'),
  ('berberis-vulgaris', 'Crespino comune'),
  ('betula', 'Betulla'),
  ('betula-pendula', 'Betulla'),
  ('bidens-frondosa', 'Forbicina peduncolata'),
  ('bromus-sterilis', 'Bromo sterile'),
  ('buphthalmum-salicifolium', 'Asteroide salicina'),
  ('calendula-arvensis', 'Fiorrancio selvatico'),
  ('caltha-palustris', 'Calta palustre'),
  ('calypso-bulbosa', 'Calipso'),
  ('camellia-sinensis', 'Albero del tè'),
  ('campanula-bononiensis', 'Campanula bolognese'),
  ('capparis-spinosa', 'Cappero'),
  ('carlina-vulgaris', 'Carlina comune'),
  ('carpinus', 'Càrpino'),
  ('carpinus-betulus', 'Carpino bianco'),
  ('carthamus-tinctorius', 'Cartamo o zafferanone'),
  ('castanea', 'Castagno'),
  ('catananche-caerulea', 'Cupidone azzurro'),
  ('cedrus-atlantica', 'Cedro dell''Atlante'),
  ('cedrus-deodara', 'Cedro dell''Himalaya'),
  ('cedrus-libani', 'Cedro del Libano'),
  ('ceiba-pentandra', 'Albero del kapok'),
  ('celtis-australis', 'Bagolaro'),
  ('centaurea-cyanus', 'Fiordaliso'),
  ('centaurea-jacea', 'Fiordaliso stoppione'),
  ('centaurea-scabiosa', 'Fiordaliso vedovino'),
  ('cerastium-arvense', 'Peverina dei campi'),
  ('ceratonia-siliqua', 'Carrubo'),
  ('ceratophyllum-demersum', 'Ceratofillo'),
  ('chelidonium-majus', 'Celidonia'),
  ('chenopodium-album', 'Farinello comune'),
  ('chenopodium-quinoa', 'Quinoa'),
  ('chenopodium-rubrum', 'Chenopodio rosso'),
  ('chrysosplenium-alternifolium', 'Erba-milza comune'),
  ('cicerbita-alpina', 'Cicerbita violetta'),
  ('cinnamomum-camphora', 'Albero della canfora'),
  ('cirsium-heterophyllum', 'Cardo tagliente'),
  ('cistus', 'Cisto'),
  ('citrus-medica', 'Cedro'),
  ('citrus-x-limon', 'Limone'),
  ('clematis-alpina', 'Clematide alpina'),
  ('clematis-vitalba', 'Vitalba'),
  ('cocos-nucifera', 'Palma da cocco'),
  ('colchicum', 'Colchico'),
  ('colutea-arborescens', 'Vescicaria'),
  ('convolvulus-arvensis', 'Convolvolo'),
  ('cornus-mas', 'Corniolo'),
  ('corylus-avellana', 'Nocciolo'),
  ('crataegus-laevigata', 'Biancospino'),
  ('crithmum-maritimum', 'Finocchio marino'),
  ('crocus', 'Croco'),
  ('crocus-sativus', 'Zafferano vero'),
  ('cupressus-macrocarpa', 'Cipresso di Monterey'),
  ('cupressus-sempervirens', 'Cipresso'),
  ('curcuma-longa', 'Curcuma'),
  ('cynara-scolymus', 'Carciofo'),
  ('cyperus-esculentus', 'Zigolo dolce'),
  ('cyperus-papyrus', 'Papiro egiziano'),
  ('cypripedium-calceolus', 'Scarpetta di Venere'),
  ('cytisus-scoparius', 'Ginestra dei carbonai'),
  ('dactylorhiza-fuchsii', 'Orchide di Fuchs'),
  ('dactylorhiza-incarnata', 'Orchide incarnata'),
  ('dactylorhiza-sambucina', 'Orchide sambucina'),
  ('dactylorhiza-viridis', 'Celoglosso verde'),
  ('daphne-cneorum', 'Cneoro'),
  ('daphne-petraea', 'Dafne minore'),
  ('digitalis', 'Digitale'),
  ('digitalis-grandiflora', 'Digitale gialla grande'),
  ('dionaea-muscipula', 'Dionea'),
  ('doronicum', 'Doronico'),
  ('echinocactus-grusonii', 'Cuscino della Suocera'),
  ('echinops-exaltatus', 'Cardo-pallottola semplice'),
  ('echium', 'Echio'),
  ('echium-vulgare', 'Erba viperina'),
  ('epilobium-palustre', 'Epilobio palustre'),
  ('epipactis-helleborine', 'Elleborina comune'),
  ('equisetum-arvense', 'Coda cavallina dei campi'),
  ('erodium-cicutarium', 'Erba cicutaria'),
  ('erythronium-dens-canis', 'Dente di cane'),
  ('euphorbia', 'Euforbia'),
  ('euphorbia-amygdaloides', 'Euforbia delle Faggete'),
  ('euphorbia-cyparissias', 'Euforbia cipressina'),
  ('euphorbia-paralias', 'Euforbia marittima'),
  ('euphorbia-peplus', 'Euforbia minore'),
  ('fagopyrum-esculentum', 'Grano Saraceno'),
  ('fagus-sylvatica', 'Faggio'),
  ('ferula-communis', 'Finocchiaccio'),
  ('ficaria-verna', 'Ranuncolo favagello'),
  ('ficus-benghalensis', 'Banyan'),
  ('ficus-elastica', 'Albero della gomma'),
  ('filipendula-ulmaria', 'Olmaria'),
  ('fragaria-vesca', 'Fragola di bosco'),
  ('frangula-alnus', 'Frangola'),
  ('fraxinus-americana', 'Frassino bianco americano'),
  ('fraxinus-excelsior', 'Frassino maggiore'),
  ('freesia', 'Fresia'),
  ('fumaria-officinalis', 'Fumaria officinale'),
  ('galanthus-nivalis', 'Bucaneve'),
  ('galeopsis-ladanum', 'Gallinaccia'),
  ('galinsoga-parviflora', 'Galinsoga comune'),
  ('galium-mollugo', 'Caglio tirolese'),
  ('gentiana', 'Genziana'),
  ('gentiana-lutea', 'Genziana maggiore'),
  ('gentiana-verna', 'Genzianella di primavera'),
  ('geranium-palustre', 'Geranio palustre'),
  ('geranium-robertianum', 'Erba Roberta'),
  ('geranium-sanguineum', 'Geranio sanguigno'),
  ('geranium-tuberosum', 'Geranio tuberoso'),
  ('gladiolus', 'Gladiolo'),
  ('gleditsia-triacanthos', 'Spino di Giuda'),
  ('goodyera-repens', 'Godiera'),
  ('gymnadenia-conopsea', 'Manina rosea'),
  ('helichrysum-italicum', 'Elicriso'),
  ('helleborus-foetidus', 'Elleboro puzzolente'),
  ('helleborus-viridis', 'Elleboro verde'),
  ('hevea-brasiliensis', 'Albero della gomma'),
  ('hippocrepis-comosa', 'Sferracavallo comune'),
  ('hovenia-dulcis', 'Albero dell''uva passa'),
  ('humulus-lupulus', 'Luppolo'),
  ('hylotelephium-telephium', 'Borracina maggiore'),
  ('hyoscyamus-niger', 'Giusquiamo nero'),
  ('hypericum', 'Iperico'),
  ('hypericum-calycinum', 'Iperico calicino'),
  ('inula-conyzae', 'Enula baccherina'),
  ('iris-tuberosa', 'Bellavedova'),
  ('jacobaea-maritima', 'Senecione cinerario'),
  ('juglans-nigra', 'Noce nero'),
  ('juniperus-sabina', 'Ginepro sabina'),
  ('juniperus-virginiana', 'Ginepro della Virginia'),
  ('lamium-album', 'Falsa ortica bianca'),
  ('lamium-galeobdolon', 'Falsa ortica gialla'),
  ('lamium-purpureum', 'Làmio porporino'),
  ('larix-decidua', 'Larice comune'),
  ('lathyrus-aphaca', 'Afaca'),
  ('lathyrus-vernus', 'Cicerchia primaticcia'),
  ('leucanthemella-serotina', 'Leucantemella tardiva'),
  ('lilium-martagon', 'Giglio martagone'),
  ('linaria-vulgaris', 'Linaria volgare'),
  ('liriodendron-tulipifera', 'Albero dei tulipani'),
  ('lonicera-caprifolium', 'Caprifoglio comune'),
  ('lupinus', 'Lupino'),
  ('maclura-pomifera', 'Spino degli Osagi'),
  ('magnolia-obovata', 'Magnolia giapponese'),
  ('manihot-esculenta', 'Manioca'),
  ('marrubium-vulgare', 'Marrubio'),
  ('melilotus-officinalis', 'Meliloto'),
  ('melittis-melissophyllum', 'Erba limona comune'),
  ('mentha-aquatica', 'Menta acquatica'),
  ('menyanthes-trifoliata', 'Trifoglio d''acqua'),
  ('mespilus-germanica', 'Nespolo comune'),
  ('mirabilis-jalapa', 'Bella di Notte'),
  ('morus-alba', 'Gelso bianco'),
  ('morus-nigra', 'Moro'),
  ('nepenthes', 'Nepente'),
  ('nuphar-lutea', 'Nannufero'),
  ('nymphaea', 'Ninfea'),
  ('nymphaea-alba', 'Ninfea comune'),
  ('nymphoides-peltata', 'Limnantemio'),
  ('oenanthe-aquatica', 'Fellandrio'),
  ('oenothera-biennis', 'Enotera'),
  ('ononis-spinosa', 'Ononide'),
  ('ophrys-apifera', 'Vesparia'),
  ('ophrys-bertolonii', 'Ofride di Bertoloni'),
  ('ophrys-bombyliflora', 'Ofride fior di bombo'),
  ('ophrys-insectifera', 'Moscaria'),
  ('ophrys-scolopax', 'Ofride cornuta'),
  ('ophrys-sphegodes', 'Ofride verde-bruna'),
  ('ophrys-tenthredinifera', 'Ofride fior di Vespa'),
  ('opuntia-ficus-indica', 'Fico d''india'),
  ('orchis-coriophora', 'Orchide cimicina'),
  ('orchis-italica', 'Uomo nudo'),
  ('orchis-militaris', 'Orchide militare'),
  ('ostrya-carpinifolia', 'Carpino nero'),
  ('paeonia', 'Peonia'),
  ('paeonia-officinalis', 'Peonia selvatica'),
  ('papaver-rhoeas', 'Papavero comune'),
  ('parthenocissus-quinquefolia', 'Vite americana'),
  ('philadelphus', 'Filadelfo'),
  ('phoenix-dactylifera', 'Palma da datteri'),
  ('physoplexis-comosa', 'Raponzolo di roccia'),
  ('picea-abies', 'Abete rosso'),
  ('picea-engelmannii', 'Peccio di Engelmann'),
  ('picea-omorika', 'Abete di Serbia'),
  ('picris-hieracioides', 'Aspraggine comune'),
  ('pinus', 'Pino'),
  ('pinus-densiflora', 'Pino rosso del Giappone'),
  ('pinus-halepensis', 'Pino d''Aleppo'),
  ('pinus-nigra', 'Pino nero'),
  ('pinus-parviflora', 'Pino bianco giapponese'),
  ('pinus-pinea', 'Pino da pinoli'),
  ('pinus-strobus', 'Pino strobo'),
  ('pistacia-lentiscus', 'Lentisco'),
  ('plantago-major', 'Piantaggine maggiore'),
  ('platanthera-bifolia', 'Platantera comune'),
  ('platanus-orientalis', 'Platano orientale'),
  ('plumeria-rubra', 'Frangipani rosso'),
  ('populus-alba', 'Pioppo bianco'),
  ('populus-nigra', 'Pioppo nero'),
  ('populus-tremula', 'Pioppo tremulo'),
  ('potamogeton-crispus', 'Brasca increspata'),
  ('potentilla-erecta', 'Cinquefoglia tormentilla'),
  ('potentilla-reptans', 'Cinquefoglia comune'),
  ('primula-elatior', 'Primula maggiore'),
  ('prunella-vulgaris', 'Prunella comune'),
  ('prunus-laurocerasus', 'Lauroceraso'),
  ('prunus-persica', 'Pesco'),
  ('prunus-spinosa', 'Prugnolo'),
  ('pseudolarix-amabilis', 'Pseudolarice'),
  ('pseudotsuga-menziesii', 'Abete di Douglas'),
  ('pterocarya-fraxinifolia', 'Noce del Caucaso'),
  ('pulsatilla-vernalis', 'Anemone primaverile'),
  ('punica-granatum', 'Melograno'),
  ('pyrus-pyraster', 'Perastro'),
  ('quercus', 'Quercia'),
  ('quercus-cerris', 'Cerro'),
  ('quercus-ilex', 'Leccio'),
  ('quercus-pubescens', 'Roverella'),
  ('quercus-robur', 'Farnia'),
  ('quercus-suber', 'Sughera'),
  ('ranunculus', 'Ranuncolo'),
  ('ranunculus-fluitans', 'Ranuncolo fluitante'),
  ('ranunculus-sceleratus', 'Ranuncolo di palude'),
  ('rhamnus-cathartica', 'Spino cervino'),
  ('rheum-palmatum', 'Rabarbaro cinese'),
  ('rhus-coriaria', 'Sommaco'),
  ('ribes-nigrum', 'Ribes nero'),
  ('rubus-idaeus', 'Lampone'),
  ('salix-alba', 'Salice bianco'),
  ('salix-babylonica', 'Salice piangente'),
  ('salix-caprea', 'Salicone'),
  ('salix-viminalis', 'Vinco'),
  ('sambucus', 'Sambuco'),
  ('scleranthus-annuus', 'Centigrani'),
  ('sedum-acre', 'Borracina acre'),
  ('sequoia-sempervirens', 'Sequoia sempreverde'),
  ('sequoiadendron-giganteum', 'Sequoia gigante'),
  ('setaria-italica', 'Panico'),
  ('solanum-dulcamara', 'Dulcamara'),
  ('solanum-nigrum', 'Morella comune'),
  ('soldanella-alpina', 'Soldanella comune'),
  ('sonchus-asper', 'Grespino spinoso'),
  ('sorbus', 'Sorbo'),
  ('sorbus-aria', 'Sorbo montano'),
  ('sorbus-aucuparia', 'Sorbo degli uccellatori'),
  ('sorbus-domestica', 'Sorbo domestico'),
  ('sorbus-intermedia', 'Sorbo intermedio'),
  ('sorbus-torminalis', 'Sorbo ciavardello'),
  ('spiranthes-spiralis', 'Viticcini autunnali'),
  ('stachys-officinalis', 'Erba betonica'),
  ('styphnolobium-japonicum', 'Sofora del Giappone'),
  ('styrax-officinalis', 'Mella bianca'),
  ('swietenia-mahagoni', 'Mogano'),
  ('taxodium-distichum', 'Cipresso di palude'),
  ('taxus-baccata', 'Tasso'),
  ('tectona-grandis', 'Teak'),
  ('telekia-speciosa', 'Telekia maggiore'),
  ('teucrium-fruticans', 'Camedrio femmina'),
  ('teucrium-scordium', 'Camedrio scordio'),
  ('thalictrum-aquilegiifolium', 'Pigamo colombino'),
  ('thuja-occidentalis', 'Tuia occidentale'),
  ('thymus', 'Timo'),
  ('tilia-cordata', 'Tiglio selvatico'),
  ('tilia-platyphyllos', 'Tiglio nostrale'),
  ('trachycarpus-fortunei', 'Palma di Fortune'),
  ('tragopogon-pratensis', 'Barba di becco'),
  ('trifolium', 'Trifoglio'),
  ('triticum-aestivum', 'Frumento tenero'),
  ('tropaeolum-majus', 'Nasturzio'),
  ('typha-latifolia', 'Tifa'),
  ('ulmus', 'Olmo'),
  ('ulmus-glabra', 'Olmo montano'),
  ('ulmus-minor', 'Olmo campestre'),
  ('ulmus-pumila', 'Olmo siberiano'),
  ('urtica-dioica', 'Ortica'),
  ('urtica-urens', 'Ortica annua'),
  ('veratrum-album', 'Veratro'),
  ('veratrum-nigrum', 'Veratro nero'),
  ('viburnum', 'Viburno'),
  ('viburnum-macrocephalum', 'Viburno'),
  ('viburnum-odoratissimum', 'Viburno'),
  ('viburnum-opulus', 'Oppio'),
  ('viburnum-tinus', 'Viburno'),
  ('vicia-faba', 'Fava'),
  ('viola-odorata', 'Viola mammola'),
  ('viscum-album', 'Vischio'),
  ('wasabia-japonica', 'Wasabi'),
  ('zelkova-carpinifolia', 'Olmo del Caucaso'),
  ('ziziphus-jujuba', 'Giuggiolo')
) as v(slug, nome)
where s.slug = v.slug
  and s.nome = s.nome_scientifico
  and s.specie_padre_id is null;
