-- Fase 3 (#120), terzo blocco (17/50 specie rimaste usate da piante reali):
-- succulente meno comuni e alberi da frutto/agrumi. Come nel blocco 2, molte
-- succulente non si propagano da seme in coltivazione amatoriale: lasciato
-- null/vuoto invece di inventare dati senza senso pratico.
--
-- senecio non aveva "alert" nella fonte, passiflora-caerulea non aveva né
-- "alert" né "descrizione": compilati insieme al resto (checklist #132).

update specie set famiglia_botanica = $t$Asparagaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asparagaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "bassa", "spaziatura_cm": 60, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 10, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.2}$j$::jsonb where slug = $t$agave$t$;
update specie set famiglia_botanica = $t$Cactaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Cactaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 36, "irrigazione_fattore": 0.2}$j$::jsonb where slug = $t$ferocactus$t$;
update specie set famiglia_botanica = $t$Crassulaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Crassulaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 15, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.2}$j$::jsonb where slug = $t$sedum-morganianum$t$;
update specie set famiglia_botanica = $t$Asphodelaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asphodelaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 15, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$gasteria$t$;
update specie set famiglia_botanica = $t$Asteraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asteraceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 15, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 18, "irrigazione_fattore": 0.3}$j$::jsonb, alert = ARRAY[$t$Perline/foglie che si afflosciano → sete d'acqua, ma attenzione a non eccedere$t$, $t$Marciume alla base se il vaso non drena bene$t$, $t$Fusti fragili: maneggiare con cura$t$, $t$Ama posizioni luminose ma non sole diretto cocente$t$] where slug = $t$senecio$t$;
update specie set famiglia_botanica = $t$Aizoaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Aizoaceae", "giorni_germinazione": "14-21", "giorni_trapianto": "30", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "media", "spaziatura_cm": 25, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$delosperma$t$;
update specie set famiglia_botanica = $t$Crassulaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Crassulaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "bassa", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$aeonium$t$;
update specie set famiglia_botanica = $t$Cactaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Cactaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 10, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 1, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.2}$j$::jsonb where slug = $t$mammillaria-piumosa$t$;
update specie set famiglia_botanica = $t$Cactaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Cactaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 10, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 1, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.2}$j$::jsonb where slug = $t$mammillaria-allungata$t$;
update specie set famiglia_botanica = $t$Cactaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Cactaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 36, "irrigazione_fattore": 0.2}$j$::jsonb where slug = $t$cactus-ago-di-eva-monstroso$t$;
update specie set famiglia_botanica = $t$Apocynaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Apocynaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": null, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 1, "rinvaso_ogni_mesi": 18, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$ceropegia$t$;
update specie set famiglia_botanica = $t$Rutaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Rutaceae", "giorni_germinazione": "14-21", "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "bassa", "spaziatura_cm": 300, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 30, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$arancio-navel$t$;
update specie set famiglia_botanica = $t$Oleaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Oleaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "media", "spaziatura_cm": 400, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 30, "rinvaso_ogni_mesi": 36, "irrigazione_fattore": 0.5}$j$::jsonb where slug = $t$ulivo$t$;
update specie set famiglia_botanica = $t$Rutaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Rutaceae", "giorni_germinazione": "14-21", "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "media", "spaziatura_cm": 150, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 20, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$mandarino-cinese$t$;
update specie set famiglia_botanica = $t$Aizoaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Aizoaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "bassa", "spaziatura_cm": 40, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$fico-di-mare$t$;
update specie set famiglia_botanica = $t$Passifloraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Passifloraceae", "giorni_germinazione": "20-40", "giorni_trapianto": "60-90", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "media", "spaziatura_cm": 100, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 15, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.8}$j$::jsonb, alert = ARRAY[$t$Crescita molto rapida: richiede un supporto robusto$t$, $t$Può soffrire il freddo sotto i -5/-7°C nella parte aerea, ma spesso ributta dalla base$t$, $t$Attenzione a cocciniglia e ragnetto rosso$t$, $t$Potatura di contenimento a fine inverno$t$], descrizione = $t$Rampicante vigoroso a fioritura estiva vistosa, con frutti arancioni non commestibili (a differenza della Passiflora edulis).$t$ where slug = $t$passiflora-caerulea$t$;
update specie set famiglia_botanica = $t$Plumbaginaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Plumbaginaceae", "giorni_germinazione": "14-21", "giorni_trapianto": "40-60", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "bassa", "spaziatura_cm": 80, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 10, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$plumbago$t$;
