-- Nomi dei generi scelti: generi.nome diventa il nome usato per le cultivar (lotto 11).
-- Colonne: nome_scientifico, nome vecchio (guardia), nome nuovo. Rollback: scripts/nomi-italiani/rollback_generi_nomi_scelti.sql
update generi g set nome = v.nuovo
from (values
  ('Abies', 'Abeti', 'Abete'),
  ('Acer', 'Aceri', 'Acero'),
  ('Aconitum', 'Aconito', 'Aconitum'),
  ('Aesculus', 'Ippocastani', 'Ippocastano'),
  ('Agapanthus', 'Agapanto', 'Agapanthus'),
  ('Allium', 'Agli', 'Allium'),
  ('Amaranthus', 'Amaranti', 'Amaranthus'),
  ('Aquilegia', 'Aquilegie', 'Aquilegia'),
  ('Asparagus', 'Asparagi', 'Asparagus'),
  ('Astrantia', 'Astranzia', 'Astrantia'),
  ('Betula', 'Betulle', 'Betula'),
  ('Camellia', 'Camelie', 'Camelia'),
  ('Campanula', 'Campanule', 'Campanula'),
  ('Capsicum', 'Peperoni e peperoncini', 'Capsicum'),
  ('Carex', 'Carici', 'Carice'),
  ('Castanea', 'Castagni', 'Castanea'),
  ('Centaurea', 'Fiordalisi', 'Fiordaliso'),
  ('Chrysanthemum', 'Crisantemi', 'Crisantemo'),
  ('Cistus', 'Cisto', 'Cistus'),
  ('Clematis', 'Clematidi', 'Clematide'),
  ('Colchicum', 'Colchici', 'Colchicum'),
  ('Cornus', 'Cornioli', 'Cornus'),
  ('Corydalis', 'Colombine', 'Corydalis'),
  ('Crocus', 'Crochi', 'Crocus'),
  ('Cucurbita', 'Zucche', 'Cucurbita'),
  ('Cyclamen', 'Ciclamini', 'Ciclamino'),
  ('Echinops', 'Cardo pallottola', 'Echinops'),
  ('Eryngium', 'Calcatreppole', 'Calcatreppola'),
  ('Eucalyptus', 'Eucalipti', 'Eucalipto'),
  ('Euphorbia', 'Euforbia', 'Euphorbia'),
  ('Fagus', 'Faggi', 'Faggio'),
  ('Fragaria', 'Fragole', 'Fragola'),
  ('Freesia', 'Fresia', 'Freesia'),
  ('Genista', 'Ginestre', 'Genista'),
  ('Gentiana', 'Genziana', 'Gentiana'),
  ('Geranium', 'Gerani', 'Geranio'),
  ('Gladiolus', 'Gladioli', 'Gladiolus'),
  ('Hoya', 'Fiore di cera', 'Hoya'),
  ('Hypericum', 'Iperico', 'Hypericum'),
  ('Ipomoea', 'Ipomee', 'Ipomoea'),
  ('Lathyrus', 'Cicerchie', 'Lathyrus'),
  ('Ligustrum', 'Ligustri', 'Ligustro'),
  ('Lonicera', 'Caprifogli', 'Caprifoglio'),
  ('Lotus', 'Ginestrini', 'Ginestrino'),
  ('Lupinus', 'Lupini', 'Lupinus'),
  ('Malus', 'Meli', 'Melo'),
  ('Narcissus', 'Narcisi', 'Narciso'),
  ('Nicotiana', 'Tabacco', 'Nicotiana'),
  ('Nymphaea', 'Ninfee', 'Nymphaea'),
  ('Opuntia', 'Opunzie', 'Opunzia'),
  ('Oxalis', 'Ossalidi', 'Ossalide'),
  ('Paeonia', 'Peonia', 'Paeonia'),
  ('Papaver', 'Papaveri', 'Papavero'),
  ('Parthenocissus', 'Viti del Canadà', 'Parthenocissus'),
  ('Phalaenopsis', 'Falenopside', 'Phalaenopsis'),
  ('Pinus', 'Pini', 'Pinus'),
  ('Platanus', 'Platani', 'Platano'),
  ('Potentilla', 'Cinquefoglie', 'Cinquefoglia'),
  ('Primula', 'Primule', 'Primula'),
  ('Prunus', 'Pruni', 'Prunus'),
  ('Quercus', 'Querce', 'Quercus'),
  ('Ranunculus', 'Ranuncoli', 'Ranunculus'),
  ('Rhododendron', 'Rododendri', 'Rododendro'),
  ('Rosa', 'Rose', 'Rosa'),
  ('Rubus', 'Rovo', 'Rubus'),
  ('Salix', 'Salici', 'Salice'),
  ('Salvia', 'Salvie', 'Salvia'),
  ('Sambucus', 'Sambuchi', 'Sambucus'),
  ('Saxifraga', 'Sassifraghe', 'Sassifraga'),
  ('Soldanella', 'Soldanelle', 'Soldanella'),
  ('Sorbus', 'Sorbi', 'Sorbus'),
  ('Symphytum', 'Consolide', 'Symphytum'),
  ('Tagetes', 'Tageti', 'Tagete'),
  ('Tamarix', 'Tamerici', 'Tamerice'),
  ('Thymus', 'Timo', 'Thymus'),
  ('Tilia', 'Tigli', 'Tiglio'),
  ('Trifolium', 'Trifogli', 'Trifolium'),
  ('Tulipa', 'Tulipani', 'Tulipano'),
  ('Ulmus', 'Olmi', 'Ulmus'),
  ('Vaccinium', 'Mirtilli, mirtilli rossi e alleati', 'Vaccinium'),
  ('Veronica', 'Occhi di Maria', 'Veronica'),
  ('Viburnum', 'Viburno', 'Viburnum'),
  ('Vicia', 'Veccie', 'Veccia'),
  ('Viola', 'Viole', 'Viola'),
  ('Vitis', 'Viti', 'Vite')
) as v(nome_scientifico, vecchio, nuovo)
where g.nome_scientifico = v.nome_scientifico and g.nome = v.vecchio;
