-- Fase 3 (#120), quarto blocco (16/50 specie rimaste usate da piante reali):
-- piante d'appartamento, graminacee ornamentali, qualche arbusto/rampicante
-- da esterno.
--
-- Correzioni di contenuto trovate controllando esigenze/alert prima di
-- scrivere (#132): lucky-bamboo aveva esigenze.terreno vuota (coerente,
-- si coltiva in acqua, ma il campo vuoto sembrava un buco — ora lo dice
-- esplicitamente) e nessun alert; pianta-delle-monete e agapanto non
-- avevano descrizione né alert, agapanto aveva anche esigenze.acqua vuota.

update specie set famiglia_botanica = $t$Commelinaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Commelinaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera", "estate"], "resistenza_gelo": "bassa", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 12, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$tradescantia$t$;
update specie set famiglia_botanica = $t$Marantaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Marantaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": null, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 18, "irrigazione_fattore": 0.9}$j$::jsonb where slug = $t$calathea$t$;
update specie set famiglia_botanica = $t$Araceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Araceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": null, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 18, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$anthurium$t$;
update specie set famiglia_botanica = $t$Moraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Moraceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": null, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$ficus-ginseng$t$;
update specie set famiglia_botanica = $t$Asparagaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asparagaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": [], "resistenza_gelo": "nessuna", "spaziatura_cm": null, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 1, "rinvaso_ogni_mesi": null, "irrigazione_fattore": null}$j$::jsonb, alert = ARRAY[$t$Se coltivato in acqua, cambiarla ogni 1-2 settimane per evitare ristagni e alghe$t$, $t$Il cloro dell'acqua di rubinetto può danneggiarlo: meglio acqua decantata o filtrata$t$, $t$Foglie che ingialliscono → eccesso di luce diretta o acqua stagnante$t$, $t$Non è un vero bambù (è una Dracaena): non produce germogli commestibili$t$], esigenze = $j${"luce": "Molta luce, non sole diretto", "acqua": "Coltivato in acqua", "terreno": "Nessuno se coltivato in acqua; substrato drenante se trapiantato in vaso con terra"}$j$::jsonb where slug = $t$lucky-bamboo$t$;
update specie set famiglia_botanica = $t$Acanthaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Acanthaceae", "giorni_germinazione": "14-21", "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 15, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 1, "rinvaso_ogni_mesi": 12, "irrigazione_fattore": 1.0}$j$::jsonb where slug = $t$fittonia$t$;
update specie set famiglia_botanica = $t$Araceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Araceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": null, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$zz-plant$t$;
update specie set famiglia_botanica = $t$Cyperaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Cyperaceae", "giorni_germinazione": "20-30", "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.9}$j$::jsonb where slug = $t$carex$t$;
update specie set famiglia_botanica = $t$Poaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Poaceae", "giorni_germinazione": "14-21", "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "media", "spaziatura_cm": 60, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 10, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$pennisetum-cinese$t$;
update specie set famiglia_botanica = $t$Poaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Poaceae", "giorni_germinazione": "14-21", "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "media", "spaziatura_cm": 40, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.4}$j$::jsonb where slug = $t$stipa-tenuissima$t$;
update specie set famiglia_botanica = $t$Urticaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Urticaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": null, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 12, "irrigazione_fattore": 0.7}$j$::jsonb, alert = ARRAY[$t$Foglie che si arricciano verso il basso → troppa luce diretta o poca acqua$t$, $t$Produce facilmente polloni alla base, ottimi per nuove piante$t$, $t$Ruotare il vaso periodicamente per una crescita simmetrica$t$, $t$Foglie gialle in eccesso → ristagno idrico$t$], descrizione = $t$Pianta d’appartamento dalle foglie tonde e piatte simili a monete, molto facile da propagare per polloni.$t$ where slug = $t$pianta-delle-monete$t$;
update specie set famiglia_botanica = $t$Amaryllidaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Amaryllidaceae", "giorni_germinazione": "30-40", "giorni_trapianto": "60-90", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "media", "spaziatura_cm": 40, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 10, "rinvaso_ogni_mesi": 36, "irrigazione_fattore": 0.7}$j$::jsonb, alert = ARRAY[$t$Fiorisce meglio se leggermente rinvasata (radici compatte)$t$, $t$Teme il gelo intenso: pacciamare la base in inverno nelle zone più fredde$t$, $t$Rimuovere gli steli fioriti appassiti$t$, $t$Tollera bene la siccità estiva una volta ambientata$t$], descrizione = $t$Perenne bulbosa/rizomatosa con vistose infiorescenze a ombrello, blu o bianche, in estate.$t$, esigenze = $j${"luce": "Pieno sole", "acqua": "Regolare in primavera-estate, ridotta in inverno", "terreno": "Ricco, fertile e soprattutto ben drenato"}$j$::jsonb where slug = $t$agapanto$t$;
update specie set famiglia_botanica = $t$Theaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Theaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["autunno"], "resistenza_gelo": "media", "spaziatura_cm": 150, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 20, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$camelia$t$;
update specie set famiglia_botanica = $t$Apocynaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Apocynaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "media", "spaziatura_cm": 100, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 15, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$falso-gelsomino$t$;
update specie set famiglia_botanica = $t$Ranunculaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Ranunculaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 100, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 15, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$clematis-montana$t$;
update specie set famiglia_botanica = $t$Rosaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Rosaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 100, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 15, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.7}$j$::jsonb where slug = $t$spiraea-arguta$t$;
