-- Fase 3 (#120), secondo blocco (20/90 specie usate da piante reali):
-- succulente e piante d'appartamento più usate, più la coda di perenni/fiori
-- comuni. Molte di queste specie non si propagano da seme in coltivazione
-- amatoriale (talea, divisione, bulbo, acquisto di pianta già avviata):
-- lasciato esplicitamente null/vuoto invece di inventare dati di semina che
-- non hanno senso pratico, non un buco dimenticato.
--
-- avocado e pothos non avevano "alert" nella fonte originale (controllato
-- prima di scrivere, come da #132): compilato insieme al resto.
--
-- marsilea-quadrifolia è un caso limite per irrigazione_fattore: è una felce
-- palustre/acquatica, ha bisogno di PIÙ acqua in vaso, non meno — fattore
-- 1.5 invece che <1 come per tutte le altre righe fin qui.

update specie set famiglia_botanica = $t$Crassulaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Crassulaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 15, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 1, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$sedum-acre$t$;
update specie set famiglia_botanica = $t$Lauraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Lauraceae", "giorni_germinazione": "30-60", "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": ["primavera", "estate"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 300, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 15, "rinvaso_ogni_mesi": 12, "irrigazione_fattore": 0.8}$j$::jsonb, alert = ARRAY[$t$Foglie che scuriscono o si seccano ai bordi → aria troppo secca o acqua troppo calcarea$t$, $t$Cresce molto in altezza da seme: potare per compattarlo$t$, $t$Sensibile al freddo sotto i 10°C$t$, $t$Teme i ristagni idrici (rischio marciume radicale)$t$] where slug = $t$avocado$t$;
update specie set famiglia_botanica = $t$Cactaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Cactaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 10, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 1, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.2}$j$::jsonb where slug = $t$mammillaria$t$;
update specie set famiglia_botanica = $t$Crassulaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Crassulaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 15, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 1, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$echeveria$t$;
update specie set famiglia_botanica = $t$Iridaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Iridaceae", "giorni_germinazione": "20-30", "giorni_trapianto": "60-90", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$iris-spontaneo$t$;
update specie set famiglia_botanica = $t$Marsileaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Marsileaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "media", "spaziatura_cm": 15, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 12, "irrigazione_fattore": 1.5}$j$::jsonb where slug = $t$marsilea-quadrifolia$t$;
update specie set famiglia_botanica = $t$Crassulaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Crassulaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 1, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$sedum-spurium$t$;
update specie set famiglia_botanica = $t$Amaryllidaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Amaryllidaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 10, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$narciso$t$;
update specie set famiglia_botanica = $t$Asparagaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asparagaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["autunno"], "resistenza_gelo": "media", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 10, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.5}$j$::jsonb where slug = $t$scilla-marittima$t$;
update specie set famiglia_botanica = $t$Orchidaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Orchidaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": [], "resistenza_gelo": "nessuna", "spaziatura_cm": null, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 1, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.6}$j$::jsonb where slug = $t$orchidea$t$;
update specie set famiglia_botanica = $t$Araceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Araceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera", "estate"], "resistenza_gelo": "nessuna", "spaziatura_cm": null, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 18, "irrigazione_fattore": 0.7}$j$::jsonb, alert = ARRAY[$t$Foglie che ingialliscono → eccesso di acqua o troppa luce diretta$t$, $t$Perde le variegature se riceve poca luce$t$, $t$Le talee in acqua radicano facilmente$t$, $t$Tollera bene la dimenticanza: meglio annaffiare poco che troppo$t$] where slug = $t$pothos$t$;
update specie set famiglia_botanica = $t$Lamiaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Lamiaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 12, "irrigazione_fattore": 0.9}$j$::jsonb where slug = $t$glechoma-hederacea$t$;
update specie set famiglia_botanica = $t$Aizoaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Aizoaceae", "giorni_germinazione": "10-15", "giorni_trapianto": "30-40", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": 25, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.4}$j$::jsonb where slug = $t$mesembriantemo$t$;
update specie set famiglia_botanica = $t$Asteraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asteraceae", "giorni_germinazione": "14-21", "giorni_trapianto": "60-90", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 40, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 8, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$echinacea$t$;
update specie set famiglia_botanica = $t$Saxifragaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Saxifragaceae", "giorni_germinazione": "20-30", "giorni_trapianto": "60-90", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$heuchera$t$;
update specie set famiglia_botanica = $t$Brassicaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Brassicaceae", "giorni_germinazione": "14-21", "giorni_trapianto": "30-40", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["primavera", "autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 30, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.5}$j$::jsonb where slug = $t$iberis-sempervirens$t$;
update specie set famiglia_botanica = $t$Asparagaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asparagaceae", "giorni_germinazione": null, "giorni_trapianto": null, "giorni_raccolta": null, "finestra_semina": [], "finestra_trapianto": ["primavera"], "resistenza_gelo": "nessuna", "spaziatura_cm": null, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 3, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.3}$j$::jsonb where slug = $t$sansevieria$t$;
update specie set famiglia_botanica = $t$Asteraceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Asteraceae", "giorni_germinazione": "10-15", "giorni_trapianto": "30-40", "giorni_raccolta": null, "finestra_semina": ["primavera", "estate"], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 15, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": null, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$bellis-perennis$t$;
update specie set famiglia_botanica = $t$Ericaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Ericaceae", "giorni_germinazione": "30-60", "giorni_trapianto": "90+", "giorni_raccolta": null, "finestra_semina": ["primavera"], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 40, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 5, "rinvaso_ogni_mesi": 24, "irrigazione_fattore": 0.8}$j$::jsonb where slug = $t$erica$t$;
update specie set famiglia_botanica = $t$Primulaceae$t$, ciclo_vitale = $t$perenne$t$, ciclo_colturale = $j${"famiglia_botanica": "Primulaceae", "giorni_germinazione": "14-21", "giorni_trapianto": "40-60", "giorni_raccolta": null, "finestra_semina": ["estate"], "finestra_trapianto": ["autunno"], "resistenza_gelo": "alta", "spaziatura_cm": 20, "consociazioni_favorevoli": [], "consociazioni_sfavorevoli": []}$j$::jsonb, vaso = $j${"adatta": true, "dimensione_minima_litri": 2, "rinvaso_ogni_mesi": 12, "irrigazione_fattore": 0.9}$j$::jsonb where slug = $t$primula$t$;

-- famiglia_botanica di zinnia era vuota anche nella fonte originale
-- (coltivazione.famiglia_botanica = '', non mancante) — corretta qui.
update specie set famiglia_botanica = $t$Asteraceae$t$ where slug = $t$zinnia$t$;
